### ISSUE TITLE
nmbd support

### ISSUE THREAD

**Issue by titpetric** [dperson/samba#10]
Hi,

can you please include/run nmdb? Some devices need nmdb to discover samba hosts, and unfortunately some devices also only support this kind of way of discovery (no manual connection to host).

Best,
Tit

**Comment by titpetric** [comment]
I haven't been able to figure out how to expose nmbd correctly to the host with the default suggested way to run this docker container, my solution was to change the --net option to host, and to run these commands to set up a nmbd instance which works as expected:

```
docker run --net=host --name samba \
            -v /mnt:/mount \
            -d dperson/samba \
            -u "user;pass" \
            -s "public;/mount;yes;yes;yes;all"
docker exec -it samba /etc/init.d/nmbd start
```

So, adding `--net=host`, and dropping specific port forwarding options + run nmbd = works for me. I guess it would be useful to add this to the docs. I'm not exactly sure it's the correct way, but it solves my issue with discovery.

**Comment by dperson** [comment]
I've now added a flag `-n` to start the `nmbd` process to the samba container. Hopefully it will take care of the issue for you. Thanks.
