### ISSUE TITLE
UID/GID 1001

### ISSUE THREAD

**Issue by ShoGinn** [dperson/samba#102]
I use UID/GID 1001 for my media server, I saw when you create the SMBUSER you use the 1001/1000 groups.

Any possible way to allow allocation of a smb user for UID 1001.

(Guess im just asking to make smbuser a UID of like 65530 or something.

Just a thought!

**Comment by dperson** [comment]
The container supports the `USERID` and `GROUPID` environment variables, so you can set the IDs to whatever you'd like. It's in the `README.md`.
