### ISSUE TITLE
cifs share is write-protected, mounting read-only

### ISSUE THREAD

**Issue by lipingxue** [dperson/samba#103]
I tried to start the samba server as a docker service with the following argument
```
 docker service create --name samba-1 -p 1139:139 -p 1445:445 -p 1137:137 -e PUID=1001 -e PGID=1001 --mount type=volume,source=testvol2,dst=/exports dperson/samba -s "public;/exports;yes;no;yes;all; root,liping;root,liping -u root;badpass -u liping;badpass"

```
I passed the parameter "PUID=1001" and "PGID=1001" which are the uid and gid for user name "liping".

Wait for a while, then check to make sure the service start successfully.
```
root@sc-rdops-vm18-dhcp-57-89:~# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                  PORTS
3t833nzmmf7d        samba-1             replicated          1/1                 dperson/samba:latest   *:1139->139/tcp,*:1445->445/tcp,*:1137->137/tcp

```

Then I tried to mount the share with username "liping" with the following option,  and I got the error like the "//127.0.0.1/share1 is write-protected".
```
root@sc-rdops-vm18-dhcp-57-89:~# mount -t cifs  -v -o username=liping,password=badpass,port=30000,uid=1001,gid=1001,file_mode=0777,dir_mode=0777,vers=3.0 //127.0.0.1/share1 /tmp/mnt
mount: //127.0.0.1/share1 is write-protected, mounting read-only
mount: cannot mount //127.0.0.1/share1 read-only
```

But if I try to mount with username "root", it works
```
root@sc-rdops-vm18-dhcp-57-89:~# mount -t cifs  -v -o username=root,password=badpass,port=30000,file_mode=0777,dir_mode=0777,vers=3.0 //127.0.0.1/share1 /tmp/mnt
mount: //127.0.0.1/share1 mounted on /tmp/mnt.

```

Any idea on how to make the share can mount with write permission with non-root user? 
Thanks!

**Comment by dperson** [comment]
A few things that I see, you have `PUID` and `PGID` environment variables being set. My container doesn't use those in any way. I have the `USERID` and `GROUPID` variables that I think will do what you want.

Second, the arguments to the `-s` option should look like this: `"public;/exports;yes;no;yes;all;root,liping;root,liping"` (no space and a closing quote).

Finally, to have the container set the permissions on the volume it's using, pass in the `-p` option.

I think you should be good then.
