### ISSUE TITLE
How to use "-p" option to set permission for files and directory?

### ISSUE THREAD

**Issue by lipingxue** [dperson/samba#104]
This is a followup question for issue #103, which is closed.
I tried the following command to start samba using docker service.
```
docker service create --name samba-1 -p 1139:139 -p 1445:445 -p 1137:137 -e USERID=1001 -e GROUP=1001 --mount type=volume,source=testvol2,dst=/exports dperson/samba -s "public;/exports;yes;no;yes;all;root,liping;root,liping" -u "root;badpass" -u "liping;badpass" -p "files=777,directories=777"
Error response from daemon: rpc error: code = InvalidArgument desc = port '1139' is already in use by service 'samba-1' (yxsiiqcp9tlw4b23r7bbbacs3) as an ingress port
```
The problem is "-p" option is already used by docker to specify the port used for service.  So what is the right format to set permission for files and directory?

**Comment by lipingxue** [comment]
I found the problem, close it.

**Comment by sante85** [comment]
what are the problem?

**Comment by sante85** [comment]
can you specify right command?

thanks

**Comment by dperson** [comment]
The `-p` option to the container is different from the one to docker, and it takes no arguments.
