### ISSUE TITLE
Add docker-compose file example for samba service

### ISSUE THREAD

**Issue by penhauer-xiao** [dperson/samba#105]
as title

**Comment by dperson** [comment]
I'll add one to the repo.

**Comment by maarteNNNN** [comment]
I got this yet:

> version: "3.1"

services:

  samba:
    image: dperson/samba
    ports:
      - 139:139
      - 445:445
    expose:
      - 139
      - 445
    restart: always
    environment:
      - USER=test;test
      - SHARE=testshare;/home/testshare
      - TZ=America_Sao_Paulo

But it doesn't work at all for me, although i'm fairly unfamiliar with samba I can not connect to it on my Windows computer.

The dockers system is running Arch Linux

**Comment by htkoca** [comment]
This is my config: I've been using this for almost a year now. Good uptime, always available on my network. https://raw.githubusercontent.com/htkoca/scripts-bash/master/release/apps/docker/samba/local/docker-compose.yml

**Comment by maarteNNNN** [comment]
@htkoca 
It's still not working for me in Windows, I can see it's receiving something but it doesn't want to connect. Using Linux however I'm able to reach the server using smb://{user}@{ip}/.

But accessing the folders withing the directory Archive/ and Files/, I'm not able to open both anonymously and connect as a user. I receive the error _Failed to open "Files". Failed to mount Windows share: File exists._

On Windows pointing my Explorer to my \\ip\, I get the error _Windows wasn't able to access "\\192.168.0.55\". Please verify the adress and try again._
When I put a random IP to see what happens then I get a different message box: _Windows can't access \\192.168.0.56\_ and it gives me the opportunity to run diagnostics.

**Comment by maarteNNNN** [comment]
For some reason the directories need to be manually created. Now it is taking connections.

**Comment by dperson** [comment]
I was sharing existing files / directories so that was never an issue. I've added a check on share creation, if the directory doesn't already exist it will be created.

**Comment by htkoca** [comment]
thanks @dperson - you always come through!

**Comment by sazima** [comment]
> This is my config: I've been using this for almost a year now. Good uptime, always available on my network. https://raw.githubusercontent.com/htkoca/scripts-bash/master/release/apps/docker/samba/local/docker-compose.yml

404 Not Found

**Comment by htkoca** [comment]
Sorry I've since moved to using webdav.
