### ISSUE TITLE
I want to create 4 users, each other can not see each other, that each other does not feel the existence of each other

### ISSUE THREAD

**Issue by penhauer-xiao** [dperson/samba#107]
I want to create 4 users, each other can not see each other, that each other does not feel the existence of each other, but I click the following settings, but, 4 users can see each other

```
docker run -it --name samba \
  -p 139:139 \
  -p 445:445 \
  -v /home/kent1:/home/kent1 \
  -v /home/kent2:/home/kent2 \
  -v /home/kent3:/home/kent3 \
  -v /home/kent4:/home/kent4 \
  -d dperson/samba \
  -u "kent1;123456" \
  -u "kent2;123457" \
  -u "kent3;123458" \
  -u "kent4;123459" \
  -s "kent1;/home/kent1/;yes;no;no;all;none;none;user_kent1" \
  -s "kent2;/home/kent2/;yes;no;no;all;none;none;user_kent2" \
  -s "kent3;/home/kent3/;yes;no;no;all;none;none;user_kent3" \
  -s "kent4;/home/kent4/;yes;no;no;all;none;none;user_kent4"
```
When I open ```\\192.168.1.2``` in windows and enter user kent1, the password is 123456, 4 users are shown. In fact, I only hope kent1 file can be seen.

![image](https://user-images.githubusercontent.com/6280121/34648676-0db16bc4-f3d9-11e7-977d-abede2a81d59.png)

**Comment by dperson** [comment]
I created this container to make it really easy to setup quick shares that everyone that can login has access.

If you need really advanced configuration, I'd suggest modifying the configuration by hand and setting up a volume with the updated `/etc/samba`, and not using the `-u`, `-s`, etc. options to manage the configuration.

**Comment by penhauer-xiao** [comment]
@dperson I am simple Linux with windows code sharing; but each one's independent.
