### ISSUE TITLE
possible permission speedup on docker start?

### ISSUE THREAD

**Issue by tjeh** [dperson/samba#110]
to speed up the chmod could you consider adding:

```
find $i -type d ! -perm 775 -exec chmod 775 {} \;
find $i -type f ! -perm 664 -exec chmod 664 {} \;
```
instead of:

https://github.com/dperson/samba/blob/e059b4f0fb9c7e916f83143ebab0945335e14207/samba.sh#L66-L67

**Comment by dperson** [comment]
I normally don't have many files on my share and found setting permissions to take a negligible amount of time. I'm not sure how much faster it will be but I've implemented it.
