### ISSUE TITLE
Second user

### ISSUE THREAD

**Issue by jodumont** [dperson/samba#112]
Hi David;

I declare my user as variable
$USER1, $USER2 and $USER3 into an environment file (.env) and it work fine for a general authentication.

Where it bug it when I try to setup these users into the share such as :
```
-s "private;/mnt/private;no;no;no;$USER1,$USER2" # result: only USER1 have access
-s "private;/mnt/private;no;no;no;$USER3,$USER2" # result: only USER3 have access
-s "private;/mnt/private;no;no;no;$USER2,$USER1" # result: only USER2 have access
```

basically only the first $USER to be declare have access

it's the 1st time I use your image, so maybe I miss a config or a parameter ;)

Cheer!

Jonathan

**Comment by dperson** [comment]
Hmm, that looks correct to me. Could you provide the docker logs for the container and a tail of `/etc/samba/smb.conf`? IE run `sudo docker exec -it <samba_container> tail /etc/samba/smb.conf`, using the real container name. Thanks.

**Comment by jodumont** [comment]
hum thank for your help
actually I look inside the /etc/samba/smb.conf and something obvious seems not right

as I mention my user are declare in .env like this:

```
#USER
USER1="me;maux?pass"
USER2="you;maux*pass"
USER3="her:maux!pass"
WORKGROUP="home"
```
and I call them like this:
```
docker run -d \
... \
dperson/samba \                        
-nrS \                          
-s "backups;/mnt/backups;yes;no;no;$USER1" \
-s "docker;/mnt/docker;yes;no;no;$USER1" \  
-s "documents;/mnt/documents;yes;no;no;$USER1" \
-s "downloads;/mnt/downloads;yes;no;no" \       
-s "movies;/mnt/movies;yes;no;no" \        
-s "music;/mnt/music;yes;no;no" \          
-s "pictures;/mnt/pictures;yes;no;no" \    
-s "videos;/mnt/videos;yes;no;no" \    
-u $USER1 \                            
-u $USER2 \
-u $USER3 \                            
-w $WORKGROUP
```
_ps: I don't use the -ti_

and than the obvious in my smb.conf is it use my password for the admin users

```
...
[backups]
   path = /mnt/backups
   browsable = yes
   read only = no
   guest ok = no
   veto files = /._*/.apdisk/.AppleDouble/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
   valid users = me
   admin users = maux?pass
...
```

it is normal ?
it is because I use a special character in my password ?
it is because I double-quote in the .env file ?

**Comment by dperson** [comment]
Well that explains it. The `;` character is used as a field separator, and having it in what's passed into `-u` (to separate the user and password) is correct, passing it and the password to `-s` (setting up a share) is where the problem is, just pass it the user name and you should be fine.
