### ISSUE TITLE
User homes

### ISSUE THREAD

**Issue by kleini** [dperson/samba#113]
I tried to share a users home directory by starting the container with the following options:

    docker run -p 137:137/udp -p 138:138/udp -p 139:139 -p 445:445 -v /home/user1:/home/user1 -d \
        dperson/samba \
        -n -r -u "user1;pass;1000;1000" -s "user1;/home/user1;;no;no;user1"

Files in /home/user1 belong to 1000:1000. But still the user is not able to write to its home directory. When additionally adding a publicly writeable share, that user1 writes files as 100:100.

/etc/passwd and /etc/group look correct inside the container.

**Comment by kleini** [comment]
Okay, stumbled over the force_user and force_group options set inside the container for samba. This does not make any sense at all, especially in combination with configured users having a UID and GID set.

**Comment by dperson** [comment]
Users that are created in docker containers don't necessarily exist outside of them. If you create them both and they have matching UID/GID and passwd keeping them in sync is a pain. I built this container to make it easy to create a share to one to a few users. Managing users in and out of the container was too much work so samba reads/writes all files as a single user. I added the ability to specify IDs based on a request after explaining that it would be pointless.

You can change the UID/GID that samba reads and writes with by setting the `USERID` and `GROUPID` environment variables.

**Comment by kleini** [comment]
Understood. Thanks for clarification. Better solution for my use case would be to mount the following files into the container

    /etc/passwd
    /etc/group
    /etc/samba/smb.conf

to get everything synchronized.

**Comment by dperson** [comment]
Correct, that will do it.

The startup script is really to make creating simple shares easy, complex setups really need to be done by people that know what they want and how to set it up. There are just too many possible options with samba to try to support everything.
