### ISSUE TITLE
Created files are owned by UID=100 instead of user

### ISSUE THREAD

**Issue by t-oster** [dperson/samba#114]
Hi, 

I am trying to set up a samba share so that the permissions correspond to the underlying filesystem permissions. In the shared folder they are set to the correct UIDs and I give the UIDs to the samba container.
But if I create a new file via samba, it is owned by UID 100 instead of the user who is logged in.
This is my docker-compose.yml
(by the way is it possible to specify multiple users in a single environment variable, because you cannot set the same environment variable multiple times. This is why I use the command instead of environment variables to configure users and shares...)

```yml
version: '2'
services:
  samba:
    image: dperson/samba
    command: |-
        -S
        -s Public;/mnt/public;yes;no;no;all;none
        -u thomas;kp9pv;1008
        -u simone;test;1006
        -g "security = user"
    environment:
      - TZ=Europe/Amsterdam
      - NMBD=true
      - WORKGROUP=workgroup
    ports:
      - "139:139"
      - "445:445"
      - "137:137"
      - "138:138"
    volumes:
      - ./public:/mnt/public
    restart: always

**Comment by t-oster** [comment]
I debugged it myself. By default the docker-container's smb.conf is created with `force user = smbuser`... you can disable it with `-g "force user ="`

**Comment by dperson** [comment]
The goal that I had with this container was to be able to very easily start a simple share. Coordinating users / groups / passwords (samba stores as separate passwd hash) between a base host and the container is a PitA (Pain in the Arse), and error prone.

There are `USERID` and `GROUPID` environment variables that you can use to set the UID / GID that files are created as, or you can use the `-g "force user ="` as you did.

Samba has more options than I could possibly support and stay sane, so I went with a simple set. Anything much more advanced really needs custom configuration past what the script can provide.

**Comment by t-oster** [comment]
Hi thanks for the answer. I like your container and did not mean to criticise it. You are right although it works very well for me after adding the parameter.
