### ISSUE TITLE
SHARE ENV Variable

### ISSUE THREAD

**Issue by ShoGinn** [dperson/samba#116]
Can you explain how to do multiple shares using the SHARE ENV variable?
I scrubbed the code and it looks like the sed remark is the same as the argument option.
I could probably just try it, but is the ENV variable designed for just one share not multiple?

**Comment by dperson** [comment]
That is correct, initially I had no support for share setup via ENV. When it was requested I told them of the limitation it would have, and they requested it anyway. It hasn't come back up since then actually.
