### ISSUE TITLE
ENV Variable for share all variables are in quotes

### ISSUE THREAD

**Issue by XtraLarge** [dperson/samba#117]
Hello,
I've installed your docker image today. I've tried to add a share with all parameters as an environment variable, but there was always an error, that said "yes" is not a boolean value.
After changing from volume to a binding location for the config, I was able to take a look at the smb.conf.
I saw that all variables are in quotes, also the boolean values. And samba did not accept >"yes"< as boolean .... it must be >yes<.

best regards Willi

**Comment by dperson** [comment]
Could you please provide the docker run / compose that you used and the relevant share section of the configuration file, please? Thanks.

**Comment by XtraLarge** [comment]
I use Portainer as config gui.

My Image is "dperson/samba:latest" created 2018-02-02 21:45:56 (sha256:25baa173078dda270820d437d57d4fe1b260ac57b209c986c9eb3b3201c23d39)

I only configured 2 ENV VARS:
USER=TESTUSER;TESTPASS
SHARE=TEST;/mount;yes;no;no;TESTUSER;TESTUSER;TESTUSER;TESTCOMMENT

The resulting config smb.conf is:
["TEST"]
   path = "/mount"
   browsable = "yes"
   read only = "no"
   guest ok = "no"
   veto files = /._*/.apdisk/.AppleDouble/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
   valid users = "TESTUSER"
   admin users = "TESTUSER"
   write list = "TESTUSER"
   comment = "TESTCOMMENT"

The error is: 
set_variable_helper("yes"): value is not boolean!

**Comment by Helios747** [comment]
Also having this problem using portainer.

**Comment by tobiebooth** [comment]
I'm also having this issue, using Portainer...somewhat leading me to believe this is an issue with Portainer double escaping something somewhere.

**Comment by tobiebooth** [comment]
#119 fixes this for me

**Comment by dperson** [comment]
The base issue was that the ENV variable handler was missing the `eval` prefix so that the `"` would be parsed by the shell. Doing so allows spaces to be present (useful for the comment field in particular).

Sorry that was missing, and that it took me so long to get to your issue.

The fixed version has been pushed to github, Docker should build it RSN (Real Soon Now).
