### ISSUE TITLE
permission and USERID & GROUPID

### ISSUE THREAD

**Issue by jodumont** [dperson/samba#118]
Hi again;

For sure I miss understood and I don't understand explanation it was given in different issue about the subject but ...

In the container all my share are attributed to `nobody:nobody` and I'm unable to `chown` them
my users appear in /etc/password and they are only able :
- to read in my shares if I `chmod o+r`  
- and write if I `chmod o+w`  
which make sense in the linux world.

So I tried to use : 
`-e USERID:1000` which represent outside of the container my owner  
`-e GROUPID:100` which represent outside of my container my users group
but inside the container all share still attributed to nobody

I also tried to understand the -p but it sadly unclear for me and I just don't get how to pass it
    _-p          Set ownership and permissions on the shares_
again I tried
`-p "1000:100"`
`-p "owner:users"` which owner represent my owner outside of the container and users the group
without noticing any change inside the container (all share are attributed to nobody)

anyway I'll be glad if someone could give me a concrete example of how to use `USERID` and or the `-p option` ;)

**Comment by dperson** [comment]
You correctly set the `USERID` and `GROUPID`.

However, the `-p` flag doesn't take any arguments. It will set the UID and GID to either the default values, or to what you provided in to `USERID` and `GROUPID`.
