### ISSUE TITLE
Disable printers

### ISSUE THREAD

**Issue by pbrisbin** [dperson/samba#12]
This image is working great for me, the only issue is my logs are spammed with:

```
Unable to connect to CUPS server localhost:631 - Bad file descriptor
failed to retrieve printer list: NT_STATUS_UNSUCCESSFUL
```

I think adding

```
load printers = no
```

to the base `smb.conf` would be enough to quiet it.

I'd be happy to PR the `Dockerfile` change, but you may want to implement this as a new argument to `samba.sh` instead of hard-coding a lack of printer support in the image.

**Comment by dperson** [comment]
It's included and rebuilding now. Thank you for the idea and your patience, I was AFK (Away From Keyboard), for a while with the holidays.

For now I've hard coded it, as trying to configure it to use CUPS on another container is past my interest level at the moment. =)

**Comment by pbrisbin** [comment]
Thanks!
