### ISSUE TITLE
No Login/ Permission Erro

### ISSUE THREAD

**Issue by quickbooks2018** [dperson/samba#120]
Dear Concern,

I am very thankful for the useful image for sharing, Mentioned below are the issues I am facing

kindly guide.

I am not able create or share any folder and also I am not able to login, is this is a BUG or any change in code?
please help.....

Regards

docker run --name SAMBA -v /home/asim/Desktop/WINDOWS:/share -it -p 139:139 -p 445:445 -d dperson/samba \
            -u "asim;abc [;5000;smbuser]" \
            -u "root;abc [;1;smbuser]" \
            -s "public;/share" \
            -s "users;/srv;yes;yes;yes;asim,root" \
            -s "asim private;/asim;yes;yes;yes;asim" \
            -s "root private;/root;yes;yes;yes;root"

**Comment by quickbooks2018** [comment]
Bug found command is unable to set a passoword ===>> smbpasswd <====

 get new password.
bash-4.4# smbpasswd asim
New SMB password:
Retype new SMB password:
Failed to find entry for user asim.
bash-4.4# smbpasswd asim
New SMB password:
Retype new SMB password:
Failed to find entry for user asim.

**Comment by dperson** [comment]
The `[` and `]` characters are used to show optional arguments, that can be left out, they're not supposed to be in the actual command line. IE your `-u` (add user) lines should look like the following:
```
-u "asim;abc;5000;smbuser"
-u "root;abc;1;smbuser"
```
