### ISSUE TITLE
any way to adapt it to arm32v6?

### ISSUE THREAD

**Issue by AnderssonPeter** [dperson/samba#121]
Hi i tried to adapt your container for `arm32v6`, so i cloned the repo copied the `Dockerfile.armhf` and created `Dockerfile.arm32v6`.

Then i replaced the first line `FROM resin/armhf-alpine` with `FROM arm32v6/alpine` but when building it i get the following output:
```bash
 docker build samba --file samba/Dockerfile.arm32v6 -t samba:arm32v6
Sending build context to Docker daemon  20.48kB
Step 1/10 : FROM arm32v6/alpine
 ---> 889c6315e8d7
Step 2/10 : MAINTAINER David Personette <dperson@gmail.com>
 ---> Using cache
 ---> 42b4781715b4
Step 3/10 : RUN ["cross-build-start"]
 ---> Running in 6e8bf2c9e765
OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"cross-build-start\": executable file not found in $PATH": unknown
```

any idea what is wrong?
when building your armhf image i get the the following output:
```bash
docker build samba --file samba/Dockerfile.armhf -t samba:armhf
Sending build context to Docker daemon  20.48kB
Step 1/10 : FROM resin/armhf-alpine
 ---> aec40d768dcb
Step 2/10 : MAINTAINER David Personette <dperson@gmail.com>
 ---> Using cache
 ---> 1dcbf1166626
Step 3/10 : RUN ["cross-build-start"]
 ---> Running in dde56ad2dce5
standard_init_linux.go:195: exec user process caused "exec format error"
The command 'cross-build-start' returned a non-zero code: 1
```

but im guessing thats the wrong architecture..

I'm trying to use the image on raspberry pi zero w, I'm just guessing that its only supporting arm32v6.

**Comment by Peter-Optiway** [comment]
I just realized that you provide your armhf build on docker hub, ill try that image there and see if it works!
(Last time i used your image you didn't, good job!!!)

**Comment by dperson** [comment]
The docker hub servers are x86_64 only. To cross-build other platforms on x86_64 the resin folks have built containers that have emulation built in. If you want to native build on non-x86_64, you'll be better off to start with the plain `Dockerfile` and modify it.

**Comment by dperson** [comment]
@Peter-Optiway hope it works for you, please let me know if you have issues with it.
