### ISSUE TITLE
GROUPID not set

### ISSUE THREAD

**Issue by avighier** [dperson/samba#122]
Hi,

I have a strange problem. I am using this command : 

`
sudo docker run \
	--init \
	--name samba \
	-d \
	-it \
	-p 139:139 -p 445:445 -p 137:137 -p 138:138 -p 137:137/udp -p 138:138/udp -p 445:445/udp \
    -v '/test:/test' \
    -e USERID=1001 \
    -e GROUPID=1001 \
    dperson/samba:armv7hf \
    -s "test;/test;yes;no;yes" \
    -w WORKGROUP \
    -nS
`

It globaly works well but the GROUPID part is ignored.

When I execute : 

`sudo docker exec samba getent group users`

I get : users:x:100:

And when I execute :

` sudo docker exec samba groupmod -g 1001 -o users`

Then users is now 1001. If I make a docker stop and start, then the samba now respects the group.

I am not able to explain that ... As samba.sh should change correctly the group id ...

Have you got an idea ?

Thanks

**Comment by dperson** [comment]
I don't have a (current if I ever had one) container with the tag `armv7hf` only `armhf`... can you confirm that you see the issue with the current build from docker hub (IE run `sudo docker pull dperson/samba:armhf` first)? Thanks.

**Comment by avighier** [comment]
Hi,

I can test and I can test with x64 (latest) too. I have pulled the image
from the docker hub (tags tab).

I will test and feedback.

Le 18 févr. 2018 01:58, "David Personette" <notifications@github.com> a
écrit :

**Comment by avighier** [comment]
Hi,

Thanks for help. armhf works well. But I confirm you have the tag ... 4 months ago

https://hub.docker.com/r/dperson/samba/tags/

:)

**Comment by dperson** [comment]
I didn't know that an image got built with that tag on the hub. Sorry for the confusion.

**Comment by avighier** [comment]
No problem. I have spent some hours to configure the container, and now works well. I see you have others usefull, good 👍 

Have a nice day
