### ISSUE TITLE
changed permission on files edited with windows

### ISSUE THREAD

**Issue by jazzdd86** [dperson/samba#123]
Hi,
I am having this issue:
https://stackoverflow.com/questions/20958888/preserving-file-permissions-for-samba-shares-when-file-is-edited
Every time I edit and save an executable script it resets the script from 775 to 664 file permissions and therefore I have to set the executable bit again.

Is it possible to add an option to set map archive to no?

**Comment by firsttris** [comment]
found out

you can use -g "force create mode = 0775"

to set file permissionson create / edit to 775

**Comment by dperson** [comment]
Thanks @firsttris that would have been what I suggested as well. Windows doesn't understand Unix/Linux file permissions, so neither does their file serving protocol. You really just get to set a default for all files.

**Comment by jazzdd86** [comment]
thanks to you both, works like a charm
