### ISSUE TITLE
Windows returns "Not enough diskspace" when writing a bigger file (>500MB)

### ISSUE THREAD

**Issue by reijin90** [dperson/samba#128]
It is mounted as a network drive in Windows. The container has an encrypted ext4 drive mounted. 
Any ideas what the problem is?

**Comment by reijin90** [comment]
Hum, I don't know what the problem was, but I set a volume instead of a direct path to my usb drive (/media/usb/myfolder) and now it seems to work.

**Comment by dperson** [comment]
I've only seen reports of that issue when someone hadn't setup a volume or local path (IE was just using the overlay for the container). I'm glad you found a work around.
