### ISSUE TITLE
Can't enable nmbd

### ISSUE THREAD

**Issue by tenchooo** [dperson/samba#129]
When i run `docker exec -it samba samba.sh -n` it doesn't enable nmdb....how can i fix this?

I already tried disabling firewall, but if i run  `nmblookup` from another computer it says that the server is not answering requests.....

**Comment by dperson** [comment]
First the question, why not pass the `-n` argument (or set the `NMBD` environment variable) when you run the container? That's the only way I've actually tested it... the `exec` options are more for configuration items (adding a user say) than starting processes.
