### ISSUE TITLE
how to set the shared directory as read write

### ISSUE THREAD

**Issue by liuzhiyi0315** [dperson/samba#131]
Hi, 
Hi, Could you please help to see why my shared dir is readonly.
I used the command below to create an instance, [readonly] option is set to "no" in this case

docker run --name "samba" -it -p 139:139 -p 445:445 \
            -v /project/share/:/share \
            -d dperson/samba \
            -u "kxes0;badpass" \
            -s "kxeshare0;/share/kxes0;yes;no;no;kxes0"

**Comment by dperson** [comment]
It could be that the samba user doesn't have write permissions to the path. Try adding the `-p` (set permissions) option after setting up the share.

**Comment by dperson** [comment]
Very good.
