### ISSUE TITLE
Not working with guest (no password) 

### ISSUE THREAD

**Issue by btlaw** [dperson/samba#132]
I use the following docker-compose.yml to deploy samba server.
Host: Debian GNU/Linux 9.4 (stretch)

It works to access from Windows 7, but NOT works from Linux (Debian).
The error is "Timeout on server".

Would you please tell me where is wrong?

<pre><code>version: '2'
services:
  samba:
    image: 'dperson/samba'
    restart: always
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/srv/file-server:/samba'
    environment:
      TZ: 'Asia/Shanghai'
      WORKGROUP: 'WORKGROUP'
    command: -s "file-server;/samba;yes;no;yes;all;none;all" -p
</code></pre>
Here is the docker log:
<pre><code>samba_1   | smbd version 4.7.6 started.
samba_1   | Copyright Andrew Tridgell and the Samba Team 1992-2017
samba_1   | STATUS=daemon 'smbd' finished starting up and ready to serve connections
</code></pre>

**Comment by dperson** [comment]
To follow the recommended security guidelines I set SMB2 as the minimum protocol version in the configuration file. Unfortunately the Linux mount command for CIFS/SMB filesystems doesn't autodetect that it is using protocol v2. To work around it there are 2 options:

1. Use mount options, IE: `sudo mount -t cifs -o domain=domain_name,user=user_name,password=password,vers=2.1 //server/share /mount`
1. Use the `-S` command option for the container to go back to using SMB v1 by default
