### ISSUE TITLE
How to share all mounted drives?

### ISSUE THREAD

**Issue by jwillmer** [dperson/samba#135]
From your Readme I think it should work like this:

```
sudo docker run -it -p 139:139 -p 445:445 -d dperson/samba \
            -u "user;password" \
            -s "media;/mnt;yes;no;no;user" \
```

I find a folder media that is shared but the content is empty but on my Linux server I have mounted two hard drives. Is it a permission problem?

**Comment by Strayer** [comment]
Did you mount /mnt from your docker host in the container? Something like `-v /mnt:/mnt` should be added to the `docker run` arguments. See [Use bind mounts](https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount) in the official Docker documentation.

I'd recommend mounting both paths separately though to avoid accidentally sharing something else from /mnt into the container. E.g. `-v /mnt/disk_a:/mnt/disk_a -v /mnt/disk_b:/mnt/disk_b`.
