### ISSUE TITLE
Read/write shares with volumes under Windows

### ISSUE THREAD

**Issue by jborza** [dperson/samba#136]
Hi,

First, thanks for a great project!

I wanted to use this container as a 'portable' Samba share for integration testing of my https://github.com/jborza/camel-smbj library. 

As my library interacts with a Samba share, the plan is to use a docker volume bound to a local folder as:

`docker run --name smb -it -p 139:139 -p 445:445 -v /tmp/somedir:/share -d dperson/samba -u "user;pass" -s "share;/share;yes;no;yes;user"` -p

and then verify if all actions executed through the samba (smbj) library did what they were supposed to by checking the local folder.

When on Linux, everything works fine, as the -p flag correctly sets up the permissions for `smbuser`. 

On Windows, however, we can't change permissions on these volumes as described here: https://github.com/docker/for-win/issues/497 (as far as I understand due to Docker using cifs for this kind of volumes, where the permissions actions chmod/chown are simply ignored).

A workaround to this problem is to use `root` as the Samba user, as root happens to have correct permissions to the volume.

As of now, I forked the repository into https://github.com/jborza/samba 

Would it make sense to parametrize the user name (smbuser) that Samba in this container is using? If yes, I'd be happy to rework my solution and submit a pull request.

**Comment by dperson** [comment]
I'm not really interested in supporting samba running on docker for windows... It's up to them to implement the normal APIs if they want docker to just work. I don't really have a test environment or the inclination to support that, sorry.
