### ISSUE TITLE
Samba share not providing access?

### ISSUE THREAD

**Issue by Dulanic** [dperson/samba#137]
So I have a strange situation, I can see the files I am sharing from within the container by using exec -it, but it won't allow me access via the share, yet all other folders and files are allowed.... It is owned by my user also.

`docker exec -it “container-id” bash`

```
bash-4.4# ls -l
total 1
drwxr-xr-x    1 dulanic  dulanic          0 Apr 29 05:00 Media
bash-4.4# cd Media
bash-4.4# ls -l
total 1
drwxr-xr-x    1 dulanic  dulanic          0 May 11 02:23 Books
drwxr-xr-x    1 dulanic  dulanic          0 May  4 05:26 DVR
drwxr-xr-x    1 dulanic  dulanic          0 May 11 02:23 Library
drwxr-xr-x    1 dulanic  dulanic          0 Sep 26  2017 Media
drwxr-xr-x    1 dulanic  dulanic          0 Oct  8  2017 Movies
drwxr-xr-x    1 dulanic  dulanic          0 Oct  8  2017 Shows
-rw-r--r--    1 dulanic  dulanic          2 May  5 15:26 mountcheck.txt
```
But if I try to access the folders inside the share, i get an error. All other shares are fine.

![image](https://user-images.githubusercontent.com/2948206/40017336-b448b8b2-577e-11e8-967e-10899b886c09.png)

Here is my run command:
```
sudo docker run -it -p 139:139 -p 445:445 --name=samba -e gid=1000 -e uid=1000 \
-v /docker:/docker \
-v /local-media:/local-media \
-v /downloads:/downloads \
-v /mnt/4K:/mnt/4K \
-v /docker/containers/samba:/etc/samba \
-d dperson/samba \
-u "redacted;redacted" \
-s "docker;/docker;yes;no;no;dulanic;dulanic;dulanic" \
-s "media;/local-media;yes;no;no;dulanic;dulanic;dulanic" \
-s "4K;/mnt/4K;yes;no;no;dulanic;dulanic;dulanic" \
-s "downloads;/downloads/4K;yes;no;no;dulanic;dulanic;dulanic" \
-w "workgroup" 
```

**Comment by dperson** [comment]
I think the error is `-e gid=1000 -e uid=1000` instead of `-e GROUPID=1000 -e USERID=1000`.

**Comment by Dulanic** [comment]
Ended up being a rclone issue the gid uid was fine. Thanks I forgot to close this before. https://forum.rclone.org/t/cache-mount-samba-share-issue/5719/7
