### ISSUE TITLE
multiple shares in docker-compose

### ISSUE THREAD

**Issue by denk-mal** [dperson/samba#138]
is it possible to share more than 1 folder im docker-compose?
It seems to me, that only the last one would be exposed, because the last one will be saved in SHARE.

with something like
`for shr in ${!SHARE*};do eval share $(sed 's/^/"/; s/$/"/; s/;/" "/g' <<< ${!shr}); done`
it should be possible to use all environment vars starting with SHARE like eg. SHARE, SHARE_1, SHARE2, ...

**Comment by two70** [comment]
I'm not sure about having more than one share exposed dynamically like that, but I have multiple shares running from my docker-compose. I just put them all under the command: section, one after another, in the docker-compose file.

`command: -u "user1;pass;1000" -u "user2;pass;1001" -s "user2;/mnt/share/user2/;no;no;no;user2;user2" -s "share;/mnt/share/;no;no;no;user1;user1"`

**Comment by dperson** [comment]
Thanks @two70, that was my answer as well.
