### ISSUE TITLE
Samba removes execution bit during startup

### ISSUE THREAD

**Issue by two70** [dperson/samba#139]
Every time the container restarts it runs `chown -Rh smbuser  /mnt/share/` which is removing the executable bit from my ruby scripts. Because of that they won't run and I have to manually run `chmod +x`.

This is before I start the container: 
`-rwxrwxr-x 1 systemd-timesync users  820 May 18 14:34 rsync.rb`

And this is after I start the container and chown runs:
`-rw-rw-r-- 1 systemd-timesync users  820 May 18 14:34 rsync.rb`

I want chown to run so that my shares are accessible by the appropriate user, I just don't want the files to lose their executable bit. 

Any ideas on how to fix this?

EDIT:
I did try setting the global permissions as suggested here - https://github.com/dperson/samba/issues/123, but didn't have any luck.

**Comment by Strayer** [comment]
Why are you running the container with -p in the first place? As far as I can see, samba.sh will only "fix" the permissions if that argument is set.

**Comment by jan-rivo** [comment]
This is happening to me now actually. if I don't use -p the executable remains and I can run things, but then I can't write files through samba. With the -p I can write files, but not run them. What was the solution here? @dperson
