### ISSUE TITLE
I have got an error,please Help.

### ISSUE THREAD

**Issue by rhinoceros** [dperson/samba#14]
root@myserver:~# sudo docker run --name samba -p 139:139 -p 445:445 -d dperson/samba
5ebec29ef7779a5d65a098b32d91796d7fee5ca7a502b128de125f7590564203
root@myserver:~# docker logs samba
smbd version 4.1.17-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2013
standard input is not a socket, assuming -D option
STATUS=daemon 'smbd' finished starting up and ready to serve connectionsUnable to connect to CUPS server localhost:631 - Bad file descriptor
STATUS=daemon 'smbd' finished starting up and ready to serve connectionsfailed to retrieve printer list: NT_STATUS_UNSUCCESSFUL
root@myserver:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
root@myserver:~# docker images|grep dperson/samba
dperson/samba                                     latest              f9d853709237        38 hours ago        255 MB

**Comment by dperson** [comment]
I'd made a first pass (issue #12) at disabling trying to connect to a local CUPS printing daemon (there isn't one in the container). It should really be disabled now, I'm no longer seeing the error messages.
