### ISSUE TITLE
/var/lib/samba and container recreation / disappearing files

### ISSUE THREAD

**Issue by Strayer** [dperson/samba#142]
While trying to run the container with `read_only: true` I realized that samba is writing several database files to `/var/lib/samba`.

According to the docs these should be preserved:
https://www.samba.org/samba/docs/old/Samba3-HOWTO/tdb.html
https://wiki.samba.org/index.php/Frequently_Asked_Questions#What_are_tdb_files.3F

When using read_only and tmpfs these will disappear on container restart, but this can happen even without using readonly when the container is recreated for whatever reason.

I guess a volume at that location makes sense, though I'm not entirely sure. @dperson, any experience with this?

**Comment by dperson** [comment]
I think you're very likely correct. I haven't really been running my samba container on a regular basis for quite a while, my personal use case went away. I only bring one online briefly from time to time.
