### ISSUE TITLE
Can not connect to the SMB

### ISSUE THREAD

**Issue by Omnipresent** [dperson/samba#145]
I'm on Docker Version 17.09.0-ce-mac35 on mac

I run the service using

```
➜  ~ sudo docker run -it -p 139:139 -p 445:445  -v /Users/omni:/mount -d dperson/samba \
            -u "example1;badpass" \
            -u "example2;badpass" \
            -s "public;/share" \
            -s "users;/srv;no;no;no;example1,example2" \
            -s "example1 private;/example1;no;no;no;example1" \
            -s "example2 private;/example2;no;no;no;example2"
```

But on mac I can not connect to it using Finder > Go > Connect to server. I've tried the following:

```
smb://0.0.0.0
smb://localhost
smb://0.0.0.0/public
smb://localhost/public
smb://<docker_ip>/
smb://<docker_ip>/public
smb://docker.for.mac.localhost/public
smb://docker.for.mac.localhost
```

**Comment by tofixx** [comment]
if running on the same machine, smb://localhost should work while having opened port 139 as above. is there any log available? see https://docs.docker.com/engine/reference/commandline/logs/

**Comment by dperson** [comment]
You may also want to try setting `-S` option to disable SMB2 as a minimum version of the protocol.
