### ISSUE TITLE
Removed parameters still in README.md?

### ISSUE THREAD

**Issue by bunsen32** [dperson/samba#146]
As far as I can see, the environment variables in the documentation, TZ, USERID and GROUPID are no longer used, and should be removed from the README. (Unless I’ve misunderstood the code, but it looks like they are mentioned in old commits, and not referred to in the current code version.)

**Comment by dperson** [comment]
`TZ` isn't really used by the script but many Linux commands automatically support it.

`USERID` and `GROUPID` are still used in the startup script.
