### ISSUE TITLE
Enabling regular builts with the API of Docker Hub for the sake of security

### ISSUE THREAD

**Issue by phocean** [dperson/samba#148]
Hello,

Good job and many thanks for this awesome Dockerfile that covers most use cases.

I see there is an image that is automatically built on the Docker Hub.
It is nice, but it does not seem that you trigger a regular rebuilt, as the current image is 3 months old.

It would be nice if you triggered automatic built with the API (in a cron, for instance), so that the image benefits from all security updates (base image and packages).

Thank you.

**Comment by dperson** [comment]
It's set to rebuild if alpine releases a new image. But maybe I should trigger a new build monthly regardless... Thanks.
