### ISSUE TITLE
"Bad SMB2 signature for message"

### ISSUE THREAD

**Issue by einarpersson** [dperson/samba#150]
I tried to follow your examples `sudo docker run -it --name samba -p 139:139 -p 445:445 -v /home/me/Downloads/:/mount -d dperson/samba`

When I try to connect via my mac (Sierra OSx) it fails.

When I run `docker logs samba` I see the following:
````smbd version 4.7.6 started.
Copyright Andrew Tridgell and the Samba Team 1992-2017
STATUS=daemon 'smbd' finished starting up and ready to serve connections
Bad SMB2 signature for message
[0000] 67 1D F0 3C CC ....... ........
````

Any advice? I did not set up any users etc since I wanted the easiest config possible. Do I have to do some additional mandatory configuration? (was not clear from the readme what was required and what was optional)

Thanks!

**Comment by dperson** [comment]
I do think there has to be a user configured. It's possible that OSX doesn't support SMB2 properly, in that case add the `-S` option.
