### ISSUE TITLE
Request: Specify additional options for share

### ISSUE THREAD

**Issue by voegtlel** [dperson/samba#151]
I'd like a way to set additional options for a share, such as 
```
force user
force group
create mask
force create mode
directory mask
force directory mode
```

Another option would be to inject a custom `/etc/samba/smb.conf` (i.e. do not generate it from commandline args).

**Comment by alexhaydock** [comment]
You can already specify options like that with the `-g-` flag at container run time.

I use
```
-g "force user = nobody" -g "force group = nobody"
```
for example.

The second point is more interesting though. You could bind mount your own `smb.conf` into the container with `-v`, but I'm not sure if the Samba init script (`samba.sh`) will attempt to do anything to it if no other command line arguments are specified. A brief glance at the file suggests to me that it won't though, so you might wish to try it.

**Comment by dperson** [comment]
@alexhaydock you're correct, if no options that modify the configuration are selected it won't mess with the file.

**Comment by voegtlel** [comment]
Still, I'd prefer to have an option to specify a file or environment variables instead of having dozens of `-g "something"` in one line. E.g.:
```
command: '-s "data;/data;yes;no;no;all;none;;Data of Server" -w "MYNET" -g "netbios aliases = alias1 alias2" -g "netbios name = myname" -n -g "force user = myuser" -g "force group = myuser" -g "create mask = 0664" -g "force create mode = 0664" -g "directory mask = 0775" -g "force directory mode = 0775" -u "myuser;blabla" -g "wins server = mywinsserver.mydomain.net" -g "interfaces = eth0" -g "domain master = no" -g "local master = no" -g "preferred master = no" -g "os level = 0"
```
This gets quite messy.

**Comment by dperson** [comment]
Again you don't have to use **any** of the options to configure samba. You can just pass in a volume that has the setup smb.conf and other config files already in place.
