### ISSUE TITLE
Not able to have competitive access to a shared drive 

### ISSUE THREAD

**Issue by sstassin** [dperson/samba#156]
Hi.
I don't really know if it is an issue or a wrong setup of my container on my Pi but :
Can someones of you can confirm (or not) that shared a local pi drive on the network, using a samba container like works without any major performance issues ?

In fact, it work for me but it seems my samba container cannot handle more than one task at the time.
For example, if i start a file tranfert from two computers, the second one is blocked until the first one task is not finished.

Maybe dockerizing a samba server is not a good way (but it is the most handy) to share disk.

Best regards and thank you for the job done.

**Comment by dperson** [comment]
It should work okay. If you experience blocking, I'd think it probably has to do with the speed of the media as SD cards are notoriously slow.
