### ISSUE TITLE
Default config uses 'force user' and 'force group' in GLOBAL section - intended?

### ISSUE THREAD

**Issue by elmorti** [dperson/samba#157]
Just noticed I was not able to write to my share, some brute testing (chmod 777 the share directory) was showing smbuser:users as file owner, when I authenticated to the server with a different smb user.

Checking smb.conf I noticed in GLOBAL:

   force user = smbuser
   force group = users

Therefore it seems that whatever user you log in, it will go with smbuser:users. Is this intended? I can't see this documented other than in the scripts.

**Comment by Fmancino** [comment]
I am experiencing the same problem, what is the idea behind it?

**Comment by Fmancino** [comment]
I realized that you need to use **-p** after declaring the shares, like so:
```
sudo docker run -it -p 139:139 -p 445:445 -d dperson/samba \
            -u "example1;badpass" \
            -s "public;/share;no;no;no;example1" -p
 ```
That changes the permissions for the folder to 775 and gives smbuser ownership of the folder.

I just wander, is all this really necessary? Is it possble to setup writable directories that are not owned by smbuser using this image?

**Comment by dperson** [comment]
The main issue is user management. If you create user in the container they don't get created outside of it. Managing many IDs for ephemeral containers is a PitA (pain in the arse). Forcing the user and group means that outside of the container you only have to manage one user and one group.

This container was created to make it simple to share some files quickly, complex user management is not something that I cared to tackle. If you like the container but want to do something complex with it, just ignore the user/group/configuration management options and mount you configured `smb.conf` into it.
