### ISSUE TITLE
How to use the -p parameter or change the 664 default permission on new files

### ISSUE THREAD

**Issue by kormid** [dperson/samba#161]
Hi, i was reading here in the old issues but i can't find a solution, i tied setting the -p parameter like -p 777 and even files=777 but i don't work, i get 

> ERROR: command not found: 777
> usermod: no changes

 in the logs and the same for files=777 :s

**Comment by dperson** [comment]
`-p` doesn't take arguments to assign different permissions to the files / directories.

**Comment by kormid** [comment]
Thanks :)
