### ISSUE TITLE
handle multiple users and shares via environment variables

### ISSUE THREAD

**Issue by didrip** [dperson/samba#164]
environment variables can be set to get same functionality than command line arguments, ex : `USER="<username;password>[;ID;group]"` in `.env` file is equivalent to `-u "<username;password>[;ID;group]"`passed as argument to `samba.sh`.

The problem is only one env var can be defined this way, whereas for USER and SHARE many can be needed. We can define the same env var multiple times but only the last one will be used.
env vars are more practical than CLI args, especially when using ` docker-compose`. 

It would be nice to have an env var pattern which is looked by `samba.sh`, ex `USER_X` and `SHARE_X` which will be automatically converted to CLI args.

**Comment by dperson** [comment]
Everything that you've said is correct, but is also the original argument that I used when it was requested that I add the option to use environment variables to pass in options in the first place. That they are of more limited utility, and that I didn't want to manage even more complex alternatives, such as you listed or having yet another separator of some form in between records in the one environment variable.

All command line options can be put in the `command:` for the container, and you can store those in environment variables if you wish.

**Comment by monkeydri** [comment]
Oh yes sorry I did not search enough : https://github.com/dperson/samba/issues/138

Would you be OK for a PR with the solution I proposed ?

**Comment by dperson** [comment]
I have a lot of containers that would all need to be updated with these changes. I'll consider making them this coming weekend.

**Comment by dperson** [comment]
Finally checked in the change.
