### ISSUE TITLE
ERROR: Named volume "samba_data:/etc/samba:rw" is used in service "samba" but no declaration was found in the volumes section.

### ISSUE THREAD

**Issue by zen** [dperson/samba#165]
Hi,

Im using following docker-compose definition:
version: '2'
services:
  samba:
    image: dperson/samba
    ports:
      - 139:139
      - 445:445
    volumes:
      - samba_data:/etc/samba
      - /home/username/homeassistant:/homeassistant
    environment:
      - SHARE=homeassistant;/mnt/data/hass;no;no;no;user
      - USER=user;pass
      - TZ='Europe/Warsaw'
      - USERID=1000
      - GROUPID=1000
    restart: always

and getting error in the topic. Any hints?

**Comment by dperson** [comment]
This is a docker-compose error, nothing to do with my container. Please see their [documentation](https://docs.docker.com/compose/compose-file/#volume-configuration-reference).
