### ISSUE TITLE
Configuration for Time Machine

### ISSUE THREAD

**Issue by sc85** [dperson/samba#176]
I am trying to get this working with Time Machine.

What I got so far:
- Samba is running
- Server shows up in Finder
- Reading, Adding, Deleting files on server works

When starting Time Machine the volume is not discovered as long as it is not mounted in Finder. Selecting the volume then seems to work, but as soon as the backup "really" starts it stops right away with an error message that like "Could not access backup volume. User name or password was incorrect".

Besides this I am unsure if the volume should show up in Time Machine directly because of the configuration regarding Avahi. Based on my understanding the file _etc_avahi_services_samba.service is completely unused. Shouldn't this be adapted and then moved into the container? I tried this by editing the txt-record to match with my share name in smb.conf and added it to /etc/avahi/services/samba.service but no luck...

Am I missing something? Anyone else who got this working?

**Comment by dperson** [comment]
I was given a link to the configuration needed to enable time machine to use the samba exports. I got no more complaints from those that asked for the changes.

I didn't really build this container to be a time machine destination, and see no reason that the avahi daemon should be integrated into the container. Indeed it would conflict with a native avahi running on the host server. I'm sure that there are avahi / Zeroconf containers already on docker hub.
