### ISSUE TITLE
Does not restart on "No local IPv4 non-loopback interfaces available"

### ISSUE THREAD

**Issue by naorunaoru** [dperson/samba#178]
Hi. Seems like I'm missing something.

Context: my SMB server is connected via WLAN and the connection becomes available later in the boot stage, I think it's the culprit. 

Incorrect startup looks like this:

```
smbd version 4.8.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2018
[2018/12/15 21:50:35.442849,  0] ../lib/util/become_daemon.c:149(daemon_status)
  daemon_status: STATUS=daemon 'nmbd' : No local IPv4 non-loopback interfaces availab
le, waiting for interface ...
[2018/12/15 21:50:35.442947,  0] ../source3/nmbd/nmbd_subnetdb.c:254(create_subnets)
  NOTE: NetBIOS name resolution is not supported for Internet Protocol Version 6 (IPv
6).
daemon_ready: STATUS=daemon 'smbd' finished starting up and ready to serve connection
s
[2018/12/15 21:50:40.444305,  0] ../lib/util/become_daemon.c:138(daemon_ready)
  daemon_ready: STATUS=daemon 'nmbd' finished starting up and ready to serve connecti
ons
[2018/12/15 21:51:03.479559,  0] ../source3/nmbd/nmbd_become_lmb.c:397(become_local_m
aster_stage2)
  *****

  Samba name server IRON-GIANT is now a local master browser for workgroup WORKGROUP
on subnet 192.168.1.104

  *****
```

And after that no shares are available and I need to manually restart the container.
The line about no local ipv4 interfaces is the only thing that differs from a correct startup. 

My docker-compose.yml:
```
version: '2.1'
services:
  samba:
    image: dperson/samba:latest
    command: >
      -n
      -p
      -r
      -u "naoru;<REDACTED>"
      -s "storage;/shares/storage;yes;no;no;naoru"
      -w "WORKGROUP"
      -g "bind interfaces only = yes"
      -g "interfaces = lo wlp*"
    volumes:
      - /mnt/storage:/shares/storage
    network_mode: host
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    restart: unless-stopped
```

Please help me with resolving my issue. I'm only starting to understand this docker thing. 

Thanks in advance.

Forgot to mention: I use Ubuntu Server 18.10, network is configured via `netplan`. Docker is installed from Ubuntu repo, package name `docker.io`.

**Comment by dperson** [comment]
I think that you're right, docker fails when it tries to set up the forwarding rules when the WLAN isn't up yet. I don't think that's something that can be fixed from the container. You can make docker depend on the network service though.

**Comment by naorunaoru** [comment]
Thank you for your help! I'll look into that.

**Comment by naorunaoru** [comment]
Docker was already dependent on `network-online.target`. 

I did some extensive googling and apparently this is a common problem. 

My problem was solved with setting `wlp1s0 `explicitly in interfaces like so:

```
      -g "bind interfaces only = yes"
      -g "interfaces = lo wlp1s0"
```

**Comment by dperson** [comment]
Glad that you got it resolved.
