### ISSUE TITLE
accessing share from windows without starting nbmd?

### ISSUE THREAD

**Issue by angelochen960** [dperson/samba#179]
Hi,
i got a share 'public', it works if I enable nmbd:

\\\sample\public 
or
\\\10.0.0.99\public

if i stop nmbd, then:
\\\sample\public won't work, I did put sample into a dns and result into 10.0.0.99
but ip works:
\\\10.0.0.99\public

How to access \\sample\public in windows 7 without enabling NMB in the docker/samba side? Thanks

**Comment by dperson** [comment]
I don't know. I built this container to create a share for a network device to access. I really don't hardly ever use windows, so I don't know why it isn't working like it should right now. But being unreliable and doing strange things is the main reason that I don't like it / run it.

**Comment by danieljkemp** [comment]
What happens if you ping the hostname of the samba server with nbmd off?

**Comment by angelochen960** [comment]
there is a dnsmasq running in the same network, so the host where samba docker runs got registered, the hostname is 'sample', so ping sample with nbmd off got a reply,  in Linuxmint I can go to smb://samba.
in Windows 'ping sample' got replies, but can not go to \\sample, if ip, then it's ok: \\10.0.0.99

**Comment by angelochen960** [comment]
finally make it work, add following line:

smb ports = 445

tested in XP and Win7
