### ISSUE TITLE
Multiple docker containers in one host

### ISSUE THREAD

**Issue by angelochen960** [dperson/samba#180]
Hi,

Is there a way to run multiple samba/dockers in one host? we got only one 445 port in the host to map to, any good practice to do this? Thanks.

**Comment by dperson** [comment]
You can have multiple IPs assigned to the host, and in the port mapping specify the IP. Linux allows you to specify the port that you're connecting to as a client, no idea if OSX, Windows, or others do.

**Comment by htkoca** [comment]
If you're exposing Samba to the web (which I don't suggest), You can possibly use a reverse proxy like nginx / nginx-proxy / haproxy / traefik. Not sure if their respective configuration would allow custom ports, you'd have to do some research.

I can't think of another reason you'd want to do so though. Makes more sense to just add shares no?
