### ISSUE TITLE
Disable guest access via docker-compose

### ISSUE THREAD

**Issue by rohitksharma** [dperson/samba#181]
Is it entirely possible to enable guest access to a samba share via docker-compose.yml? I basically have a samba share setup that needs to have its guest account turned off, though the container is up via docker-compose.

**Comment by htkoca** [comment]
```
-s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
                ...
                [guest] allowed default:'yes' or 'no'
                ...
```

**Comment by dperson** [comment]
As @htkoca states, guest access is easily disabled for a share when it's created. The formatting also looks correct.
