### ISSUE TITLE
Triying to make it work with composer - (Error in samba.sh)

### ISSUE THREAD

**Issue by davidjhi** [dperson/samba#185]
Hello!

After reading all the available examples on google, i came up with this fragment (A frankenstein from all the examples that i read):

  samba:
    container_name: samba
    restart: unless-stopped
    image: dperson/samba
    network_mode: host
    hostname: my-samba
    volumes:
      - "${MEDIA}/movies:/movies"
      - "${DATA}/shared:/shared"
    command: >
      -w "MYLAN"
      -u "admin:mypasss"
      -n
      -s "shared;/shared;yes;no;yes;all;none;;Shared\"
      -s "movies;/movies;yes;no;no;admin;none;;Movies\"
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
      - "TZ=${TZ}"
      - "NMBD=True"
      - "RECYCLE=False"

Something is wrong, as i get this on the logs:

`samba          | usermod: no changes
samba          | /usr/bin/samba.sh: line 139: $2: unbound variable
samba          | usermod: no changes`

As the container its not started, i think the referenced file its not available:

`sudo docker-compose exec samba nano /usr/bin/samba.sh`

`Error response from daemon: Container c0f797781c1b47e529b361efd5baf577d8a2a9a382504699926d8ea303654c63 is restarting, wait until the container is running`

Will greatly appreciate any guidance!

**Comment by nemchik** [comment]
I believe I have a similar issue and will try to remember to post the specifics about what I have going on soon.

The basics are that the `-u` flag causes the `/usr/bin/samba.sh: line 139: $2: unbound variable` error for me in the docker logs.

**Comment by jeliasson** [comment]
@dperson By any chance we can have your input on this issue? Thanks!

**Comment by dperson** [comment]
It looks like you're using a colon `:` instead of a semicolon `;` to separate the username and passwd.

**Comment by nemchik** [comment]
I've got a `;` in my implementation here https://github.com/GhostWriters/DockSTARTer/blob/42a169618698482f7e72b47c48794b617000e78f/compose/.apps/samba/samba.yml (just did an adjustment to cleanup the newlines to be more readable) but I seem to not have any luck getting this working (getting the error I commented above). Maybe unrelated?

**Comment by nemchik** [comment]
I've figured out the issues I was having. https://github.com/GhostWriters/DockSTARTer/pull/772 tl;dr don't use quotes around the arguments or environment variables.
