### ISSUE TITLE
Not displaying files in folder previous to creation

### ISSUE THREAD

**Issue by jsyl** [dperson/samba#187]
Hello,

I can't see/interact with the files that were in my folder prior to share creation.

Here is my configuration:

`docker run --name samba -it -p 139:139 -p 445:445 -d dperson/samba \
-u "person:badpass" \
-s "Recipes;/data/recipes;yes;no;no;all;all;yes`

Thank you in advance

**Comment by dperson** [comment]
I would recommend adding the `-p` (set permissions) option to the container arguments as follows:
```
docker run --name samba -it -p 139:139 -p 445:445 -d dperson/samba -p -u "person:badpass" -s "Recipes;/data/recipes;yes;no;no;all;all;yes
```
