### ISSUE TITLE
:latest build on alpine 3.8 instead of 3.9

### ISSUE THREAD

**Issue by smlx** [dperson/samba#188]
Thanks for the awesome container!

I noticed that the :latest tag is based on alpine, which had a new release (3.9) the other day.
I'm trying to build a container based on yours but I need a package from 3.9.. it would be great if you could kick off a new build on docker-hub based on the latest alpine image.

**Comment by dperson** [comment]
Sorry about how busy I've been this year, but it's been updated now.
