### ISSUE TITLE
SMB on Mac , can't connect

### ISSUE THREAD

**Issue by ivanghisleni** [dperson/samba#189]
Hi ,

I'm trying on my mac with this command following the example of issue #84 but I have some connection problem, this is what I've done:

```
docker run -d -it --name samba --rm \
        --net=host \
        -e USERID=0 \
        -e GROUPID=0 \
        --expose 137 -p 127.0.0.2:137:137  \
        --expose 138 -p 127.0.0.2:138:138  \
        --expose 139 -p 127.0.0.2:139:139  \
        --expose 445 -p 127.0.0.2:445:445 \
        -v ivan:/Users/ivanghisleni/workspaces/samba/ivan \
        dperson/samba \
            -s "ivan;/Users/ivanghisleni/workspaces/samba/ivan;yes;no"
```

before I executed :
`sudo ifconfig lo0 127.0.0.2 alias up
`
on docker run I have this message:
...
WARNING: Published ports are discarded when using host network mode
....

the docker logs are:

```
smbd version 4.8.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2018
daemon_ready: STATUS=daemon 'smbd' finished starting up and ready to serve connections
```
but when I'm trying to connect to smb://127.0.0.2 I can't access.

Where I'm wrong?

thanks

**Comment by dperson** [comment]
On MacOS the docker container is running in a Linux VM, so the `host` network isn't your actual host Mac system... remove the `--net=host` line and I think you'll be okay, though I don't really test / support this on Mac or Windows.
