### ISSUE TITLE
Not conneting to Windows 10

### ISSUE THREAD

**Issue by mouzzampk2014** [dperson/samba#191]
Hi, I have this docker compose and could you please look into this for me. Thank you 

 samba:
    command:
    - -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" \ -s "Books;/data/books;yes;no;no;${SAMBA_USERNAME}"
      \ -s "Comics;/data/comics;yes;no;no;${SAMBA_USERNAME}" \ -s "Docker Config;/data/docker/config;yes;no;no;${SAMBA_USERNAME}"
      \ -s "Downloads;/data/downloads;yes;no;no;${SAMBA_USERNAME}" \ -s "Movies;/data/movies;yes;no;no;${SAMBA_USERNAME}"
      \ -s "Music;/data/music;yes;no;no;${SAMBA_USERNAME}" \ -s "TV;/data/tv;yes;no;no;${SAMBA_USERNAME}"
    container_name: samba
    environment:
    - GROUPID=${PGID}
    - TZ=${TZ}
    - USERID=${PUID}
    image: dperson/samba
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${SAMBA_PORT_139}:139/tcp
    - ${SAMBA_PORT_139}:139/udp
    - ${SAMBA_PORT_445}:445/tcp
    - ${SAMBA_PORT_445}:445/udp
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}:/data/docker/config
    - ${DOWNLOADSDIR}:/data/downloads
    - ${MEDIADIR_COMICS}:/data/comics
    - ${MEDIADIR_BOOKS}:/data/books
    - ${MEDIADIR_MOVIES}:/data/movies
    - ${MEDIADIR_MUSIC}:/data/music
![1](https://user-images.githubusercontent.com/44548525/52679619-81d89780-2f2d-11e9-8ebc-71f35177483d.JPG)

    - ${MEDIADIR_TV}:/data/tv

**Comment by daduskacpokus** [comment]
hi, try to connect from windows to "\\192.168.1.84\ downloads"

**Comment by dperson** [comment]
Were there any messages in the log when starting the docker container? or when you tried to connect?

**Comment by mouzzampk2014** [comment]
I fixed the issue and it's working. Only thing I'm noticing is that when I'm moving data  from my Windows drive into samba it's extremely slow.

**Comment by mouzzampk2014** [comment]
`Added user DockSTARTer.
/usr/bin/samba.sh: line 244: $(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}'): No such file or directory
/usr/bin/samba.sh: line 250: $(env | awk '/^SHARE/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
/usr/bin/samba.sh: line 254: $(env | awk '/^USER/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
[2019/07/07 03:01:44.221829,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
  daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.10.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
[2019/07/07 03:02:07.270143,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****
  Samba name server ZEUS is now a local master browser for workgroup APOLLO on subnet 172.17.0.1
  *****
[2019/07/07 03:02:07.272405,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****
  Samba name server ZEUS is now a local master browser for workgroup APOLLO on subnet 172.18.0.1
  *****
[2019/07/07 03:02:07.273424,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****
  Samba name server ZEUS is now a local master browser for workgroup APOLLO on subnet 192.168.1.23
  *****`

**Comment by mouzzampk2014** [comment]
This is the line I am not sure what is that `/usr/bin/samba.sh: line 244: $(env | awk '/^GLOBAL/ {sub (/^[^=]=/, "", $0); print}'): No such file or directory
/usr/bin/samba.sh: line 250: $(env | awk '/^SHARE/ {sub (/^[^=]=/, "", $0); print}'): ambiguous redirect
/usr/bin/samba.sh: line 254: $(env | awk '/^USER/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
[2019/07/07 03:01:44.221829, 0] ../../lib/util/become_daemon.c:136(daemon_ready)`

**Comment by mouzzampk2014** [comment]
Same with this `[2019/07/07 03:02:07.272405, 0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
`

**Comment by dperson** [comment]
Sorry about the fat-finger on the update. I just pushed another change that should fix the error messages you're seeing. Thanks.

**Comment by mouzzampk2014** [comment]
Hehe thank you I think you should close the other one too :)
