### ISSUE TITLE
Improve documentation by showing example of multiple users and different permissions

### ISSUE THREAD

**Issue by dennisvanderpool** [dperson/samba#195]
Hi,

First of all thank you very much for making this docker container :-)

Maybe you can adjust documentation so it's a little bit more clear what to do with multiple users?
I've now used the following config (which now seem to work fine).
1) Do the admin users also have to be in the user list itself?
2) The seperator of users is ",", which is not mentioned or shown in an example?

`docker run -it \
        -d \
        --name samba \
        --restart always \
        -p 139:139 \
        -p 445:445 \
        -e TZ="Europe/Amsterdam" \
        --mount source=samba_data,target=/data \
        --mount type=bind,source=/mnt/data1,target=/mnt/media \
        dperson/samba \
        -r \
        -u "dennis;notmypassword" \
        -u "monika;notmypassword" \
        -s "media;/mnt/media;no;no;no;;dennis;;" \
        -s "dennis;/data/dennis;no;no;no;;dennis;;" \
        -s "monika;/data/monika;no;no;no;monika,dennis;dennis;;" \
        -s "shared;/data/shared;no;yes;no;monika,dennis;dennis;dennis;"`

Greets,

Dennis

**Comment by bingobob** [comment]
i'd like this also - in fact I was hoping there is some sort of web front end that could help me configure shares / permissions etc in an easy manner - but i can't really find one.

**Comment by dperson** [comment]
I built this to create really simple share originally... sigh.
