### ISSUE TITLE
Disabling recycle bin will also affect other vfs objects (fix inside)

### ISSUE THREAD

**Issue by xupefei** [dperson/samba#197]
Hi,

First, I want to thank you for publishing this nice image.

I found an issue regarding the recycle bin, that turns it off will also disable all vfs objects. This is because the `sed` in `recycle` function deletes all lines that contain the word `recycle`:
```
recycle() { local file=/etc/samba/smb.conf
    sed -i '/recycle/d; /vfs/d' $file
}
```
This will delete **all three lines** below:
```
   vfs objects = acl_xattr catia fruit recycle streams_xattr
   recycle:keeptree = yes
   recycle:versions = yes
```
and hence disables other features, e.g. Time Machine which relies on the vfs `fruit`.

This issue can be fixed by just deleting the substring `recycle` from the first line, and leaves others unchanged. Here is a fix with a dirty regex:

```
recycle() { local file=/etc/samba/smb.conf
    sed -i 's/^\(.*vfs.*\)recycle\(.*\)$/\1\2/' $file
}
```
which will output
```
   vfs objects = acl_xattr catia fruit  streams_xattr
   recycle:keeptree = yes
   recycle:versions = yes
```
The last two lines can be left as-is without an impact.

**Comment by dperson** [comment]
Thanks for the report, it's been fixed now. Sorry for the delay.
