### ISSUE TITLE
error opening config file '/etc/samba/smb.conf' with -v "$(pwd)"/etc:/etc

### ISSUE THREAD

**Issue by andruet** [dperson/samba#199]
why fail to run docker with mount option -v "$(pwd)"/etc:/etc,
but successfully run docker with  -v /etc:/etc，
what is difference between "$(pwd)"/etc:/etc and /etc:/etc?
both of them lead to the same behavior in the official document except the place of mount point.

erro information:
smbd version 4.8.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2018
error opening config file '/etc/samba/smb.conf'

**Comment by dperson** [comment]
The error message says that it can't find the `smb.conf` file. I would guess that there is one in your `/etc`, but not in the path in `pwd`.
