### ISSUE TITLE
useradd: user 'notrealusername' already exists

### ISSUE THREAD

**Issue by ersutton** [dperson/samba#20]
after upgrading docker to 1.11.0 my samba container no longer seems to work. Here's the logs that keep repeating in its restart loop:

`17/04/2016 10:37:13smbd version 4.1.17-Debian started.`
`17/04/2016 10:37:13Copyright Andrew Tridgell and the Samba Team 1992-2013`
`17/04/2016 10:37:13standard input is not a socket, assuming -D option`
`17/04/2016 10:37:22useradd: user 'notrealusername' already exists`

here's the compose file I use to make this container:

`samba:`
`  ports:`
`  - 139:139/tcp`
`  - 445:445/tcp`
`  command:`
`  - -u`
`  - notrealusername;notrealpassword`
`  - -s`
`  - share;/share;yes;no;no;notrealusername`
`  - -s`
`  - share2;/share2;yes;no;no;notrealusername`
`  - -s`
`  - private;/private;no;no;no;notrealusername`
`  image: dperson/samba`
  `volumes:`
`  - /mnt/6tb/share/:/share`
`  - /mnt/new6tb/share/:/share2`
`  - /mnt/6tb/privateshare/:/private/``

here's my docker version:

`~$ docker version`
`Client:`
` Version:      1.11.0`
` API version:  1.23`
` Go version:   go1.5.4`
` Git commit:   4dc5990`
` Built:        Wed Apr 13 18:34:23 2016`
` OS/Arch:      linux/amd64`

`Server:`
` Version:      1.11.0`
` API version:  1.23`
` Go version:   go1.5.4`
` Git commit:   4dc5990`
` Built:        Wed Apr 13 18:34:23 2016`
` OS/Arch:      linux/amd64`

Thanks for supplying the great image in the first place - let me know if you want any more details for looking into this :)

**Comment by dperson** [comment]
I'm not on docker 1.11 yet, and I'm out of state on vacation visiting family right now. I'm probably not going to have a chance to look into this until the 25th.

**Comment by ersutton** [comment]
This is for my home server, so there is absolutely no rush to fix (I can always fall back to a normal samba share after all!). Enjoy your vacation.

**Comment by dreamcat4** [comment]
You should take a full shell trace by adding `set -x` near the beginning. Or `#!/usr/bin/env bash -x` as the sheang line of the script (line 1).

**Comment by ersutton** [comment]
@dreamcat4 sounds good - though I am not following. Not sure if you are asking me to modify some script or to change my docker run command.

I tried this:
`docker start ed6d7cbb55be #!/usr/bin/env bash -x`

and then had a quick look at the logs and there was no additional information. Couldn't find what -x does in shell...and couldn't find sheang with a quick search either! give me links, happy to read :)

**Comment by dreamcat4** [comment]
I guess theres no reason why not add a special `-d` debug flag for you to to be able to set from docker run flags. But since there isn't one, then yeah. You have to modify the `samba.sh` script and rebuild the image.

**Comment by longwdl** [comment]
I also can not start this image in my new server (docker 1.11.0).

`Server exit (EOF on stdin)` display after I increased smbd debug level.

[This post](http://unix.stackexchange.com/questions/277114/docker-container-with-samba-exits-without-any-message) may solve the problem.

**Comment by dperson** [comment]
@longwdl @ersutton thank you for your patience, the suggested fix is in place now if you pull a fresh copy.
