### ISSUE TITLE
[Improvement] Performance Improvement 

### ISSUE THREAD

**Issue by lesca** [dperson/samba#201]
Hi, I love this great project! 

However, I encounter performance issue when I upgrade my pi, it is now NanoPi M4, with 1Gbps NIC and 4 USB3.0 ports.  I connect 2 HDDs formatted as NTFS and mounted to the board.

`hdparm` shows the read speed can reach up to 150MB/s.

Copy with smb client is slow -- only 25MB/s at MacOS, and very unstable on Windows -- suddenly drops to zero and freezes when copying files. 

The performance bottleneck must not at my new board -- it must be somewhere inside the container.  So I read the **smb.conf** manual and find out something interesting:
[aio write size](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#AIOWRITESIZE)
[aio read size](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#AIOREADSIZE)

When the two booleans are set to 0, smb will do read and write synchronously. Below is what I do in the docker-compose file:

    ....
    command: '-u "user1;badpass" 
        -g "aio read size = 0"
        -g "aio write size = 0"
        -s "Share;/mnt/share;yes;yes;no;all;none"'

Now, magic happens. MacOS transfer speed increase to 30MB/s, Windows averagely 45MB/s -- without big drop. 

Cheers!!

**Maybe there are more that we can do to improve the performance in container. Share your findings~~!**

**Comment by me1299** [comment]
Seems to help indeed.

Composer file:
```
     environment:
       - GLOBAL=aio read size = 0
       - GLOBAL=aio write size = 0  
```

**Comment by dperson** [comment]
I'd love to hear what this does to performance on x86_64 systems as well as RasPi's...

**Comment by dperson** [comment]
Okay, I've added it by default. Thanks for the tip!
