### ISSUE TITLE
Hide share until user is logged in

### ISSUE THREAD

**Issue by jeff-h** [dperson/samba#206]
I've got a share which is only accessible by a specific user. eg:

```
 -s "MyShareName;/share/from/here;yes;no;no;john"
```

**I'd like the share itself to be hidden in the macOS finder until the user logs in (in this case as `john`).**

However (in macOS at least) when I click on my server in the finder, I see all the shares even before I am logged in to my Samba server. If I double-click one of these shares (which at that point should be inaccessible) the finder window disappears and the following error dialog is displayed:

"The operation can’t be completed because the original item for “MyShareName” can’t be found."

I also have a Synology NAS providing smb shares, and when I click on that, I only see the shares that I am authorised to see, and the list changes when I log in. That's what I'm hoping I can achieve here.

I've researched far and wide and came up with `access based share enum = yes` but that seems to behave the same as `browsable = no` — it renders the share completely invisible even when I am logged in. I tried it both globally (with `-g`) as well as for a specific service in a custom conf file.

Has anyone else managed to achieve this?

**Comment by dperson** [comment]
I never tried, but let me know if you find something.

**Comment by szaimen** [comment]
> I've researched far and wide and came up with `access based share enum = yes` but that seems to behave the same as `browsable = no` — it renders the share completely invisible even when I am logged in.

Unfortunately I experience the same. Was anyone able to solve this problem?
