### ISSUE TITLE
Can't set custom share/volume icon in MacOS

### ISSUE THREAD

**Issue by tapeboy7** [dperson/samba#208]
MacOS creates three files in the root of the Samba share when you set a custom share/volume icon (in the _get info_ dialog):
- .VolumeIcon.icns
- ._.VolumeIcon.icns
- ._.

However, all files with the "**._**" prefix are in the _veto files_ list (thus deleted), making it impossible to set custom share/volume icons for these samba shares in MacOS.

Solution: remove **/._** from the _veto files_ list in /etc/samba/smb.conf

(Or make _veto files_ configurable in the SHARE argument/environment-variable)

**Comment by dperson** [comment]
The number of settings that are available for new shares are already rather crazy... unless this gets more people requesting the option I'm going to pass.
