### ISSUE TITLE
How to prevent executable flag setting for new files?

### ISSUE THREAD

**Issue by dzubape** [dperson/samba#209]
Hello! I try all options from official samba docs, but none works.
1. Your smb.conf file has:
```
create mask = 0664
force create mode = 0664
```
and it seems ok for my case

2. I tried to add:
```
map archive = no
map system = no
```
but it not works

3. I tried readonly = yes + writelist

4. I tried readonly = no

In all cases every new file, created with samba (both from Linux and Windows clients), creates file executable. I need all files 0644 only. How to fix it?

**Comment by darkdragon-001** [comment]
Did you check the permissions on the original files _within the container_?

I guess it is a mounting problem. For me, the mounted files all have executable bit sit, while the files in the volume don't.

**Comment by dperson** [comment]
I'm not seeing the execute bit being set on files created on the share...

**Comment by asgillmor** [comment]
I have experienced this too. Fresh install of Ubuntu 18.04 and docker. MacOS as a client.

```~/samba_test$ ls -l
total 40
drwxrwxr-x+ 2 alex alex 4096 Jan 28 16:05 test_dir_2_from_macos
drwxrwxr-x+ 2 alex alex 4096 Jan 28 16:01 test_dir_from_macos
drwxrwxr-x  2 alex alex 4096 Jan 28 15:58 test_dir_on_server
-rwxrwxr-x+ 1 alex alex   33 Jan 28 16:06 test_file_2_from_macos
-rwxrwxr-x+ 1 alex alex   12 Jan 28 16:01 test_file_from_macos
-rw-rw-r--  1 alex alex   14 Jan 28 15:58 test_file_on_server
```

I believe these are more or less tied to default configs that you generate in `smb.conf.` The + is suggestive of some ACL stuff. When I added the following `acl_xattr:ignore system acls = yes` to the end of `smb.conf` it fixed the file structure at least.

```
-rw-rw-rw-  1 alex alex   12 Jan 28 16:20  test_file_3_from_macos
drwxrwxrwx  2 alex alex 4096 Jan 28 16:20 'untitled folder'
```

So at least it now respects the create mask on the file, but not the directories. 

Maybe this is as intended but there's a lot of configs that are hidden in `samba.sh` and `Dockerfile` that might be better served in a configuration file.

**Comment by nelsyeung** [comment]
@asgillmor Thank you so much! I was pulling my hair out for this problem. Just one comment is that you've also removed `recycle` in your example, which is not necessary.
I now have this in my `docker-compose.yml` environment:
```yml
environment:
  GLOBAL: vfs objects = catia fruit recycle streams_xattr
  # ...
```

**Comment by jeff-h** [comment]
Just for the record, in case anyone else hits this issue, having the `acl_xattr` specified also had the side-effect of breaking macOS's automatic versioning and saving. It caused Pages, Numbers etc to throw errors such as "the document could not be autosaved" and "the document XYZ could not be saved."

Removing it as per https://github.com/dperson/samba/issues/209#issuecomment-579545263 fixed this issue for me.

**Comment by jeff-h** [comment]
Hmm, scratch my last comment. I have since found that my issue was caused by connecting to the share via the Finder window "Locations" section (which results in a connection `smb://servername._smb._tcp.local/Sharename`). When I connect via cmd-k and enter `smb://servername.local/Sharename` macOS's automatic versioning and saving works fine.
