### ISSUE TITLE
Unkown Parameters 

### ISSUE THREAD

**Issue by mouzzampk2014** [dperson/samba#210]
I am getting these a lot. Any idea how can I fix this. Everything working fine just these parameters issue I am not understanding. Thank you

```Ignoring unknown parameter "yes"
Unknown parameter encountered: "yes"
Ignoring unknown parameter "yes"
Unknown parameter encountered: "yes"

**Comment by mouzzampk2014** [comment]
```  samba:
    network_mode: "host"
    command:
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}"
      -s "zeus;/zeus/;yes;no;yes;all;${SAMBA_USERNAME}"
    environment:
      - WORKGROUP=Apollo
      - NMBD=yes
      - RECYCLE=true
      - GLOBAL=yes
    ports:
      - 137:137/udp
      - 138:138/udp
    volumes:
      - ${DOCKERSHAREDDIR}:/zeus/shared
      - ${DOCKERCONFDIR}:/zeus/docker/config
      - /home/zeus/.docker/compose:/zeus/compose

**Comment by dperson** [comment]
Are the messages in the logs? Can you provide more context for them, please?

**Comment by mouzzampk2014** [comment]
> Are the messages in the logs? Can you provide more context for them, please?
I am not getting them after samba updated last night but I am getting these now `Added user DockSTARTer.
/usr/bin/samba.sh: line 244: $(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}'): No such file or directory
/usr/bin/samba.sh: line 250: $(env | awk '/^SHARE/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
/usr/bin/samba.sh: line 254: $(env | awk '/^USER/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
[2019/07/07 03:01:44.221829,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
  daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.10.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
[2019/07/07 03:02:07.270143,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****

  Samba name server ZEUS is now a local master browser for workgroup APOLLO on subnet 172.17.0.1

  *****
[2019/07/07 03:02:07.272405,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****

  Samba name server ZEUS is now a local master browser for workgroup APOLLO on subnet 172.18.0.1

  *****
[2019/07/07 03:02:07.273424,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****

  Samba name server ZEUS is now a local master browser for workgroup APOLLO on subnet 192.168.1.23

  *****`

**Comment by dperson** [comment]
Sorry about that, I fat-fingered the change. A corrected version is checked in now.

**Comment by mouzzampk2014** [comment]
> Sorry about that, I fat-fingered the change. A corrected version is checked in now.

Need your little help apart from this. I have two nfs mounts in ubuntu and both are visible in windows 10 but only issue when I transfer any data between them transfer speed is 10-20mb/s over 1gb lan. But when I transfer files directly from windows 10 I get 110mb/s. Any idea is there something I am missing? Thank you

**Comment by dperson** [comment]
There's an optimization that was recommended. I'll try setting it and see if it helps out.

**Comment by mouzzampk2014** [comment]
Nice one do you have any guide for that :) 

```  samba:
    network_mode: "host"
    command:
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}"
      -s "zeus;/zeus/;yes;no;yes;all;${SAMBA_USERNAME}"
    environment:
      - WORKGROUP=Apollo
      - NMBD=yes
      - RECYCLE=true
      - GLOBAL=yes
    ports:
      - 137:137/udp
      - 138:138/udp

**Comment by mouzzampk2014** [comment]
```  samba:
    command:
    - -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}" \ -s "Books;/data/books;yes;no;no;${SAMBA_USERNAME}"
      \ -s "Comics;/data/comics;yes;no;no;${SAMBA_USERNAME}" \ -s "Docker Config;/data/docker/config;yes;no;no;${SAMBA_USERNAME}"
      \ -s "Downloads;/data/downloads;yes;no;no;${SAMBA_USERNAME}" \ -s "Movies;/data/movies;yes;no;no;${SAMBA_USERNAME}"
      \ -s "Music;/data/music;yes;no;no;${SAMBA_USERNAME}" \ -s "TV;/data/tv;yes;no;no;${SAMBA_USERNAME}"
    container_name: samba
    environment:
    - GROUPID=${PGID}
    - TZ=${TZ}
    - USERID=${PUID}
    hostname: ${DOCKERHOSTNAME}
    image: dperson/samba
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
    - ${SAMBA_PORT_139}:139/tcp
    - ${SAMBA_PORT_139}:139/udp
    - ${SAMBA_PORT_445}:445/tcp
    - ${SAMBA_PORT_445}:445/udp
    restart: unless-stopped

**Comment by dperson** [comment]
Actually if you wouldn't mind testing it, add the following 2 options to the `command:` section:
```
-g "aio read size = 0" -g "aio write size = 0"
```

**Comment by mouzzampk2014** [comment]
Like that
```  samba:
    network_mode: "host"
    command:
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}"
      -s "zeus;/zeus/;yes;no;yes;all;${SAMBA_USERNAME}"
      -g "aio read size = 0" 
      -g "aio write size = 0"
    environment:
      - WORKGROUP=Apollo
      - NMBD=yes
      - RECYCLE=true
      - GLOBAL=yes
    ports:
      - 137:137/udp
      - 138:138/udp
    volumes:
      - ${DOCKERSHAREDDIR}:/zeus/shared
      - ${DOCKERCONFDIR}:/zeus/config
      - /home/zeus/.docker/compose:/zeus/compose
      - /mnt:/zeus/drives
      - /mnt:/zeus/drives

**Comment by dperson** [comment]
Yes, that should set the options.

**Comment by mouzzampk2014** [comment]
Nice one between 40-50 now is there anything we can do to take it upto 110?

**Comment by dperson** [comment]
I'll look into it. I think that I'll set those by default however.

**Comment by mouzzampk2014** [comment]
Coolio. Can I use them in one line or I need to set them in separate lines
```    command:
      -u "${SAMBA_USERNAME};${SAMBA_PASSWORD}"
      -s "zeus;/zeus/;yes;no;yes;all;${SAMBA_USERNAME}"
      -g "aio read size = 0" -g "aio write size = 0"

**Comment by mouzzampk2014** [comment]
Just to make it tidy I tried the first way but I am thinking about putting them in a single line :)

**Comment by dperson** [comment]
Single line will work, but they should be set in the default container image now.

**Comment by mouzzampk2014** [comment]
Coolio I'm using DockStarter and any modification need to be made in compose. When you release a new update tomorrow morning we will automatically get new changes :)

**Comment by mouzzampk2014** [comment]
> Single line will work, but they should be set in the default container image now.

Above logs gone but these came back
```Unknown parameter encountered: "yes"
Ignoring unknown parameter "yes"
Unknown parameter encountered: "yes"
Ignoring unknown parameter "yes"
Unknown parameter encountered: "yes"
Ignoring unknown parameter "yes"
Unknown parameter encountered: "yes"
Ignoring unknown parameter "yes"

**Comment by mouzzampk2014** [comment]
Everything is working fine but samba speed is still very slow, is there any optimization I need to make? Thank you

**Comment by dperson** [comment]
I thought that you'd seen an improvement to at least 40-50 MB/s?

I think that the errors you're seeing are due to the `- GLOBAL=yes` in the `environment:` section.

**Comment by mouzzampk2014** [comment]
Yes errors are fixed :) Thank you 

It's not consistent transfer rate drop to 10MB/s. So I thought should ping you :)

**Comment by dperson** [comment]
Glad that it fixed your issue.

So you're seeing inconsistent speed from the samba container?

**Comment by mouzzampk2014** [comment]
Yes if I move any files into samba location rate goes up to 40 or 50 then drop down to 10. Thanks

**Comment by dperson** [comment]
I'm not sure that I follow the chain of events.

"I move any files into samba location"
I assume that you mean the volume that you shared in on the local drive?

"rate goes up to 40 or 50 then drop down to 10"
Is this for reads, writes, a mixture? Does the speed go up for these specific files and others are slow? Does it run quickly for a few minutes then everything slow down?

**Comment by mouzzampk2014** [comment]
Hi, thank you so much for looking into this for me. Issue was happening because I was transferring data into usb 3.0 external drive and that's why speed was fluctuating. But when I tried directly into ubuntu drive and then I get 100mb something. Thanks again :)

**Comment by dperson** [comment]
Okay, glad to hear that it's resolved.
