### ISSUE TITLE
Improve documentation for smbpasswd

### ISSUE THREAD

**Issue by darkdragon-001** [dperson/samba#211]
# Create dummy configuration file

```
# smb.conf
[global]
    security = user
    encrypt passwords = yes
    passdb backend = smbpasswd
    smb passwd file = /PATH/TO/smbpasswd
```

# Generate smbpasswd file

For every user:

    sudo smbpasswd -c ./smb.conf -a USER

# Run samba container

    -i ./smbpasswd

**Comment by darkdragon-001** [comment]
Where can I find this now?

**Comment by dperson** [comment]
I have no idea what you want... there was no question / problem in the initial issue. I don't understand your followup question...

**Comment by darkdragon-001** [comment]
Well, I would like to save other people time who try to see a bunch of users but don't know how to create a `smbpasswd` file. So I think it would be good to place it in the README for example.

**Comment by dperson** [comment]
Well there are already 2 supported ways to create it:
- `-u` / `USER` environment variable: to create the specified user
- `-i` / `IMPORT` environment variable: import a pre-existing file

**Comment by sushshring** [comment]
I think the issue we run into is the UID matching for users. Importing the file does not add any of the users listed in the file to the Linux passwd.

**Comment by dperson** [comment]
@sushshring I have a check to make sure any users from the file exist or else create a linux account for them, is that not working? Or are you saying that it does but the UIDs don't match?

**Comment by sushshring** [comment]
I believe the latter.

**Comment by dperson** [comment]
The user IDs aren't stored in the `smbpasswd`, so there's no way for me to know what to use...

**Comment by sunny-logic** [comment]
@dperson, thanks for the repo.
Could you please confirm what the content of the smbpasswd file should be before we import it ?

**Comment by h0m3** [comment]
Actually it would be fine to have this in the docs. Follow those steps and you create your smbpasswd to import :P

I was trying to create using another server with a different version of samba without success. So this solved. Log into your container, create the dummy smb.conf, dont forget to change the smbpasswd path to the path you've mapped your smbpasswd on docker, run `sudo smbpasswd -c ./smb.conf -a USER` to add all users and then pass that smbpasswd as -i or IMPORT environment. Recreate your container and success.

I think it wasn't clear the intent of the OP in the issue topic but @dperson could you add these steps on the doc to help people creating their smbpasswd file to import?
