### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by darkdragon-001** [dperson/samba#212]
It took me quite some time to find out that

    /usr/bin/samba.sh: line 139: $2: unbound variable

means that I used a colon (`:`) instead of a semicolon (`;`) when declaring the user.

**Comment by dperson** [comment]
I'm not really sure what to change to fix typos?

**Comment by darkdragon-001** [comment]
What about checking the number of arguments. If smaller than the required number, then tell the user: 

> Error parsing arguments for option "-u". 
> Parsed parameters: _show what has been parsed here_
