### ISSUE TITLE
Recent changes prevent successful connections on my config

### ISSUE THREAD

**Issue by DJFliX** [dperson/samba#213]
Hi! As of recently (10 hours ago) the container does not seem to be able to accept connections on my current configuration. I tried to add logging but apparently I'm doing it incorrectly. I did see that there are some warnings in the logs on starting the container but I'm not sure if they were already there. I did notice that you changes some of the code that handles the variables that are mentioned in the warnings. 

Would it be possible for you to provide me with the docker image sha for the 'regular' build for commit sha `26d20a96a3f2c4be8535af039edc39d984131e85` so I can verify that this is actually caused due to the recent changes?

These are the parameters that unRaid provides based on my configuration in the unRaid GUI:
```
docker run -d --name='PS2Samba' --net='bridge' --log-opt max-size='10m' --log-opt max-file='1' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'SMB'='true' -e 'SHARE'='PS2;/ps2;yes;yes;yes' -e 'GLOBAL'='\"log level = 3\"' -p '446:445/tcp' -v '/mnt/user/Games/Playstation 2/':'/ps2':'ro' 'dperson/samba' 05570d5ccf558f931bf47c9c51ee7317c5ba58c4c74266ddd7c0d8b98868b7c2
```

These are the log entries:
```
/usr/bin/samba.sh: line 240: $(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
/usr/bin/samba.sh: line 246: $(env | awk '/^SHARE/ {sub (/^[^=]*=/, "", $0); print}'): No such file or directory
/usr/bin/samba.sh: line 250: $(env | awk '/^USER/ {sub (/^[^=]*=/, "", $0); print}'): ambiguous redirect
smbd version 4.10.5 started.

Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
```

**Comment by dperson** [comment]
Sorry about that, I fat-fingered the line and then copied and pasted. Just checked in the fixed version.

**Comment by DJFliX** [comment]
Thanks! :)
