### ISSUE TITLE
Errors after recent update

### ISSUE THREAD

**Issue by dr4g0nsr** [dperson/samba#214]
I'm having problems since recent update (i see you updated git 3hrs ago):
/usr/bin/samba.sh: line 245: syntax error near unexpected token `<(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}')'
,/usr/bin/samba.sh: line 245: `done <(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}')'

**Comment by Robert-Arctor** [comment]
Hi, me too...

**Comment by WilliamStam** [comment]
The devs said he fat fingered it and fixed already but I can't get any newer image. Sick as a dog at the moment. Trying to settle in to watch stuff off my server. And now this :( can't connect to my server. Very very very very very grumpy at the moment :(

**Comment by justinjxzhang** [comment]
Think it was just missing a few extra brackets and have submitted a PR in #215. Have built and run on my Pi 4 and it seems to have fixed it, although I don't use any of the new features so not 100% sure if the new functionality is working.

**Comment by dr4g0nsr** [comment]
I reverted to commit ad05a2bb8ba2c174ab01fe89a4094238b441b1c8 and build new docker image, it's now working fine.
Solution from justinjxzhang also seems to work.

**Comment by dperson** [comment]
Sorry guys, what I put in worked in my shell here in testing but not in the container. It should be fixed for real now.

**Comment by WilliamStam** [comment]
Well those errors went away at least. But now it has some unbound variables
````
root@server:/storage.config# docker-compose logs -f samba
Attaching to samba
samba              | Added user william.
samba              | Added user share.
samba              | /usr/bin/samba.sh: line 99: $2: unbound variable
samba              | usermod: no changes
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | /usr/bin/samba.sh: line 99: $2: unbound variable
samba              | usermod: no changes
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | /usr/bin/samba.sh: line 99: $2: unbound variable
samba              | usermod: no changes
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | /usr/bin/samba.sh: line 99: $2: unbound variable
samba              | usermod: no changes
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | Can't load /etc/samba/smb.conf - run testparm to debug it
samba              | /usr/bin/samba.sh: line 99: $2: unbound variable


````

Unless something else changed or I screwed it up trying to force refresh

````
version: '3'
services:
   samba:
      image: dperson/samba
      container_name: samba
      command: >
         -w "WORKGROUP"
         -s ".config;/storage.config/;yes;no;yes;all"
         -s ".storage;/storage/;yes;no;yes;all"
         -s "series;/storage/series/;yes;no;yes;all"
         -s "movies;/storage/movies/;yes;no;yes;all"
         -s "downloads;/storage/downloads/;yes;no;yes;all"
         -s "other;/storage/other/;yes;no;yes;all"
         -u "william;password"
         -u "share;share"
         -n
         -S
         -p
      environment:
         - USERID=${PUID}
         - GROUPID=${PGID}
         - TZ=${TZ}
      volumes:
         - /storage:/storage:z
         - /storage.config:/storage.config:z
      network_mode: host
      ports:
         - "137:137"
         - "139:139"
         - "445:445"
      restart: unless-stopped
````

**Comment by Robert-Arctor** [comment]
Same error here:
/usr/bin/samba.sh: line 99: $2: unbound variable

**Comment by WilliamStam** [comment]
This was 1 crazy bad update then. It always worries me when stuff like this happens. A simple docker and docker compose test would of caught this I'm sure (not that many configurations and I doubt ours are complicated edge cases)

**Comment by WilliamStam** [comment]
@dr4g0nsr you also have issues with the latest fix? Or holding off on the previous for now? 
@dperson ticket might need to be re-opened?

**Comment by dperson** [comment]
Sorry guys, I didn't really want to change how these variables were parsed, but kept getting requests for it. I hope it's really really fixed now.

**Comment by WilliamStam** [comment]
No worries. Code breaks. But you might want to set up a testing branch or something.... :p

**Comment by WilliamStam** [comment]
We have liftoff!!!

````
root@server:/storage.config# docker-compose logs -f samba
Attaching to samba
samba              | Added user william.
samba              | Added user share.
samba              | [2019/07/07 15:41:04.812365,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
samba              |   daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
samba              | smbd version 4.10.5 started.
samba              | Copyright Andrew Tridgell and the Samba Team 1992-2019
samba              | daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
samba              | [2019/07/07 15:41:27.652762,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
samba              |   *****
samba              |
samba              |   Samba name server SERVER is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1
samba              |
samba              |   *****
samba              | [2019/07/07 15:41:27.653197,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
samba              |   *****
samba              |
samba              |   Samba name server SERVER is now a local master browser for workgroup WORKGROUP on subnet 172.30.0.1
samba              |
samba              |   *****
samba              | [2019/07/07 15:41:27.653457,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
samba              |   *****
samba              |
samba              |   Samba name server SERVER is now a local master browser for workgroup WORKGROUP on subnet 192.168.128.1
samba              |
samba              |   *****
````

**Comment by dperson** [comment]
In retrospect I really should have.

**Comment by dperson** [comment]
Thanks for verifying @WilliamStam !

**Comment by WilliamStam** [comment]
Hehe now maybe I can finish watching that episode of ##redacted## that stopped working half way through cause watchtower updated the image :P 

Appreciate the work. I was ready to find a voodoo doll with your name on it earlier tho. Then I just gave up and tried sleeping. Couldn't do a thing on the network here since everything is network shared :(

**Comment by dperson** [comment]
Hope you feel better soon.

**Comment by Robert-Arctor** [comment]
Worked for me aswel.
Thanks a lot!!!

**Comment by GeorgeHahn** [comment]
I opened https://github.com/dperson/samba/issues/216 in response to this - versioned tags would have given us an easy downgrade fix option.
