### ISSUE TITLE
Versioned tags

### ISSUE THREAD

**Issue by GeorgeHahn** [dperson/samba#216]
It would be good to have versioned tags available. This would allow users who wish to upgrade in a controlled manner to stay on a stable version until they're ready to perform maintenance. This would also give users some recourse when `latest` is broken.

An arbitrary repo version number would solve this nicely.

**Comment by dperson** [comment]
I should have made the previous changes in a different branch that would later after testing be merged, but I really have no idea what I'd version the container to... I'm just using the samba provided by upstream.

**Comment by GeorgeHahn** [comment]
Even an arbitrarily chosen number would be sufficient - that would let us stick with one version and update in a controlled manner while also allowing for downgrades in the case of issues.

**Comment by dperson** [comment]
Is there some way to get the docker hub auto build system to assign incrementing version number tags? If there is I don't know what it is. If you can find it, I'll configure it.

**Comment by GeorgeHahn** [comment]
It looks like there are a couple of options. Two that stand out are [GitHub Actions](https://github.com/actions/docker/blob/master/tag/README.md) or automatically/manually tagging after commits on master.

**Comment by dperson** [comment]
That looks interesting, but as far as I can tell provides a CLI to do tagging. That helps some (and seems useful regardless), but is far different from docker hub generating the tags automatically.
