### ISSUE TITLE
latest broken

### ISSUE THREAD

**Issue by kellystuard** [dperson/samba#22]
Please please please push the other versions and future versions as labels on docker hub. Don't only have latest. It makes it impossible to pin to a working version, which means one day I wake up and stuff is broken... like right now.

I see a commit from 5 days ago that might address the issue. Any chance it could be pushed to latest on docker hub?

**Comment by kellystuard** [comment]
Error : standard input is not a socket, assuming -D option

**Comment by dperson** [comment]
I didn't make a change, the latest rebuild was due to the upstream debian image being rebuilt. The commit from 5 days ago is `latest` on docker hub.

**Comment by dperson** [comment]
I'm not on `docker 1.11` myself, but the the folks that are reported the issue. They also confirmed that the change resolved it for them. Are you sure that you have the latest version? Sometimes `docker pull` can be wonky, please try to purge the image `docker rmi -f dperson/samba` and then relaunch it `docker run <your options here>` or `docker-compose up`.

**Comment by kellystuard** [comment]
Following those directions fixed it. Still have no idea what happened. Thank you for the instructions.
Logs:
```
C2016-05-04T18:58:56.654665297Z smbd version 4.2.10-Debian started.
V2016-05-04T18:58:56.654718369Z Copyright Andrew Tridgell and the Samba Team 1992-2014
h2016-05-04T18:58:57.366623964Z STATUS=daemon 'smbd' finished starting up and ready to serve connections
```
