### ISSUE TITLE
Get Samba run on Raspberry Pi 4

### ISSUE THREAD

**Issue by BMWfan** [dperson/samba#220]
Hey,

i have a Raspberry Pi 4 with an installed Raspbian as OS.

I installed Docker and want to use the Samba Container from dperson.

I tried different builts but the docker container stops directly.
`docker image pull dperson/samba`
`docker image pull dperson/samba:armhf`
`docker image pull dperson/samba:armv7hf`

I have mounted my external hard drive to my Raspberry pi  (Path /mnt/ext-hdd ).

This is my start command:

`sudo docker run -it -p 139:139 -p 445:445 -d dperson/samba \
	    -v /mnt/ext-hdd:/ext-hdd \
            -u "test;test" `

How could i get it running?

Best Regards

Daniel

**Comment by isaacwalkercox** [comment]
I am having the same issue

**Comment by dperson** [comment]
Do either of you have any `docker logs <container_name>` output? If it's a script problem, I'll have to see the errors to know what's going wrong for you.

**Comment by BMWfan** [comment]
I find my mistake, i should not only pull the right build version i should start it also with it:

` docker run --name samba -p 139:139 -p 445:445 -v /mnt/ext-hdd:/mount -d dperson/samba:armhf \
            -u "Daniel;test" \
            -u "test;test" \
            -s "Root;/mount/ext-hdd;yes;yes;yes;Daniel" \
            -s "Movies;/mount/ext-hdd/nzb.to/movies;yes;yes;yes;kodi"`

The Container is now running but its not working as expected.
If i try to reach the share \\RASPI-IP then i have only the following folder:
nzb.to/movies but no Folder which should be called Movies and once which should be called Root.

Is there a mistake in my configuration?

If I jump on the container via `docker exec -it samba /bin/bash` then there is the path /mount which has the right structure.

**Comment by dperson** [comment]
If the samba user doesn't have access to the files, then they won't show up either. Group/User IDs inside the container seldom match those outside. If you add the `-p` option to the end of your command line, it will set file permissions / ownership for the container.

If that's not the problem, then you'll probable need to share the error messages showing up in `docker logs samba`.

**Comment by isaacwalkercox** [comment]
Sorry I took so long to get back to you @dperson 

Here is my error: standard_init_linux.go:190: exec user process caused "exec format error"

It would seem I hadn't given the container the correct parameters?

**Comment by daniel-afo** [comment]
@isaacwalkercox you should start it with this container naming: dperson/samba:armhf.
It works for me. 

@dperson thanks to you, now everything is working as expected.

**Comment by BMWfan** [comment]
@isaacwalkercox you should start it with this container naming: dperson/samba:armhf.
It works for me.

@dperson thanks to you, now everything is working as expected.

**Comment by isaacwalkercox** [comment]
Thank you. I will try that now!

**Comment by isaacwalkercox** [comment]
Thanks to everyone. It works. I think we can now close this issue! Unless
people have any other issues?
