### ISSUE TITLE
Error useradd

### ISSUE THREAD

**Issue by aedork** [dperson/samba#221]
i have a problem when i try to run docker-compose 

my docker-compose.yml is:
<hr>

version: '3.4' 

services: 
  samba: 
    container_name: samba <br/>
    image: dperson/samba:rpi
    environment:
      TZ: 'EST5EDT'
    networks:
      - raspi
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - '/external:/external'
    command: '-s "external;/external;yes;no;no;storage" -u "storage;password" -p' 

networks:
  raspi:

And the error in console is: 
<hr>

useradd: cannot lock /etc/passwd; try again later.
samba       | Failed to open /var/lib/samba/private/secrets.tdb
samba       | mkdir failed on directory /var/log/samba/cores: Read-only file system
samba       | Failed to create /var/log/samba/cores for user 0 with mode 0700
samba       | Unable to setup corepath for smbd: Read-only file system
samba       | smbd version 4.5.8-Debian started.
samba       | Copyright Andrew Tridgell and the Samba Team 1992-2016
samba       | mkdir failed on directory /var/run/samba/msg.lock: Read-only file system

please help

**Comment by dperson** [comment]
The errors provided let you know the problems:
```
samba | Failed to open /var/lib/samba/private/secrets.tdb
samba | mkdir failed on directory /var/log/samba/cores: Read-only file system
```
In the `compose.yml` the setting `read_only: true` is in place, so in locations without a volume or tmpfs, samba (as well as all processes can't write there). Add the following after `tmpfs:`
```
- /var/lib/samba
- /var/log/samba
```

**Comment by aedork** [comment]
Thanks for your answer :+1: :rocket:
