### ISSUE TITLE
common shares and additional shares for specific users

### ISSUE THREAD

**Issue by judos** [dperson/samba#222]
This is more a question than issue, as I don't really know how to configure samba correctly.
I would want two users, one with access to /hd/general and one with access to both /hd/user and /hd/general.
Is it possible to setup such that I can connect with windows such that the second user connects once and then sees two folders inside the share (being general/ and user/) ?

I tried like this but obviously when I connect to `192.168.1.5\<share name>` I only get the one shared folder not both.
Also trying to connect to `192.168.1.5\` doesn't work as windows says: "Could not connect to \\192.168.1.5".

The container was started using about these arguments:
```
docker run -it --name samba -p 139:139 -p 445:445 \
--restart='unless-stopped' \
-v /hd/general:/data/general \
-v /hd/user:/data/user \
-d \
dperson/samba \
-u "general_user;<pw>" \
-u "user;<pw>" \
-s "data;/data/general;no;no;no;user,general_user;user,general_user" \
-s "user;/data/user;no;no;no;user;user"
```

Thanks a lot for your help!!

Also bonus question: :)
For a user to be able to write files he needs to be in the admin list. Is this correct?

**Comment by dperson** [comment]
As far as I know SMB (Samba or Windows) wouldn't track permissions differently if you had nested shares (IE the directory of one share is inside another).

No you don't have to be an admin, the share needs to not be read only and you should be on the list of users (if you provide one, it defaults to allowing all authenticated users).
