### ISSUE TITLE
No rights to create files 

### ISSUE THREAD

**Issue by BMWfan** [dperson/samba#225]
Hi,

i again. I had to change the filesystem of my external hard drive from ntfs to ext4 and now i'm trying to reconfigure everything. 

I deleted the old samba container and started once with the following parameters:
`docker run --name samba -p 139:139 -p 445:445 -d dperson/samba:armhf \
 -u "Daniel;test" \
 -u  "test;test" \
 -s "Root;/mnt/ext-hdd;yes;yes;yes;Daniel" \
 -s  "Movies;/mnt/ext-hdd/movies;yes;yes;yes;test" -p`

But if i access this Root Share with the user Daniel and try to create a file, i get the error that i have not the rights to write files.

The docker logs says nothing depending on this.

The folder ext-hdd has the following permissions:
 `drwxrwxr-x  3 systemd-network users 4096 Aug  5 06:51 ext-hdd`

The folder movies was not existing before and was created by the samba docker container itself and has the following rights:
`drwxrwxr-x 2 systemd-network users 4096 Aug  4 18:59 movies`

Before starting of the samba container both folders /ext-hdd and /movies had this permissions:
`drwxrwxr-x  3 root root 4096 Aug  5 06:51 ext-hdd`
`drwxrwxr-x  2 root root 4096 Aug  4 18:59 movies`

How could i solve this issue?

Greetings
Daniel

**Comment by dperson** [comment]
For each of the `share`s / `-s` that you create, you have `yes;yes;yes` set. The 2nd `yes`, is confirms that you want it to be a read-only share, if you want it to be writable, you'll have to change it.
