### ISSUE TITLE
mount succeeds but I get "access is denied" when I try to switch to drive 

### ISSUE THREAD

**Issue by rhildred** [dperson/samba#226]
I am trying to use the container to share a docker volume.  I run this command:

```

docker run -it -p 139:139 -p 445:445 -v fixed-disk:/myvol dperson/samba \
            -u "example1;badpass" \
            -s "data;/myvol;no;no;no;example1"

```

On the windows machine on the same subnet I do:

```
C:\Users\Administrator>net use g: \\172.31.16.219\data /user:example1
Enter the password for 'example1' to connect to '172.31.16.219':
The command completed successfully.


C:\Users\Administrator>g:
Access is denied.

```
back from my container I get the error:

```
smbd version 4.10.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
change_to_user_internal: chdir_current_service() failed!

```

I can sh into the container with `docker exec -it 45a003a63e40 sh`. I see the contents of myvol as I would expect. Any ideas?

**Comment by dperson** [comment]
The most likely source is that the permissions on the files / directories don't allow the samba user access to the files. I'd suggest adding the `-p` (set permissions flag) at the end of your command line.

**Comment by rhildred** [comment]
You are good!

Thanks so much for your quick response.
