### ISSUE TITLE
how to create public folder with all permission?

### ISSUE THREAD

**Issue by sante85** [dperson/samba#227]
i have read readme, but when i create a public folder, samba tell me permissions

sudo docker run -it -p 139:139 -p 445:445 -d dperson/samba  -s "public;/public;no;yes;no"

**Comment by dperson** [comment]
Add the `-p` option to the end of your options to the container, or set the `PERMISSIONS` environment variable.

**Side note**: The options that you set for the share specify that it **is not** browsable, **is** read-only, and **is not** accessible by a guest.

**Comment by sante85** [comment]
can  you explain with an example??



Il giorno lun 12 ago 2019 alle ore 13:22 David Personette <
notifications@github.com> ha scritto:

**Comment by sante85** [comment]
"is not browsable, is read-only, and is not accessible by a guest"

in fact i have set: no -> is browsable
yes is not readonly
no -> access for guest.

is right?

but folder have no write permissions

**Comment by dperson** [comment]
Example of adding `-p` to the end:
```
sudo docker run -it -p 139:139 -p 445:445 -d dperson/samba -s "public;/public;no;yes;no" -p
```
You're wrong about the read-only, they're all `is ___`, none of them are `is not ___`.

**Comment by sante85** [comment]
ok, but if i set -v  as volume mount not work

 sudo docker run -it -p 139:139 -p 445:445 -v /srv/samba/sante:/public -d
dperson/samba -s "public;/public;no;no;yes" -p

Il giorno lun 12 ago 2019 alle ore 23:42 David Personette <
notifications@github.com> ha scritto:

**Comment by dperson** [comment]
What error are you getting in the samba containers logs and/or on the client? What isn't working (what is the behavior you expect vs. what you're seeing)?

**Comment by sante85** [comment]
to show error docker logs container id?

I expect that the directory be so visible.



Il 14 ago 2019 2:59 AM, "David Personette" <notifications@github.com> ha
scritto:

**Comment by dperson** [comment]
`sudo docker logs <container_name>`, replacing `<container name>` with the actual container name.

As I pointed out to you before, you are explicitly turning off making it browsable (visible).

**Comment by sante85** [comment]
cmd:

sudo docker run -it -p 139:139 -p 445:445 -v /srv/samba/sante:/public -d
dperson/samba -s "public;/public;no;no;yes" -p


logs
chown: /public/test/iot/README.md: *Permission denied*
......


permission in folder
[root@centos ~]# ls -la /srv/samba/sante/
total 12
drwxr-xr-x.   3 root root   20 Nov 18  2018 .
drwxr-xr-x.   5 root root   46 Nov 29  2018 ..
drwxr-xr-x. 149 root root 8192 May 21 09:23 test



Il giorno mer 14 ago 2019 alle ore 13:16 David Personette <
notifications@github.com> ha scritto:

**Comment by dperson** [comment]
Okay, you're on CentOS. This is very likely SELinux permission related add a `:z` to your volume docker option, IE: `-v /srv/samba/sante:/public:z`

**Comment by sante85** [comment]
Thank you

Il 14 ago 2019 6:17 PM, "David Personette" <notifications@github.com> ha
scritto:
