### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by braddevans** [dperson/samba#230]
untill command `pdbedit -L` is run as root
before that command no access since it print out 
```
read_fd_with_timeout failed for client 0.0.0.0 read error = NT_STATUS_CONNECTION_RESET.

read_fd_with_timeout failed for client 0.0.0.0 read error = NT_STATUS_CONNECTION_RESET.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 164.52.24.171 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 0.0.0.0 read error = NT_STATUS_CONNECTION_RESET.

read_fd_with_timeout failed for client 119.28.100.67 read error = NT_STATUS_END_OF_FILE.
```

**Comment by braddevans** [comment]
i solved this issue but i thought i would mention it

**Comment by dperson** [comment]
The only time `pdbedit` is called by the container is if you're importing some predefined users... I'm not sure that I follow what you're saying triggered the error or resolved it.

**Comment by vamsi2257** [comment]
Hi @braddevans 

How you solved this issue ? Could you please provide action plan / steps how you resolved.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 96.127.158.234 read error = NT_STATUS_END_OF_FILE.

read_fd_with_timeout failed for client 164.52.24.171 read error = NT_STATUS_END_OF_FILE.
