### ISSUE TITLE
how to mount multiple volume ?

### ISSUE THREAD

**Issue by sante85** [dperson/samba#232]
how to mount multiple volume ?

**Comment by dperson** [comment]
Mounting multiple volumes into a container is covered in the docker documentation, please see it.

**Comment by sante85** [comment]
Buy i want map any volume with different folders to share?
How to do?

Il gio 29 ago 2019, 00:09 David Personette <notifications@github.com> ha
scritto:

**Comment by dperson** [comment]
You call the `-s` command line argument multiple times.
