### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by mouzzampk2014** [dperson/samba#234]
Hi, every time I restart the container I see these logs. The one in red I am not sure about and the one in yellow repeat twice. If its possible or you have little time could you look into this one. I use this image a lot so I thought lets tidy up the logs :) 

First time when I created this image first line added as Added user mouzzampk. Then after every time I restart the container I see usermod: no changes. Can we look into this too.

Thank you so much :)

![3](https://user-images.githubusercontent.com/44548525/63900668-2bc6cf80-c9f9-11e9-875b-c09285dc62cd.JPG)

**Comment by dperson** [comment]
The logs in red are just messages from the daemons on startup, letting you know their status. If you look back at the messages in yellow, you'll notice that it's telling you about both the `nmbd` and `smbd` daemons, that each of them are now in a ready state.

As for the `usermod` message, it will only show up if you're setting the `USERID` environment variable.

**Comment by mouzzampk2014** [comment]
Thank you so much for the detailed explanation. You have been always very helpful.
