### ISSUE TITLE
Incorrect Architecture tag in Docker hub images

### ISSUE THREAD

**Issue by amondit** [dperson/samba#235]
Hello, and thank you for your hard work on these images, it's very much appreciated!

However, I am facing an issue deploying a samba container in Docker Swarm. The samba images I am fetching from Docker Hub have an incorrect "`Architecture`" tag of "`amd64`" instead of the relevant one (`arm` or `arm64`, depending). This usually happens when you are cross-building the images on a different architecture (like using the docker hub automated builds)

I am running on a Raspberry 4 on Ubuntu 18.04 with arm64 kernel, and launching the images via docker-compose or docker-run works just fine, but deploying them via docker stacks leads to a failed deployment (`no suitable node (unsupported platform on 1 node)`).

You can see from your images:
```
$ docker image inspect dperson/samba:aarch64 | grep Architecture`
        "Architecture": "amd64",
```

**Comment by dperson** [comment]
The images are cross-built on the docker hub with automated builds. My search failed to find a way to set the architecture manually on these builds. I'll be glad to make a change to the appropriate `Dockerfile` if you can point me to what's needed.

**Comment by dperson** [comment]
I'll try building it that way (I like it better than using the resin included pre-made containers anyway), but don't see anything in that thread that indicates that it going to fix the tag, just allow the arm builds to run on the "amd64" architecture.

**Comment by amondit** [comment]
From what I understood (but I may be wrong), the purpose is to have the Docker Hub build machines (which are amd64) to run the docker build process inside a aarch64 (or armhf) container. That way the output docker images are correctly tagged, as if they were build on arm.

**Comment by dperson** [comment]
The current builds take place on the docker hub build servers, just using containers that were created by someone else to let them run on the amd64 systems.

**Comment by dperson** [comment]
Okay, I'm far from certain if this change has fixed the issue for you or not, but if you pull the latest image it's built using the new method.

**Comment by amondit** [comment]
I just fetched the latest dperson/samba:aarch64 and I'm still not able to deploy the image on docker swarm (`no suitable node (unsupported platform on 1 node)`) and the Architecture tag is still `amd64` :(

**Comment by dperson** [comment]
Well unless you come up with another idea for fixing it, I don't see anything in their documentation for changing the architecture from the platform it's built on (even if cross built).
