### ISSUE TITLE
Can't connect to my samba server

### ISSUE THREAD

**Issue by akation** [dperson/samba#237]
Hi,

First of all thank you for this docker image, it rocks.

I am using it on my raspberry pi, everything was fine but suddenly I cannot connect anymore from my mac, and i cant understand why, the container is running, i can ping my raspberry pi from my mac, I dont know what else to do.

This is my docker-compose.yml

version: "3.3"

services:

  samba:
    image: dperson/samba:rpi
    restart: always
    command: '-u "pi;password" -s "home/pi;/home/pi;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /home/pi/:/home/pi

I hope you can help me, thank you.

**Comment by dperson** [comment]
Sorry this ticket got lost in my inbox.

There was a rebuild at around that time, but that shouldn't have really broken anything... I do notice that you're using the `rpi` tag... I don't have that tag on my builds. Depending on the version of Raspberry Pi you have (64-bit CPU or not) use one of:
* `dperson/samba:armhf`
* `dperson/samba:aarch64`
