### ISSUE TITLE
/var/cache/samba on ssd ?

### ISSUE THREAD

**Issue by yyysuo** [dperson/samba#239]
Thank you for the very good docker image，and I noticed that there is a volumn bind named /var/cache/samba，I run the container on a SSD,So,Should I bind the volumn to a another place to avoid mass data write to my SSD?

**Comment by dperson** [comment]
I seriously doubt that it will wear out your SSD, but if that's a concern for you feel free to mount a tmpfs there (see the docker documentation for how to do that).
