### ISSUE TITLE
Feature Request: Hide Dot Files

### ISSUE THREAD

**Issue by lukeawyatt** [dperson/samba#240]
Samba by default hides files prefixed with a period (.gitignore for example).  It'd be nice to change this.

Within Samba.sh, adding this extra line of code to the config builder will flag this setting off.  Maybe it can be an extra option.

```
echo "   hide dot files = no" >>$file
```

**Comment by dperson** [comment]
The management script that comes with the container supports the `-g` option that will let you add that to the samba configuration (see the `README.md`).
