### ISSUE TITLE
CHARMAP mappings not working

### ISSUE THREAD

**Issue by carlba** [dperson/samba#241]
I have this in my docker-compose.yaml for the samba service
```yaml
    environment:
      - CHARMAP=0x22:0xa8,0x2a:0xa4,0x2f:0xf8,0x3a:0xf7,0x3c:0xab,0x3e:0xbb,0x3f:0xbf,0x5c:0xff,0x7c:0xa6
```

When I start the service I get this in the log
```bash
sed: unmatched '/'
```

**Comment by dperson** [comment]
Sorry about that, something got messed up in that function. It should be fixed now.
