### ISSUE TITLE
"Volume-less" / stateless image?

### ISSUE THREAD

**Issue by w-flo** [dperson/samba#244]
Hi and thanks for maintaining this image!

All the samba configuration I need is stored in a docker-compose file that mounts my data dirs as custom volumes and uses the dperson/samba flag "-s" to add shares. So the container is ephemeral and can be dropped and recreated completely at any time without breaking anything.

Now those 5 volumes defined in the Dockerfile are a bit annoying in my case, because anonymous volumes are created for them when I (re-)create the container. I don't think they are necessary in my case, as I don't really want to keep around log files or configuration files. I'd prefer to have a fresh container (with just my config flags from the docker-compose file applied) every time I recreate it, but I can't find a way to disable VOLUMEs specified in the Dockerfile so it doesn't "pollute" my docker volume list with those 5 volumes. It appears like there actually is no way to drop VOLUMEs defined in the Dockerfile.

I guess some people may have a use case for those volumes and want to keep them, but couldn't they just specify them manually, or in their docker-compose file or whatever method they use to manage containers? I feel like VOLUMEs in a Dockerfile are useful when that place stores data that you absolutely WANT to keep around in almost every possible use case and it would be dangerous to forget setting up a volume yourself.

Do you think it would be possible to drop those VOLUMEs from the Dockerfile? Otherwise I'll mount named volumes to all those locations so that I can at least identify what they are by looking at their name, but I'd prefer to not have these volumes at all.

**Comment by dperson** [comment]
No, those are in place to allow the container to function when it's set to RO (read only), which is security related. I'm much more inclined to optimize for that rather than esthetics of the volume list (which few people are likely to look at). Sorry.

**Comment by dperson** [comment]
No, those are in place to allow the container to function when it's set to RO (read only), which is security related. I'm much more inclined to optimize for that rather than esthetics of the volume list (which few people are likely to look at). Sorry.
