### ISSUE TITLE
Isn't Using Specified Path

### ISSUE THREAD

**Issue by trek-e** [dperson/samba#246]
I'm attempting to point the share to a specific path.

Instead, it goes into a docker shim directory.

The command line I'm using is:

sudo docker run -it --name samba -p 139:139 -p 445:445 -d dperson/samba -p -u "uname/password" -s "tesla;/var/lib/plexmediaserver/Media/samba/directory;no;no;no;uname;yes"

It works fine, except it's not storing the files where i'm pointing too.  I'm not getting any errors in the command line, and the logs just say 'samba started' but not anything else.   Am I misunderstanding something?  i thought the -s command used that directory specified.

**Comment by dperson** [comment]
It's using the specified directory, but it's the directory (if it exists) inside the container. If you want it to be the one from the host system you'll have to use the docker `-v` command line option to mount it into the container (it has to go before the `dperson/samba`).
