### ISSUE TITLE
Add bind interfaces parameter

### ISSUE THREAD

**Issue by SoerenBusse** [dperson/samba#247]
Hey there,

would it be possible to support the `bind interface only` option? 
This would be extremely useful if you have multiple network interfaces where one of them is accessible from the public internet.
https://wiki.samba.org/index.php/Configure_Samba_to_Bind_to_Specific_Interfaces

**Comment by dperson** [comment]
The whole point of the container is that it isn't running on your host system, that includes the host network and it's devices.

That being said, look more closely at the `-p` port forwarding command for docker. Each port that gets forwarded to the container can be bound to a specific IP on the host itself.
