### ISSUE TITLE
/var/lib/samba persistence

### ISSUE THREAD

**Issue by tardich** [dperson/samba#248]
I'm trying to find out how I can persist /var/lib/samba (well, guess that's what I need to persist over reboots. But if I mount a volume on it, the container just crashes. 

I'm trying to find hw I can start with an empty directory the provision everything. I was used to this command: "samba-tool domain provision" but the tool doesn't exist in the docker image.

I'm using latest for aarch64 that was created 3 days ago.

Thanks,

**Comment by dperson** [comment]
Below are the contents of a fresh containers `/var/lib/samba` just recreate the 3 directories and their permissions in the volume that you mount into the container and you should be fine.

```
bash-5.0# ls -AlFR /var/lib/samba
/var/lib/samba:
total 0
drwxrwx---    1 root     root             0 Sep 18 13:52 bind-dns/
drwx------    1 root     root             0 Sep 18 13:52 private/
drwxr-xr-x    1 root     root             0 Sep 18 13:52 sysvol/

/var/lib/samba/bind-dns:
total 0

/var/lib/samba/private:
total 0

/var/lib/samba/sysvol:
total 0
```

As for being a domain controller, that is a very advanced / complex use case. That's far beyond what I have the time / interest to support. I'm just trying to make creating a simple share a simple thing.
