### ISSUE TITLE
How do I create a Samba service in swarm mode and share a named volume?

### ISSUE THREAD

**Issue by bobfraser1** [dperson/samba#25]
I'm using Docker in swarm mode and I want to create a service that runs Samba and shares a named data volume.

**Comment by bobfraser1** [comment]
This worked for me:

Assuming you have Docker 1.12 or later swarm cluster.

Pick a worker node to host your data (e.g. worker1).

First set a node label:
SSH into a manager node (e.g. manager1) and execute the following:
`docker node update --label-add value "type=data" worker1`
The key and value are arbitrary.

In a new shell window SSH into worker1 and execute the following:
`docker volume create --name data`
The name is arbitrary. Your data will only exist on this node.

Back in your manager1 SSH session execute the following to create a service:
```
docker service create \
  --name samba \
  --constraint 'node.labels.type == data' \
  --publish 137:137 \
  --publish 139:139 \
  --publish 445:445 \
  --mount src=data,dst=/data \
  dperson/samba -n -p -s 'data;/data;yes;no;yes;yes'
```
This will create a service that will share the volume 'data' with guest,rw access.
You should be able to mount the volume by pointing at any node in your swarm cluster. Mesh networking will take care of routing traffic to the node actually hosting the volume.

On the manager node `docker service ls` will show the service.
`docker service ps samba` will show the task running on node worker1.

On worker1 `docker ps` will show the running container.

Hope this helps someone.

**Comment by bobfraser1** [comment]
@dperson Thanks for the awesome work on the Samba container!

**Comment by dperson** [comment]
Sorry to not get back to you sooner, I've been moving as well as working and haven't had time. I'm glad that you figured out the issue.
