### ISSUE TITLE
Setting permissions

### ISSUE THREAD

**Issue by me2000** [dperson/samba#250]
Hi,

I am using the container from a docker-compose file configuring it by setting environment variables. Setting the PERMISSIONS variable I noticed that it didn't seem to do anything. When looking into samba.sh I saw that first perms() is called iterating through /etc/samba/smb.conf and then the SHARE* variables are parsed. So when perms() is called there are no shares configured and so no permissions are set. I had to go into the container after starting it to set the permissions.

I would like to suggest to change the order of variable parsing in samba.sh to make sure that smb.conf is complete before perms() is called.

Cheers, ME

**Comment by dperson** [comment]
Thanks! that's a good suggestion. The next build will have it in there.
