### ISSUE TITLE
Disable veto file

### ISSUE THREAD

**Issue by Rhyscoch** [dperson/samba#252]
Hi!
With veto file option rsync on osx not work correct. Need option to disable add veto file to all shares.
Thank you.

**Comment by dperson** [comment]
Edit the generated file by hand.

**Comment by sam2kb** [comment]
We really need an option to disable veto files through ENV. You can make the ENV default to whatever values it is currently adding to the config.

This particular veto filter skips a whole lot of legit files `._*`

**Comment by dperson** [comment]
Okay you can set an environment variable `VETO` to `no` and you won't have vetoed files on any of your shares.

**Comment by mabelisle** [comment]
> Okay you can set an environment variable `VETO` to `no` and you won't have vetoed files on any of your shares.

I was using the parameters:
 -g "veto files = /._*/.DS_Store/" \
 -g "delete veto files = yes"

 But now I get /usr/bin/samba.sh: line 108: VETO: unbound variable

What was the change and how do I fix it?

**Comment by dperson** [comment]
Doh! sorry for the fat-finger.
