### ISSUE TITLE
"force user = smbuser"

### ISSUE THREAD

**Issue by dkhokhlov** [dperson/samba#253]
Is there way to disable these options that enabled by default:

force user = smbuser
force group = smb

?

Use case:  
sharing docker volume and with using specific "user id", such that new files have "user id" owner, but not smbuser.

**Comment by dperson** [comment]
That user won't necessarily exist in other containers and/or the host system (if it does it will likely have the wrong UID/GID), so I'm not sure that's what you really want.

Look into the `USERID` and `GROUPID` environment variable settings (they're covered in the `README.md`).

**Comment by dkhokhlov** [comment]
1. install container with specifc UID/GID sharing volume pointing to specific folder on host
2. connect share using UID on remote client
3. create file in share on remote client
4. file will be owned by smbuser. ( caused by see setting in smb.conf - see above)

Expected: file owned by UID

Workaround: disable these force settings.

Bug

**Comment by dperson** [comment]
It doesn't matter if the force statements are in place or not users inside the container don't match up with those outside unless you do extra work to make them do so (even if the user/group names are the same the IDs will be different).

I don't want to manage more than 1 user / group, which is why the default is as it is. I'd already pointed out that if you set the `USERID` and `GROUPID` you can set the UID/GID for the smbuser/smb which should get you what you want.

**Comment by dkhokhlov** [comment]
"if you set the USERID and GROUPID you can set the UID/GID for the smbuser/smb which should get you what you want." - does not work. see use case, which is already based on what you described.

**Comment by dperson** [comment]
The `smbuser` and `smb` group only exist in the container. Outside the container their actual numeric user ID and group ID will refer to a different or non-existent user/group. The `USERID` and `GROUPID` let you make the IDs be whatever you want to match something outside the container.

It is well known by me that the container script only supports a single user owning all the files being shared, I wanted to make creating a simple share easy. If you want something complex I don't have the time or interest to create a script that tries to handle everything that samba can do. Just ignore the configuration provided by the script and build your own complex config and map it into the container, or make your own.

**Comment by stuckj** [comment]
I know you purposely didn't want to implement this functionality. But, if you do feel like merging it in I have it implemented in a fork and made a PR. There's not much to it. :)

**Comment by BobSammers** [comment]
I was bitten by this as well, although I fully understand dperson's reluctance to support an ever-expanding list of features.

I have found (through experimentation, not documentation, so use at your own risk!) that `smb.conf` can include multiple sections with the same name, which are merged when samba processes `smb.conf`.

This means that a mini `smb.conf` can be appended using `-I` or the `INCLUDE` env variable with a one or two-line body for each share that needs a different uid / gid. Something like this:

```
[share_name]
   force user = alternate_user
   force group = alternate_group
```
It's a bit hacky having a share defined across two locations, but it does the job and it's always possible to just define the shares entirely in the `INCLUDE` file and leave just the `[global]` section to be handled by the normal container set-up script.

**Comment by mariuszskon** [comment]
To others stumbling across this, I found this solution by @DrDOIS from [here](https://github.com/dperson/samba/issues/334#issuecomment-706720780). It seems to work correctly to reset the forcing of user and group, such that you do not need a separate hack for each share or each user.

```
-g "force user =" -g "force group ="
```

Also works with the `GLOBALS` environmental variable.
