### ISSUE TITLE
cannot add users in Dockerfile when deriving from dperson/samba

### ISSUE THREAD

**Issue by macmeck** [dperson/samba#255]
I am implementing a derived version of this image using `FROM dperson/samba:latest`. Within the `Dockerfile` I have a `RUN adduser ...` command.

The `adduser` command is successful and the user is being created in the temporary container. But the next `RUN` command does not see this user any more. 

I guess this is due to the fact that `/etc` is defined as a `VOLUME` within your `Dockerfile`.

Could you confirm this behaviour? Is there any workaround? Why is `/etc` defined as a `VOLUME` at all?

**Comment by dperson** [comment]
I run the `adduser` command within the container and it doesn't loose the user so I can't confirm that behavior.

The reason it's a separate volume is that I like my containers to be able to run read-only, but this container needs to be able to manage users, groups, and the samba configuration.
