### ISSUE TITLE
container unhealthy and not working anymore

### ISSUE THREAD

**Issue by Adrianos712** [dperson/samba#258]
Since last update (5hours ago) container is unhealthy:
`fe6c845c80a0        dperson/samba                     "/sbin/tini -- /usr/…"   13 minutes ago      Up 13 minutes (unhealthy)   0.0.0.0:139->139/tcp, 0.0.0.0:137-138->137-138/udp, 0.0.0.0:445->445/tcp           samba`

I tryed to run healthcheck manually:
```sh
# docker exec -it samba smbclient -L '\\localhost' -U '%' -m SMB3
protocol negotiation failed: NT_STATUS_CONNECTION_DISCONNECTED
```

Here is the way I launch it
```sh
docker run -d \
  -it \
  -p 137:137/udp \
  -p 138:138/udp \
  -p 139:139 \
  -p 445:445 \
  -e USERID=33 \
  -e GROUPID=33 \
  -v /mnt/nas/download:/mount/download:rw \
  --restart=always \
  --name=samba \
  dperson/samba \
  -n \
  -w WORKGROUP \
  -u "kodi;pass" \
  -s "Download;/mount/download;yes;no;no;kodi" \
```

**Comment by ieno** [comment]
Same issue here.

As a workaround I updated /etc/samba/smb.conf to undo the protocol changes from https://github.com/dperson/samba/commit/4183cdca1497c56806333a56470715dbf733057c and after a docker restart the healthcheck succeeds again.

**Comment by rumd3x** [comment]
Same here.

**Comment by mbreedlove** [comment]
@ieno Can you post your changes /etc/samba/smb.conf? 

Looking at mine, I don't see *some* of the changes from https://github.com/dperson/samba/commit/4183cdca1497c56806333a56470715dbf733057c. For example, the following lines are missing from my `/etc/samba/smb.conf`.

```
    echo '   server max protocol = default' >>$file && \
    echo '   client min protocol = SMB2_10' >>$file && \
    echo '   server min protocol = SMB2_10' >>$file && \
```
However, I do see these lines in `/etc/samba/smb.conf`:

```
    echo '   fruit:metadata = stream' >>$file && \
    echo '   fruit:model = MacSamba' >>$file && \
    echo '   fruit:posix_rename = yes' >>$file && \
    echo '   fruit:veto_appledouble = no' >>$file && \
    echo '   fruit:wipe_intentionally_left_blank_rfork = yes' >>$file && \
    echo '   fruit:delete_empty_adfiles = yes' >>$file && \
```

I'm wondering why only some of the Dockerfile changes in https://github.com/dperson/samba/commit/4183cdca1497c56806333a56470715dbf733057c applied, while others did not.

**Comment by ergoz** [comment]
same here :( not works

**Comment by JohnShortland** [comment]
Setting server max protocol = SMB3 in /etc/samba/smb.conf works for me also.

**Comment by dko-slapdash** [comment]
Same, stopped working on MacOS today:

```
# mount_smbfs -o soft //user:@localhost/some /tmp/some
mount_smbfs: server connection failed: RPC struct is bad
```

And there are no older versions available on https://hub.docker.com/r/dperson/samba/tags, just the latest.

To the author of the package:
1. Maybe we could have an environment variable to configure this protocol parameter?
2. Is there some way I can refer some older version (what hash to use?) of the image? We don't need the very recent version of the package anyway (it's used in our dev environment), we just need it to be stable.

**Comment by dperson** [comment]
Sorry about the SNAFU, somehow it made it through my test okay. I've merged the fix @rumd3x submitted.

**Comment by Adrianos712** [comment]
Thanks for the quick correction !
