### ISSUE TITLE
issue with -s and "all" keyword for 'valid users'

### ISSUE THREAD

**Issue by gdallaire** [dperson/samba#261]
example:

-s "share;/mnt;yes;no;no;zally"

"zally" won't be added as a valid user since it contains "all"

from /usr/bin/samba.sh:

`[[ ${users:-""} && ! ${users:-""} =~ all ]] && echo "   valid users = $(tr ',' ' ' <<< $users)" >>$file`

`[[ zally =~ all ]] --> true`  **incorrect**

`[[ zally = all ]] --> false`  **correct**

**=~** should be replaced by **=**  ?

**Comment by dperson** [comment]
Thanks!
