### ISSUE TITLE
Ability to set the servername? (netbios name)

### ISSUE THREAD

**Issue by gsdevme** [dperson/samba#262]
Hi,

Im struggling to see how I can set the name of the server? is that something that is supported? Rather than `CA8AFE51AA8D` Id like to have something set. 

![Screenshot 2019-12-15 at 18 47 51](https://user-images.githubusercontent.com/319498/70867271-992c4b00-1f6b-11ea-8348-3056801ed184.png)

**Comment by gsdevme** [comment]
Just thought this is the hostname of the container, I wonder if its worth adding a `HOSTNAME` environment variable so this can be set.

**Comment by gsdevme** [comment]
Looks like the default for samba is to use the hostname but using `netbios name = XX` would change it. I can look to make a PR for this.

**Comment by gsdevme** [comment]
The reason its causing me bother is the Nvidia shield uses this to mount locally, so every container recreate changes the path 

![image](https://user-images.githubusercontent.com/319498/70868141-7c951080-1f75-11ea-89c1-85c4101b35db.png)

**Comment by dperson** [comment]
The `-g` or `GLOBAL` environment variable will already let you set arbitrary options in the global section of the samba configuration.

**Comment by initstring** [comment]
> The reason its causing me bother is the Nvidia shield uses this to mount locally, so every container recreate changes the path
> 
> ![image](https://user-images.githubusercontent.com/319498/70868141-7c951080-1f75-11ea-89c1-85c4101b35db.png)

@gsdevme - how did you get this working with the Shield? I'm struggling to get the network name discovery functioning, which I believe is required. Thanks!
