### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by numberformat** [dperson/samba#265]
The following is not working for me. under Debian 10 (server). Windows 10 Professional (client).

sudo docker run -it --name samba -p 139:139 -p 445:445 -v /home2:/home2 dperson/samba -p \
-u 'test;bogusPassword' \
-s "home2;/home2;no;no;no;test"

**Comment by bd8392** [comment]
i too have problems with linux permissions....(runnign in docker-compose)

**Comment by Shenanigans77** [comment]
I'm also having this issue.

**Comment by estimadarocha** [comment]
any news on this?

**Comment by estimadarocha** [comment]
i tought to test the new fix's but ain't resolved yet

**Comment by estimadarocha** [comment]
smbuser:x:1000:1000:Samba User:/tmp:/sbin/nologin
teste:x:1001:1001:Linux User,,,:/home/teste:/bin/ash

is it supposed to be like that?

**Comment by rikki78** [comment]
I think I have the same issue. I run the container with ```docker run -it --name samba --restart always --net=host -p 139:139 -p 455:455 -p 137:137/udp -p 138:138/udp -v /home/pi/IOTstack/volumes:/v_shared -d dperson/samba:armhf -p -s "share;/v_shared" -n -u "user;pass"```
but when I open the share, it never asks me for a username or password. I can't write anything to the share either.

**Comment by dperson** [comment]
Shares by default are read-only... is that the issue that you're seeing or is it denying access entirely?

**Comment by estimadarocha** [comment]
asking me or @rikki78?

**Comment by rikki78** [comment]
No I can see it, just can't write a file on it.
How can I make it writable?

**Comment by dperson** [comment]
In the [README.md](https://github.com/dperson/samba#configuration), check the section about `-s` creating shares. It's one of the optional arguments that you can provide.
