### ISSUE TITLE
Active Directory 

### ISSUE THREAD

**Issue by gprossliner** [dperson/samba#269]
Hi!

For testing purposes, I want to use a Samba instance to simulate a Microsoft Active Directory. I will use LDAP to authenticate to the instance.

Is this image capable to run a Active Directory, like outlined in [Setting up Samba as an Active Directory Domain Controller](https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller)?

I created an interactive container from you Image, and tried to follow the instructions, but there is no samba-tool command found.

Thank you

**Comment by dperson** [comment]
You could add it from the software repo. This container was created to make creating simple shares easy, Samba is too complex to try and support all possible use cases. You're welcome to modify it for your uses however.
