### ISSUE TITLE
Performance not great

### ISSUE THREAD

**Issue by erikpb** [dperson/samba#27]
Very nice image!
However, I seem to have an issue with read/write performance. I'm using OSX to connect. Any advice on how to improve the performance?

**Comment by dreamcat4** [comment]
I have seen sure problems on OS X too. Like it takes time to connect or list the files. Sorry I am not sure whats the solution.

**Comment by dperson** [comment]
Glad you like the image. I haven't really tested it from OSX. But I'll put it on my todo list.

It might be a little while before I get to it though, I'm in the middle of moving...

**Comment by erikpb** [comment]
I've been experimenting with the image and adding:

socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=65536 SO_SNDBUF=65536

to the global config in smb.conf seems to make a big difference.

**Comment by dperson** [comment]
I added the 'socket options = TCP_NODELAY' to the default smb.conf now.

Setting the TOS (type of service) to lowdelay can limit the available bandwidth allocated. The docs say that any updates to SO_RCVBUF and SO_SNDBUF should be tested on a per environment basis... which isn't practical for me to do =).

Please let me know if it resolves the performance issue you were seeing.

**Comment by erikpb** [comment]
Thanks! I did another change in my fork that allows for specifying the ID of the users created. This is quite helpful when you want to match user ID's with the host.

**Comment by dperson** [comment]
Another good suggestion! Thanks, I added that too.
