### ISSUE TITLE
Slow speeds when in Link Aggregation

### ISSUE THREAD

**Issue by huhugiter** [dperson/samba#272]
Hello!

I'm having an issue when use samba in Link Aggregation, both write and read speed down to 1/2.
I'm use two 1GB LAN cables to route AC88U. and enable Bonding/ Link aggregation in AC88U. However the speed down to 500Mbps/s, but when not in LAG, the speed resumed to 1000Mbps/s.

```txt
       1000Mbps          2000Mbps(theoretically)
PC----------------route==========================Server
note: one line one cable
```

I have no ideal why this happend. when in LAG. win10 task manager show `System process` occupied half bandwidth(500Mbps/s) and `windows resource manager process` occupied last 500Mbps/s, so actually client received 1000Mbps/s but the 500Mbps of `System` wasted. On the other hand. When not in LAG, only `windows resource manager process` occupied whole 1000Mbps/s.

Any ideal? thanks.

**Comment by dperson** [comment]
Sorry I have no idea what's happening on your ASUS router, it sounds like a networking issue, if it's a samba issue that's a bit past what I support directly too, I'm just trying to make setting up a simple share easy.
