### ISSUE TITLE
Exec privilege

### ISSUE THREAD

**Issue by DaveBRH** [dperson/samba#274]
As the configuration is now. All files get the exec privilege. Is it possible to make this easily configurable with an option. For most files no execute privlege is necessary. Having this disabled makes it easier. In that case exec privilege only has to be set on the few files that need it.

Alternatively, but I don't know if that is possible, would be the ability to run a script/program on save to determine the privileges.

**Comment by dperson** [comment]
Windows and hence SMB doesn't really understand execute privilege. I'm not aware of any good automatic options in Samba.
