### ISSUE TITLE
USERX variables are not working properly

### ISSUE THREAD

**Issue by janwo** [dperson/samba#275]
Dear maintainers,

unfortunately I am unable to get three users installed. It says `/usr/bin/samba.sh: line 140: $2: unbound variable`. 

I had to modify the Dockerfile in order to inject the variables when the container is running as my framework does not support variables in docker-compose or in .env files.

Therefore I have the following files:
- Dockerfile
- pre-samba.sh
- docker-compose.yml

```
# Dockerfile
FROM dperson/samba:armhf
COPY ./pre-samba.sh /usr/bin/pre-samba.sh
RUN chmod +x /usr/bin/pre-samba.sh
ENTRYPOINT ["/usr/bin/pre-samba.sh"]
```
```
#!/bin/sh
# pre-samba.sh
export USER1="influxdb;${AUTH_SAMBA_PASSWORD}"
export USER2="openhab;${AUTH_SAMBA_PASSWORD};9001;openhab;9001"
export USER3="grafana;${AUTH_SAMBA_PASSWORD};472;grafana;472"
echo $USER1 #influxdb;badpass123
echo $USER2 #openhab;badpass123;9001;openhab;9001
echo $USER3 #grafana;badpass123;472;grafana;472`
exec /usr/bin/samba.sh "$@"
```
```
# docker-compose.yml
version: '2'
volumes:
  openhab-conf:
  openhab-userdata:
  influxdb:
  grafana:

services:
  samba:
    build: ./samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - openhab-conf:/mount/openhab/conf
      - openhab-userdata:/mount/openhab/userdata
      - grafana:/mount/grafana
      - influxdb:/mount/influxdb
    restart: unless-stopped
    environment:
      AUTH_SAMBA_PASSWORD: badpass123
      SHARE1: vol1;/mount/openhab;yes;no;no;openhab
      SHARE2: vol2;/mount/grafana;yes;no;no;grafana
      SHARE3: vol3;/mount/influxdb;yes;no;no;influxdb
```

It all works fine, the only thing which does not work is to inject the users. I also tried with command as mentioned in other comments. I get the same error. It is working when I only inject the standard user, but thats not what I am looking for.
```
#!/bin/sh
# pre-samba.sh: this works!
export USER="influxdb;${AUTH_SAMBA_PASSWORD}"
echo $USER #influxdb;badpass123
exec /usr/bin/samba.sh "$@"
```

**Comment by mrowek** [comment]
same issue here, I could add one user, anothers are giving this error

**Comment by dperson** [comment]
I've tested this: `sudo docker run --rm -it -e USER1='bob;bob' -e USER2='bobo;bobo' dperson/samba bash' both users are created exactly as they should be.

Your outer system environment variables have any bearing on the environment inside the container, that's kind of the point it's a separate environment.
