### ISSUE TITLE
Raspbian on RPI 4 - standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by djonk** [dperson/samba#277]
Hi,

Thanks so much for maintaining this image. Just tried to run using the documented commands on a freshly installed Raspberry PI 4 with Raspbian 10 (Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l). 

Starting returns the error: standard_init_linux.go:211: exec user process caused "exec format error"

Thanks,
Djon

**Comment by Shenanigans77** [comment]
@djonk I just ran into this problem. You need to get the armhf version of this container.

`sudo docker run -it --name samba -p 139:139 -p 445:445 \
            -v /path/to/directory:/mount \
            -d dperson/samba:armhf -p`

**Comment by djonk** [comment]
Thanks @Shenanigans77! Did the trick.
