### ISSUE TITLE
Host user groups not taken into consideration

### ISSUE THREAD

**Issue by vendetta1987** [dperson/samba#278]
Hi,
I'm trying to share a folder not owned by my main host user, he's just part of the same group that owns the folder. The share works as far as read access is concerned but I can't write to it. Writing works for the other shares, which are owned by my main user.
The following is the command starting the container as part of a systemd service unit:

> docker run --name=%n \
        -e "USERID=1000" \
        -e "GROUPID=1000" \
        -p 139:139 \
        -p 445:445 \
        -v /home/pi:/opt/pi_user \
        -v /opt/openhab/conf:/opt/openhab_conf \
        -v /media/usb_hdd:/media/usb_hdd \
        dperson/samba:armhf \
        -s "pi;/opt/pi_user;yes;no;yes" \
        -s "openhab;/opt/openhab_conf;yes;no;yes" \
        -s "usb_hdd;/media/usb_hdd;yes;no;yes" \
        -u "samba;samba;1001;samba;1001" \
        -p

My host is a raspberrypi and the clients are Windows 10 machines. The readonly share is the one containing my openhab configuration files. The host folder is owned by the user/group "openhab" and my main user is part of the "openhab" group.
When connecting to the container and looking at the mounted folders the problematic folder isn't assigned the correct user/groupid of the samba user:

> drwxrwxr-x   13 999      994           4096 Feb 12 16:30 openhab_conf
drwxrwxr-x    8 smbuser  smb           4096 Feb 12 16:36 pi_user

As you can probaply guess, 999 and 994 represent user and group "openhab" on the host. These are the mounted host folders:

> drwxrwxr-x 13 openhab openhab 4096 Feb 12 17:30 /opt/openhab/conf
drwxrwxr-x  8 pi   pi   4096 Feb 12 17:36 /home/pi

Is it possible to share the folder writeable this way or do I have to provide write privileges to everyone as a workaround?

**Comment by dperson** [comment]
I'm really not sure exactly what you're trying to accomplish and where it's going wrong for you...
