### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by pniedzwiedzinski** [dperson/samba#280]
Hi, I would like to use this image on ARM architecture (raspberry pi). I made this script which builds the image on github actions and uses docker buildx. I think this would be helpful in this project.

https://github.com/zsk-poznan/zastepstwa/blob/master/.github/workflows/docker-deploy.yml

**Comment by ipeacocks** [comment]
There already is one `dperson/samba:armhf`.

**Comment by pniedzwiedzinski** [comment]
Okay, I missed it
