### ISSUE TITLE
Simple version

### ISSUE THREAD

**Issue by ldrrp** [dperson/samba#281]
Can you fork and make a simpler version that just mounts the smb config file instead of all these messy parameters and variables. It would be nice to carry over existing configs

**Comment by dperson** [comment]
Those are all optional. You can just provide your own `smb.conf` as it stands.

**Comment by ldrrp** [comment]
Can you document that process for the noobs

**Comment by dperson** [comment]
You just mount in a volume with the configuration files to `/etc/smb` or `/etc/samba` whatever the path is (not at my system right now). If you don't set any of the command line arguments to the container (the part after `dperson/samba`) it won't try to configure anything.
