### ISSUE TITLE
Update docker-compose.yml

### ISSUE THREAD

**Issue by BKoster98** [dperson/samba#284]
A suggestion based on issue #231.  Add -p flag to the end of line 24 in docker-compose.yml in order to access shares.

Old:
>     command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd"'

Updated:
>     command: '-s "Mount;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd" -p'

**Comment by dperson** [comment]
Done. Good suggestion.
