### ISSUE TITLE
Windows10 need login

### ISSUE THREAD

**Issue by amColinzzz** [dperson/samba#285]
When I use -u arg add users,on windows10 sys ,even a guest share ,also need input account and passwd,but on android sys can direct access.
If i del all -u arg,windows10 can direct access.
so,how can fix this problem ?

**Comment by mattthhdp** [comment]
You cannot fix that, they remove support for smbv1 (as it's unsecure and easily hacked)
if guest is enable you can enter what ever credential you want and it will work
p.s: it's possible to activate smbv1 but really not recommended.

**Comment by dperson** [comment]
Correct.
