### ISSUE TITLE
Permissions again

### ISSUE THREAD

**Issue by estimadarocha** [dperson/samba#291]
So i decided to open this cause i really don't know what to do more!

this is my docker-compose.yml

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/Lisbon'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /gmedia/movies-kids:/mnt2:z
    command: '-s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd" -p'

i can see share, but can't create or edit nothing on it.

any help will be appreciated! thanks

**Comment by dperson** [comment]
I believe that it's the `'` (single quotes) around the `command:` content. It can be rather fussy. Looking at the `docker logs <container_name>` could confirm / provide a better idea what's going wrong.

**Comment by estimadarocha** [comment]
logs:

Added user bob.
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections

tested without quotes and no lucky!

**Comment by estimadarocha** [comment]
![image](https://user-images.githubusercontent.com/17991728/77541898-454fcd00-6e9d-11ea-9c4e-26ee2428ce6f.png)

it looks correct even with single quotes!

**Comment by estimadarocha** [comment]
if i do to container console and make:

su bob

i can edit the files inside share

dunno if that helps you somehow
