### ISSUE TITLE
Question about shares

### ISSUE THREAD

**Issue by itobi1** [dperson/samba#292]
Hello,

at the moment I am mounting my shares in windows as follows:
-  \ \server\share1
-  \ \server\share2

But I actually don't want to mounte the shares seperately.
I just want to mount \ \server and see all my shares.
Sadly that doesn't work.

Do you have a fix for my problem?

Best regards,
itobi1

**Comment by dperson** [comment]
I think that's more of a windows thing, you can't mount the server and have to mount the shares...
