### ISSUE TITLE
Another permissions issue? Help with settings 

### ISSUE THREAD

**Issue by vazquezjm** [dperson/samba#296]
Hi All. 

Please, I need help letting my users in Windows access a shared directory. 

```
sudo docker run -it --name samba --restart always --net=host \
  -p 139:139 -p 455:455 -p 137:137/udp -p 138:138/udp \
  -v /media/external:/v_media \
  -d dperson/samba \
  -s "external;/v_media" \
```

By doing that, I can only access for reading. I want to RW.

TIA

**Comment by dperson** [comment]
Shares default to read only, you have to specify that writing is allowed, see the [README.md](https://github.com/dperson/samba#configuration) for shares.
