### ISSUE TITLE
Does not work with Docker For Windows after upgrade to version 2.2.0

### ISSUE THREAD

**Issue by KarlNeosem** [dperson/samba#299]
Docker on Windows 10.
I was using dperson/samba to share docker volumes between host and containers. I mapped the samba shares using 10.0.75.xxx ip address. When I upgraded and dockerNat went away I lost the ability to do this.

I cannot forward the ports when running the, docker run -d -it -p 139:139 -p 4445:445........, it seems windows is already using port 445. If I try something like docker run -d -it -p 139:139 -p 4445:445..... the container runs but I can't get the drive mapped in windows. It appears that windows requires samba to be at port 445.
This is where I got the idea of using samba to share files.
https://www.guidodiepen.nl/2017/03/alternative-way-to-share-persistent-data-between-windows-host-and-containers/

**Comment by dperson** [comment]
I don't have a windows system, nor is docker for windows dropping features (if that's what you meant with dockerNat) something that seems like an issue I want to try to figure out.
