### ISSUE TITLE
wide link dos not work properly

### ISSUE THREAD

**Issue by amsaravi** [dperson/samba#301]
Thanks for your very nice and handy docker that makes samba config a lot easier. one minor problem that i have with this docker is that after using the -W and properly assignment of ownership and access to folders, i can not use symlinks.
perhaps you should place `widelinks=yes `for each user. i did so, but i don't know how to restart samba within this kinds of minimal containers.

**Comment by dperson** [comment]
It's a global setting, it should apply to all users / shares.

To restart samba, you restart the container with docker.
