### ISSUE TITLE
Samba write operation can’t be completed because it isn’t supported

### ISSUE THREAD

**Issue by agusgambina** [dperson/samba#304]
I am not sure if this is an issue, can be the case that it is the expected behaviour

I have a server with `Ubuntu 18.10`. It has `docker` and `docker-compose` installed. I have this `docker-compose` recipe to run samba
```
	version: "3.7"

	services:

	  samba:
	    image: dperson/samba
	    container_name: samba
	    restart: always
	    network_mode: host
	    environment:
	      TZ: 'America/Argentina/Buenos_Aires'
	      WORKGROUP: "WORKGROUP"
	      NMBD: "true"
	      USERID: "1001"
	      GROUPID: "1001"
	    command: '-u "$SAMBA_USER;$SAMBA_PASSWORD" -s "media;/media;yes;no;no;myuser;myuser;myuser;myuser"'
	    stdin_open: true
	    tty: true
	    ports:
	      - 139:139
	      - 445:445
	    volumes:
	      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
	      - $SAMBA_MEDIA:/media
```
I also have a mac, and I am able to connect to the server with `finder`, see the files and open them. But when I try to copy or delete a file I get this message
```
	The operation can’t be completed because it isn’t supported.
```

**Comment by dperson** [comment]
It looks like a permissions issue, try adding `-p` (set permissions) to the `command:`.
