### ISSUE TITLE
How to properly use dperson/samba

### ISSUE THREAD

**Issue by proclia** [dperson/samba#305]
I am trying to use dperson/samba, created a `DockerFile` like below with my folders added into it 

```
FROM dperson/samba
RUN mkdir -p /home/newstack/stacks \
             /home/newstack/stacks/wea \
             /home/newstack/stacks/cas \
             /home/newstack/stacks/cada
WORKDIR /home/newstack


ADD /files/cada /home/newstack/stacks/wea
ADD /files/wea /home/newstack/stacks/cada
ADD /files/*.tar /home/newstack/stacks/

EXPOSE 139
ENTRYPOINT [ "samba.sh","-s newstackshare;/home/newstack/stacks/","-p" ]
```
When i try to access `\\ip\newstackshare\`, i am getting `network path was not found` in `windows`
I am not sure what am i missing here, i wanted to add my folders into this image and wanted to share it, is that approach wrong? Any help on this would be appreciated.

  [1]: https://github.com/dperson/samba

**Comment by noohi** [comment]
Hi,

I'm using docker-compose, but it might help.
This is my working example, differences from the first glance are the port used (445 in my case), and have a user/pass defined on the share.
Mapping a directory to the host (home/USER), then sharing that, so that the files are not "stuck" in the container.

`services:
  samba:
    container_name: samba
    image: dperson/samba
    volumes:
      - /home/USER:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 445:445
    #restart: always
    command: '-u "username;password" -s "home;/home;yes;no;no;username;username;username;username" -p'`

**Comment by proclia** [comment]
how do i map the `volume`

**Comment by proclia** [comment]
For some reason i am not getting this working, is my understanding right? i.e the dperson/samba docker image will have the files and folders and it can be shared to other containers

**Comment by dperson** [comment]
Can you share how you're starting the container, and the log messages that it outputs? Without those it's near impossible to figure out what might be wrong.

**Comment by proclia** [comment]
my question has the `Dockerfile` 
`ENTRYPOINT [ "samba.sh","-s newstackshare;/home/newstack/stacks/","-p" ]`

**Comment by dperson** [comment]
Okay how you started it was in your `Dockerfile`, sorry. But without the error messages that you're getting I still don't know what's going wrong.
