### ISSUE TITLE
cannot write to a mount

### ISSUE THREAD

**Issue by kapoorsunny** [dperson/samba#306]
Hi,

i am not able to write any file to folder using below command 

sudo docker run -it --name samba -p 139:139 -p 445:445 -d -v /media/usb/share:/mount dperson/samba -p \
            -u "user1;password" \
            -s "sharedrive;/mount;yes;no;yes;user1"

**Comment by kapoorsunny** [comment]
and if i do below then i am not able to access the share 

sudo docker run -it --name samba -p 139:139 -p 445:445 -d -v /media/usb/share:/mount dperson/samba -p 
-u "user1;password" 
-s "sharedrive;/mount;no;no;no;user1"

**Comment by dperson** [comment]
What does `sudo docker logs samba` show?
