### ISSUE TITLE
Cannot see files (only directories)

### ISSUE THREAD

**Issue by iammenotyou** [dperson/samba#307]
Running the following:

```
sudo docker run -it --name samba -p 139:139 -p 445:445 -d -v /srv/device/directory1:/mount/dir1 -v /srv/device/directory2:/mount/dir2 dperson/samba -p
-u "user1;password"
-s "dir1;/mount/dir1;no;no;no;user1"
-s "dir2;/mount/dir2;no;no;no;user1"
-s "dir3;/mount;no;no;no;user1"
```

The host is a debian guest is windows.  Connecting to \\ip\dir3 shows me dir1 and dir2 and when I enter either directory they are blank.   If i go to \\ip\dir1 or \\ip\dir2 then it asks for password and says \\ip\dir1 is not accessable.  You might not have permissions to use this network.

**Comment by dperson** [comment]
What does `sudo docker logs samba` show?

**Comment by iammenotyou** [comment]
Unfortunately it doesn't show much.  

smbd version 4.11.5 started.
```
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections

```

**Comment by iammenotyou** [comment]
I made a slight change.
`sudo docker run -it --name samba -p 139:139 -p 445:445 -d -v /srv/device/directory1:/mount/dir1 -v /srv/device/directory2:/mount/dir2 /srv/device:/mount/device dperson/samba -p`

So adding the directory (1 up from the two I'm trying to share).
Log still shows no extra information.  but I do get the following when connecting.

\\ip\ shows up and I can see files.
\\ip\dir2 still no go

Update 2: after 1 hour (approximately), now \\ip\device and \\ip\dir2 are now both showing files
I should note no changes were done during this time.

**Comment by dperson** [comment]
I'm not really sure how/if the nested shares work, I've never really tried to do that (`/mount`, `/mount/dir1`, and `/mount/dir2`). What happens if you just share `/mount` or `dir1` and `dir2`?
