### ISSUE TITLE
Samba reports the storage capacity of the boot drive instead of the bound external HDD

### ISSUE THREAD

**Issue by djcopley** [dperson/samba#308]
I have bound a directory on an external HDD to be my storage point; however, the Samba server only reports the capacity of the OS boot drive, not the external HDD. As a result, my backup agent always fails because it thinks there is not enough room. Is there a fix for this?

**Comment by dperson** [comment]
Please include:
1. how you're starting samba (`docker run` command, compose `yml` file, etc.)
1. the output that you get from `sudo docker logs <samba_container_name>`

**Comment by djcopley** [comment]
Docker command: 
```docker run --name samba -p 137:137/udp -p 138:138/udp -p 139:139/tcp -p 445:445/tcp --network homecluster_net -e TZ="America/Arizona" --restart unless-stopped dperson/samba -p -s "backups;/backups" -s "backups;/backups;yes;no;no;djcopley" -u "djcopley;password"```

Docker logs: 
```ubuntu@pi0:~$ docker logs samba
Added user djcopley.
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections```

**Comment by dperson** [comment]
2 things:
1. nowhere on the `docker run` do you pass in the USB drive as a volume to be located at `/backups`, which is why it's not being seen.
1. you're defining the `backups` share (`-s`) twice... I'm not sure that I tested that, it may work or may do something weird... I'm not sure.

**Comment by eb** [comment]
I have the very same issue. The boot partition is very small and has only 12GB left which shouldn't matter, since I use bind mounts to much larger partitions. But it still won't allow me to copy a file that's bigger than the space left on the boot partition. It yields an error "There's not enough space...".

Here's the docker-compose.yml:

```  samba:
    container_name: samba
    image: dperson/samba
    restart: always
    network_mode: host
    hostname: myhost
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /srv/data/user1_data:/mount/user1/data
      - /srv/data/user2_data:/mount/user2/data
      - /srv/data/shared_data:/mount/user1/shared
      - /srv/data/shared_data:/mount/user2/shared
    environment:
      - USERID=0
      - GROUPID=0
      - WORKGROUP=WORKGROUP
      - PERMISSIONS=1
      - RECYCLE=1
      - NMBD=1
      - USER=user1;user1pass
      - USER2=user2;user2pass
      - SHARE=user1;/mount/user1;yes;no;no;user1
      - SHARE2=user2;/mount/user2;yes;no;no;user2
```

Does copied data first land in some other (temporary) directory maybe? I tried monitoring the copy process with 'du / -h -d 1', but couldn't see anything strange.

**Comment by dperson** [comment]
Neither home directory `/mount/user1` or `/mount/user2` is a volume, I'd recommend making the `volumes:` section as follows (making the home directories and moving the data directories into them):
```
      - /srv/data:/mount
      - /srv/data/shared_data:/mount/user1/shared
      - /srv/data/shared_data:/mount/user2/shared
```
