### ISSUE TITLE
cannot write

### ISSUE THREAD

**Issue by iot49** [dperson/samba#309]
I run the samba docker on linux, mount on a mac. Reading works fine, but I cannot write to the mount from the mac.

I have tried the -p option, but this changes all my file ownerships and groups, then I cannot even create files on the host anymore.

Command:
```
docker run -it --name samba -p 139:139 -p 445:445 -d \
    -v /home/${USER}:/mount \
    dperson/samba \
    -u "${USER};samba_share" \
    -s "home;/mount;yes;no;no"
```

Logs:
```
Added user boser.
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
```

I've also tried specifying the UID, without success:
`-u "${USER};samba_share;`id -u ${USER}`;${USER};`id -g ${USER}`"`
(formatting removed the backtics of the `id` commands).

This line evaluates to 
`boser;samba_share;1000;boser;1000` on linux, and
`boser;samba_share;501;boser;20` on the mac.

**Comment by dperson** [comment]
The UID/GID of created users in the container is ignored for reading/writing files. if you don't want to use `-p` you want to check the `USERID` and `GROUPID` from the [README.md](https://github.com/dperson/samba#configuration).

**Comment by iot49** [comment]
Thanks for the link to the readme. Unfortunately I still cannot get write access working to the shared volume. If this is indeed possible, I am sure an example would be appreciated not just by me, but also others (cf issue 312, Get write access without using option -p).

For reference, my docker command is

```
docker run -it --name samba -p 139:139 -p 445:445 -d \
    -v /home/${USER}:/mount \
    dperson/samba \
    -s "home;/mount;yes;no;no;all;none;${USER};home on docker vm" \
    -u "${USER};samba_share;`id -u ${USER}`;;`id -g ${USER}`"
```

Reading works fine, but writing is blocked and I am not sure how to diagnose the issue, nor even if it's possible.

**Comment by dperson** [comment]
It's just setting standard docker environment variables:
```
docker run -it --name samba -p 139:139 -p 445:445 -d \
    -e "USERID=$(id -u ${USER})" \
    -e "GROUPID=$(id -g ${USER})" \
    -v /home/${USER}:/mount \
    dperson/samba \
    -s "home;/mount;yes;no;no;all;none;${USER};home on docker vm" \
    -u "${USER};samba_share"
```

**Comment by iot49** [comment]
Terrific, this work!

I wonder when one would use the -p flag. (But I won't).

**Comment by dperson** [comment]
It's a simple way to setup a share. If you just want a location to have files be available (not use them on the server as well). There's not a simple and good way of synchronizing users/IDs/passwd from the host server and container and especially samba running inside of it (which uses an entirely different hashing function for the passwords).
