### ISSUE TITLE
-u, -p, and -n commands

### ISSUE THREAD

**Issue by htko89** [dperson/samba#31]
I have a few questions and I'm not sure if this is the right place to ask. Here it is:

For -u argument: Where does [ID] go? is it `-u "<username;password>[;ID]"` ? Is this the linux User UID and what is it used for?

For -p argument: Admittedly a more samba-related question. On container start, samba.sh sets these permissions on the mounted volumes' files and directories.
`chown = smbuser, files = 664, directories = 775`
which corresponds to this on the host:
`drwxrwxr-x 2 999 docker 4096 Oct 19 16:44 Directory1`
However, this only applies to when the container is set up. When I create directories from another computer accessing the share, file permissions show on the host as: 
`drwxrwxr-x 2 999 users  4096 Oct 19 16:51 Directory2`
Is there any way to set it so it is consistent or user settable so to maintain compatibility with other host and docker applications?

For -n argument: I am also unavailable to find my host on "network places" in windows. I can access my share through \\ip_address\ 

Excuse me if it is a lack of understanding in my part. I am still new to docker! Thank you for your time reading all of this. If anyone can help I will greatly appreciate it.

**Comment by dperson** [comment]
@htko89,

The `<>` and `[]` are just to denote what kind of variable value that field is. For `<>` it is a required variable, where as `[]` are optional. The actual `<>[]` aren't part of what you would provide. IE use `-u "bob;badpassword"` or `-u "bob;badpassword;1024"`

As for `-p` it was meant to make it easy to set permissions on preexisting files / directories that you wanted to share into the container via the `-v` option to docker. The `smb.conf` already has settings to force permissions and user on files / directories created through samba.

For `-n` which starts `nmbd` to talk to the rest of your network (and provide netbios naming), you also have to set the `-p 137:137/udp -p 138:138/udp` options for docker. I just updated the `README.md` a bit to try and clarify it a bit more.

Hope this helps.

**Comment by htko89** [comment]
I just put the network to host to fix nmbd not working. (docker-compose yml looks like `network_mode: "host"`

It did complain at one point that it couldn't find a valid hostname, which one could pass as `hostname: foo` in docker compose but I haven't tried it yet.
