### ISSUE TITLE
netbios daemon not working correctly

### ISSUE THREAD

**Issue by aovestdipaperino** [dperson/samba#313]
I've aliased a bunch of IP on my same server, i.e. the server has multiple IPs associated.
I start each instance of samba and bind all the ports to that specific IP e.g.:

``` Up 5 seconds (health: starting)   192.168.2.5:139->139/tcp, 192.168.2.5:137-138->137-138/udp, 192.168.2.5:445->445/tcp   server```

While connecting to the server via IP works as expected, it seems that in this configuration the Netbios daemon doesn't broadcast properly (maybe due to NAT translation done by docker?).

This is how the container is launched for the first time:

```docker run -it -p 192.168.2.5:139:139 -p 192.168.2.5:445:445 -p 192.168.2.5:137:137/udp -p 192.168.2.5:138:138/udp --name server -v /Pool:/Pool -d dperson/samba -I /Pool/docker/samba/server.conf -i /Pool/docker/samba/samba_users -n```

Am I missing a bit of configuration or broadcasting is broken under default bridge network configuration?

**Comment by dperson** [comment]
I really should remove the option to even start it at this point. It's been disabled in Windows as a way of advertising server names. I've mainly left it in place for embedded systems that still use the legacy protocol.

Samba doesn't have built-in support for the new method (at least it didn't last I checked).

**Comment by aovestdipaperino** [comment]
> Samba doesn't have built-in support for the new method

To what are you referring here? Curious.
Also I found out that it works wonderfully even in `macvlan` mode so don't rush to remove this.

**Comment by dperson** [comment]
WS Discovery is the new "protocol" that MS uses for discovery. NMBD is part of SMB1 which is now disabled by default (and can't even be installed on the latest windows versions as I understand it).

**Comment by aovestdipaperino** [comment]
ah thank you.
I found this: https://github.com/christgau/wsdd
If you are interested I can put together a PR that uses this protocol instead of NB.

**Comment by dperson** [comment]
It won't work with NAT. That's the most common way the container is used.

**Comment by aovestdipaperino** [comment]
I ended up creating a [single binary image](https://hub.docker.com/repository/docker/aovestdipaperino/wsdd2) which - although requires `macvlan` or `host` networking - can be used to expose a samba server behind NAT which is not bad.
Thank you for all your help!

**Comment by mallory98e** [comment]
> WS Discovery is the new "protocol" that MS uses for discovery. NMBD is part of SMB1 which is now disabled by default (and can't even be installed on the latest windows versions as I understand it).

Dude I don't know what are you smoking but WINS is there even in the latest Windows 11.
Can be configured manually but it is usually given out by the DHCP on your LAN and yes it's in use in all windows versions, maybe they take advantage of that crap you mentioned earlier but it will surely fall back to wins as by default netbios node type defaults to 2 direct wins query.

I can verify that the --host mode works fine and it is the best for samba.

IF you use the default nat it will give back crap natted entries.

Once you switch make sure you delete the wins file with the broken entries like:

/var/lib/samba/wins.dat:"server#20" 1705917467 172.17.0.3 66R


You can always verify wins from any linux box on your lan with:

nmblookup -R -U <samba server ip> <name you wanna query>
