### ISSUE TITLE
Cannot get password protect share working

### ISSUE THREAD

**Issue by jonare77** [dperson/samba#314]
Im trying to get a password protected share working, but with no luck. What am I missing? 
Sorry if this is not a bug, but rather a question.

Compose config as follows.
`samba
    container_name: samba
    image: dperson/samba
    hostname: samba
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WORKGROUP="NORKNT"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    networks:
      - default
`

samba:
    container_name: samba
    image: dperson/samba
    hostname: samba
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WORKGROUP="NORKNT"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    networks:
      - default
``
    read_only: false
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - ${USERDIR}/docker/data/share1:/mnt/share
    command: >
      -u "samba;samba123" -s "Share1;/mnt/share;yes;no;no;samba"`

**Comment by MPeti1** [comment]
I see that you closed the issue, but did you find a solution to it?
If yes, what did you change?
