### ISSUE TITLE
All files/folder have chrony as owner and group

### ISSUE THREAD

**Issue by MGMehdi** [dperson/samba#332]
Hi

I run Alpine on my raspberry with a HDD as volume for Samba but all files and folder are owned by chrony when this container run and it block nextcloud or seedbox how are also in the HDD.

I don't understand why and how counter this

Can someone explain and help me ?

**Comment by MagicRB** [comment]
Linux stores user and group permissions not by name but by ID, the default UID is 100 and GID is 101, on my system 100 and 101 is nothing, but on your it is chrony, it just depends on what it maps to

**Comment by solipsist01** [comment]
don't use -p if you don't want the permissions and owner to be changed

**Comment by gucki** [comment]
I have the same problem and I'm not using the p flag. This my docker-compose.yml file:

    image: dperson/samba
    environment:
      - GLOBAL=log level = 3
      - USER=gucki;test;1000;gucki;1000
      - SHARE=gucki;/srv/gucki;yes;no;no;gucki;gucki
    volumes:
      - /home/gucki/Public:/srv/gucki
    ports:
      - 139:139
      - 445:445

I'd expect the files created on the share to get 1000:1000 and not 100:101. How can I fix it?

**Comment by solipsist01** [comment]
this part parses the variables
while getopts ":hc:G:g:i:nprs:Su:Ww:I:" opt; do
    case "$opt" in
        h) usage ;;
        c) charmap "$OPTARG" ;;
        G) eval generic $(sed 's/^/"/; s/$/"/; s/;/" "/g' <<< $OPTARG) ;;
        g) global "$OPTARG" ;;
        i) import "$OPTARG" ;;
        n) NMBD="true" ;;
        p) PERMISSIONS="true" ;;
        r) recycle ;;
        s) eval share $(sed 's/^/"/; s/$/"/; s/;/" "/g' <<< $OPTARG) ;;
        S) smb ;;
        u) eval user $(sed 's/^/"/; s/$/"/; s/;/" "/g' <<< $OPTARG) ;;
        w) workgroup "$OPTARG" ;;
        W) widelinks ;;
        I) include "$OPTARG" ;;
        "?") echo "Unknown option: -$OPTARG"; usage 1 ;;
        ":") echo "No argument value for option: -$OPTARG"; usage 2 ;;
    esac
done

you could try:

image: dperson/samba
environment:
  - GLOBAL=log level = 3
  - PERMISSIONS=false
  - USER=gucki;test;1000;gucki;1000
  - SHARE=gucki;/srv/gucki;yes;no;no;gucki;gucki
volumes:
  - /home/gucki/Public:/srv/gucki
ports:
  - 139:139
  - 445:445

**Comment by gucki** [comment]
Thanks, but it made it even worse then better. It changed *all* existing files to 100:101 too....

**Comment by MGMehdi** [comment]
I've found a solution, I set the USERID and GROUPID same value as me
