### ISSUE TITLE
Status restarting

### ISSUE THREAD

**Issue by luciodaou** [dperson/samba#348]
Build up the command as written on the main page. I need 2 shares from the hosting machine, one rw (exchange_box) and the other ro (log). All I get on `docker ps -a` is that the container is restarting on loop, even though I get no errors after `docker run`.
```
sudo docker run -it -e TZ=UTC --name samba --restart=always -p 139:139 -p 445:445 -d dperson/samba -p \
            -v /share/exchange_box:/home/pi/exchange_box \
            -v /share/log:/home/pi/log \
            -u "smb;123" \
            -s "exchange_box;/share/exchange_box;yes;no;no;smb" \
            -s "log;/share/log;yes;yes;no;smb" -p
```

What am I doing wrong?

**Comment by justsomeguyontheinternet** [comment]
you're mixing parts of the arguments for docker and the container. if you run it without the -d, you'll probably get an exact error message with something like unknown or bad argument.

`docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]`
https://docs.docker.com/engine/reference/run/#general-form

my guess is this is what you want.
```
sudo docker run -it -e TZ=UTC --name samba --restart=always -p 139:139 -p 445:445 -d \
            -v /share/exchange_box:/home/pi/exchange_box \
            -v /share/log:/home/pi/log \
            dperson/samba -p \
            -u "smb;123" \
            -s "exchange_box;/share/exchange_box;yes;no;no;smb" \
            -s "log;/share/log;yes;yes;no;smb"
```
