### ISSUE TITLE
Adding filename mapping support

### ISSUE THREAD

**Issue by ultrafez** [dperson/samba#36]
I'd like to use the [`vfs_catia` module](https://www.samba.org/samba/docs/man/manpages/vfs_catia.8.html) in Samba to add translation of characters in filenames that are considered illegal in Windows (e.g. `:` - see [this post](https://askubuntu.com/questions/79434/a-human-friendlier-samba-name-mangling) for some background), which entails adding 2 new lines to a share section in `smb.conf`:
```
vfs objects = catia
catia:mappings = 0x22:0xa8,0x2a:0xa4
```

It's possible to specify a number of mappings of character=>different character in the `catia:mappings` line on modern versions of Samba, but when this feature was originally added the mapping was hardcoded.

I'd like to use this feature with your Samba image but I'm unsure of how (or the best way) it could be implemented. It could potentially be supported by adding an extra option to the image `-s` flag to specify a mapping list, which if populated would be added to `smb.conf` as described above.

What are your thoughts on adding such a feature? I could have a go at submitting a PR but my bash isn't great (although I imagine I could work it out based on your existing code).

**Comment by dperson** [comment]
Okay, I just pushed a new version that should have what you're looking for let me know if you have any problems. Thanks for the suggestion.
