### ISSUE TITLE
Segfault on ARM

### ISSUE THREAD

**Issue by lxgr** [dperson/samba#363]
The newest image fails on my Raspberry PI due to an upstream bug in the Alpine 3.13.1 base image: https://github.com/alpinelinux/docker-alpine/issues/141

**Comment by dam09fr** [comment]
I was able to make the last build running on armhf by following these instructions:
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

As described in the document, adding ```--security-opt=seccomp=default.json``` does not work ...
So I tried with this option to my ```docker run``` and get it worked: ```--security-opt=seccomp=unconfined```

Useful commands to do some tests:
```
# docker run -it --rm dperson/samba:armhf date
Sun Jan  0 00:100:2009302  1900
```
=> KO 👎 
```
# wget https://raw.githubusercontent.com/moby/moby/master/profiles/seccomp/default.json
(...)
# docker run -it --security-opt=seccomp=default.json --rm dperson/samba:armhf date
Sun Jan  0 00:100:2009302  1900
```
=> KO 👎 
```
# docker run -it --security-opt=seccomp=unconfined --rm dperson/samba:armhf date
Tue Feb 23 18:03:43 UTC 2021
```
=> OK 👍

**Comment by lxgr** [comment]
Note that `seccomp=unconfined` is not recommended due to security concerns. I was able to get this running by updating `libseccomp2` to a newer version on my Docker host.

Also closing this since this is essentially a Docker/host-side bug and not any fault of the image.
