### ISSUE TITLE
broken latest build?

### ISSUE THREAD

**Issue by jandrews377** [dperson/samba#37]
The latest build 2 days ago appears to have broken things. Hopefully its something silly I am doing: 

docker run -it -p 139:139 -p 445:445 dperson/samba:latest -u "jeremy;jeremy" -s "jeremy;/mount/users/jeremy;yes;yes;yes;jeremy"
Unknown parameter encountered: "security mask"
Ignoring unknown parameter "security mask"
Unknown parameter encountered: "force security mode"
Ignoring unknown parameter "force security mode"
Unknown parameter encountered: "directory security mask"
Ignoring unknown parameter "directory security mask"
Unknown parameter encountered: "force directory security mode"
Ignoring unknown parameter "force directory security mode"
Added user jeremy.
smbd version 4.4.7-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2016
Unknown parameter encountered: "security mask"
Ignoring unknown parameter "security mask"
Unknown parameter encountered: "force security mode"
Ignoring unknown parameter "force security mode"
Unknown parameter encountered: "directory security mask"
Ignoring unknown parameter "directory security mask"
Unknown parameter encountered: "force directory security mode"
Ignoring unknown parameter "force directory security mode"
Unknown parameter encountered: "security mask"
Ignoring unknown parameter "security mask"
Unknown parameter encountered: "force security mode"
Ignoring unknown parameter "force security mode"
Unknown parameter encountered: "directory security mask"
Ignoring unknown parameter "directory security mask"
Unknown parameter encountered: "force directory security mode"
Ignoring unknown parameter "force directory security mode"
STATUS=daemon 'smbd' finished starting up and ready to serve connections
Unknown parameter encountered: "security mask"
Ignoring unknown parameter "security mask"
Unknown parameter encountered: "force security mode"
Ignoring unknown parameter "force security mode"
Unknown parameter encountered: "directory security mask"
Ignoring unknown parameter "directory security mask"
Unknown parameter encountered: "force directory security mode"
Ignoring unknown parameter "force directory security mode"

**Comment by dperson** [comment]
Oops, I was trying to fix another issue that was reported, and added those options too (thank you server fault). I wasn't looking at the `docker logs`. Thanks for reporting the issue. I've just pushed a new version that removes those lines once more.
