### ISSUE TITLE
Unable to connect to share

### ISSUE THREAD

**Issue by MPeti1** [dperson/samba#373]
I'm trying to run an SMB server with [this](https://gist.github.com/MPeti1/09b595d0497c0f22677ee9886227ad36) docker compose file with the command `sudo docker-compose up -d`.

When the container has started, `sudo docker-compose logs -ft` shows these 3 lines:

smb      | 2021-04-07T21:59:05.239202629Z smbd version 4.13.7 started.  
smb      | 2021-04-07T21:59:05.239317886Z Copyright Andrew Tridgell and the Samba Team 1992-2020  
smb      | 2021-04-07T21:59:05.609256291Z daemon_ready: daemon 'smbd' finished starting up and ready to serve connections

But when I check my local network in the default file explorer's network menu or in total commander, the SMB server does not show up, and trying to connect to it with \\[hostname]\Storage or \\Hostname\ (by entering this in the path bar, and where hostname is either the hostname of the docker host, or it's IP address on my LAN) doesn't work either: the file explorer shows me an error code of 0x80004005 (unspecified error, of course...), while totla commander just switches back to the rpevious directory.  
I also checked what smbclient has to say. That program is _very_ buggy for me so I might be doing something wrong (constant error messages about trying to use SMB1 even if I specify `-m SMB3`, "unable to initialize messaging context", etc), _but_ `smbclient -L \\localhost -U % -m SMB3` does print me the list of shares on this server (actually the only share I have set up, plus an IPC$ share that I would turn off if possible)

Could you help what am I doing wrong? I've read other issues, the readme, the wiki, I've also read archwiki and other sources if I can find a solution to the problems of smbclient, but they don't really help with mundane errors like these.

**Comment by barkawa** [comment]
I noticed you have guest login disabled for your share, but no user accounts set up, that could be the issue.

**Comment by MPeti1** [comment]
That's a good catch, thank you, but after fixing this it still does not work.

Now this is my command string: `-u "testuser;testpassword" -s "Storage;/mnt/Storage;yes;no;yes`
I've both added a user, and allowed gusts to view the eisting share, but it's still the same: windows explorer doesn't find the server, total commander neither.

PS: I've ran `sudo docker-compose up -d` after editing the compose file with the new command string

**Comment by MPeti1** [comment]
I did some experimenting, and it seems I was able to make it work somehow, but I can only access it from my Android phone with an app called Mixplorer, clients on Windows still fail.

**Comment by MPeti1** [comment]
Ok, found the solution, The firewall on the client machine was the culprit. Add a outgoing rule to LAN IPs for port 445 and it will be allowed through.
