### ISSUE TITLE
Created user is not allowed to visit shared folder, only guest is allowed. Puzzled me a long time, ask for help!

### ISSUE THREAD

**Issue by minifake** [dperson/samba#390]
**This is my usage command:**

```sh
sudo docker run -it -p 139:139 -p 445:445 --name c_samba --restart=always \
            -v /mnt/udisk:/mnt/udisk \
            -d dperson/samba -p \
            -u "pi;abcabc" \
            -s "pu;/mnt/udisk/udisk" \
            -s "pi;/mnt;yes;no;yes;pi" -S
```

I created 2 share folder: `pu` and `pi`.   Added one user `pi`.
When I use username `guest`, I can find the  `pu` and `pi`, and read&write `pu` normally. 
But when I use username `pi` , I can see **nothing**. 

Where is my bug? ( The `smb.conf` file is attached, hope it helps)
[smb.conf.txt](https://github.com/dperson/samba/files/6986996/smb.conf.txt)

**Comment by GoingOffRoading** [comment]
@minifake I am having similar issues...  Even when I setup the config to match what I have on bare-metal samba installs.  Did you figure anything out?

My install is on Kubernetes so the formatting is a little different, but my config so far:

`"-p", "-s", "SHARE;/SHAREDIR;yes;no;no;USER", "-u", "USER;PASS;1000;1000;1000"`

NMBD is enabled as an environmental variable

**Comment by minifake** [comment]
> 

@GoingOffRoading 
I guess you used a wrong docker image just like me. You need choose a correct architecture.

I try to use `dperson/samba:armhf` instead of `dperson/samba`, then everything works well. You can also choose like `dperson/samba:aarch64`, `dperson/samba:amd64`, `dperson/samba:armv7hf`.

One more tip:
If you run samba in Raspberry Pi, `uname -a` returns `aarch64` is not sufficient to use `dperson/samba:aarch64`, you need also make sure `getconf LONG_BIT` returns `64`.
