### ISSUE TITLE
anonymous share on  android TV box, 

### ISSUE THREAD

**Issue by jackadam1981** [dperson/samba#396]
When I use this container, I use the following yaml configuration file.

You can access this share anonymously in win10. Although it cannot be found in the network, you can still access it by entering the IP.

It seems to be a problem with nmbd and WSSD. It doesn't matter. Just visit.

But I can't use Kodi to access this share on my android TV box, indicating that the connection failed.

Other network shares are also inaccessible.

What I need is anonymous sharing, which can be accessed by any name and has all permissions.

It doesn't matter whether you enter a user name or not.

version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Asia/Shanghai'
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /share:/share:z
    command: '-s "share;/share;yes;no;yes;all" -p'

**Comment by jiabuda** [comment]
@jackadam1981 hello, solved? and how to solve this?
