### ISSUE TITLE
User ownership & group

### ISSUE THREAD

**Issue by konsumer** [dperson/samba#40]
I find it really handy to use the [linuxserver](https://github.com/linuxserver) containers, which have standardized on `PUID` and `PGID` for setting the default user & group for things. It would be awesome if I could run this:

```
sudo docker run -it \
    -e PUID=1000 -e PGID=1000 \
    -p 137:137/udp -p 138:138/udp -p 139:139 -p 445:445 \
    -v /path/to/directory:/media \
    -d dperson/samba \
    -s "media;/media;yes;no;yes"
```

If `/path/to/directory` is owned by `1000:1000` user on host, everyone on network has full access to `media`, and permissions stay read/writable (so I can link it to other docker containers that are also using `PUID` and `PGID`.)

They setup `abc` user/group via `PUID` & `PGID` in their base-images, so you can do stuff like this:

```
force user = abc
force group = abc
```

I [started work](https://github.com/konsumer/samba) on a container, but can't test until later tonight (limited networking.) It'd be rad to be able to do this directly with yours, though, and I'm happy to submit a PR once I can test.

**Comment by dperson** [comment]
On my images that I already configured setting the user/group ID, it's by setting the `USERID` and `GROUPID` environment variables. If you're okay with that naming, I'll add it tonight.

**Comment by konsumer** [comment]
Ah, yeh, that sounds fine. Awesome!
