### ISSUE TITLE
ntlm_password_check: NTLMv1 passwords NOT PERMITTED for user 

### ISSUE THREAD

**Issue by ANAT01** [dperson/samba#41]
I have some trouble with connect to samba from Windows XP

samba's log show ```ntlm_password_check: NTLMv1 passwords NOT PERMITTED for user ```

It can be solved with add ```ntlm auth = yes``` to smb.conf or setting Only NTLMv2 in Windows (like this https://www.imss.caltech.edu/node/396)

**Comment by dperson** [comment]
As XP is EOL (End of Life), I'm not overly concerned with maintaining compatibility...

**Comment by Angelinsky7** [comment]
Yes but sadly some devices (like printer) still use NTLMv1)

**Comment by dperson** [comment]
See the `-S` option or the `SMB` environment variable. They're documented in the `README.md`.
