### ISSUE TITLE
Cannot connect: canonicalize_connect_path failed for service samba

### ISSUE THREAD

**Issue by arnaldop** [dperson/samba#42]
I run:

    docker run -it --name samba -p 139:139 -p 445:445 -p 137:137/udp -p 138:138/udp -d dperson/samba -u "root;root" -s "samba;/mnt/data/test;yes;no;no;root"

I get:
```
groupadd: '' is not a valid group name
useradd: user 'root' already exists
Added user root.
smbd version 4.5.2-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2016
STATUS=daemon 'smbd' finished starting up and ready to serve connections
canonicalize_connect_path failed for service samba, path /mnt/data/test
```

Directory structure
```
docker@default:/mnt/data$ ll / ; ll /mnt ; ll /mnt/data
...
drwxr-xr-x    9 root     root           180 Dec 14 21:23 mnt/
...
drwxr-xr-x    7 root     root          4096 Jan 19 06:26 data/
...
drwxrwxrwx    2 root     root          4096 Jan 19 06:26 test/
```

I've run the command both from inside the Host (with and without sudo) as well as from outside.

I can't figure out what's up. It would seem that all relevant directories are executable, satisfying Samba requirements.

**Comment by dperson** [comment]
I ran it very close to how you did (just not detached) and I've been unable to reproduce the error that you're seeing... One note is that you're not actually passing `/mnt/data` into the container. Try adding `-v /mnt/data:/mnt/data` to your arguments to docker.

```
$ sudo docker run --rm -it --name samba -p 139:139 -p 445:445 -p 137:137/udp -p 138:138/udp dperson/samba -u "root;root" -s "samba;/mnt/data/test;yes;no;no;root"
groupadd: '' is not a valid group name
useradd: user 'root' already exists
Added user root.
smbd version 4.5.2-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2016
```

**Comment by arnaldop** [comment]
That was it!!!
Thanks so much for the insight!
