### ISSUE TITLE
Unable to complete large file transfer

### ISSUE THREAD

**Issue by therevoman** [dperson/samba#46]
I am having difficulties getting large media files to transfer completely between my Windows 10 system and my RHEL 7 server.  Doing a little reading it might be because of the "strict locking" setting.  Is it possible to expose this as a configurable item?

**Comment by dperson** [comment]
Sorry for the slow reply, I've been really busy with the day job.

Were you creating either a docker volume or using local storage (from the server's filesystem) for the share? The default overlay created at launch has had issues with arbitrarily large files for others...

**Comment by dperson** [comment]
I hope the suggestion helped with your issue, if you're still having problems feel free to comment / reopen the issue. I'm going to close it for now.
