### ISSUE TITLE
Add support for the "Follow Symlinks" Option for Shares

### ISSUE THREAD

**Issue by PhilippHeuer** [dperson/samba#52]
Hey,

i want to report that i always get those 2 warnings in the console, the veto files option probably isn't supported anymore.
```
Unknown parameter encountered: "   veto files"
Ignoring unknown parameter "   veto files"
```

I want to request an option to enable symlinks in file shares.
Required changes to the config: http://unix.stackexchange.com/a/137192

Greetings

**Comment by dperson** [comment]
Sorry for the slow reply, I was out of town on vacation.

There was a SNAFU where somehow Unicode blanks got in instead of spaces. I think this is fixed now. I've added the `follow symlinks = yes` to the default configuration now.
