### ISSUE TITLE
Samba filesize limit 2GB

### ISSUE THREAD

**Issue by Aviraer** [dperson/samba#55]
Can not copy files larger than 2g.

**Comment by Aviraer** [comment]
docker logs:
![logs](https://cloud.githubusercontent.com/assets/8214334/25777607/a2bee18c-3314-11e7-96fb-d28a6568a2d0.png)

**Comment by dperson** [comment]
What OS and docker version are you using? Thanks.

**Comment by Aviraer** [comment]
CentOS Linux release 7.2.1511 x64 and docker 17.03.1-ce

**Comment by dperson** [comment]
I've just pushed a new version to git, and it's building a container on the docker servers now. Try a fresh pull in about 10 minutes.

**Comment by Aviraer** [comment]
Works fine,thanks.
