### ISSUE TITLE
can I enable recycle function ?

### ISSUE THREAD

**Issue by xjflyttp** [dperson/samba#56]
```
https://www.samba.org/samba/docs/man/manpages/vfs_recycle.8.html
```

Configure Like this.
```
vfs object = recycle
recycle:repository = .deleted/%U
recycle:keeptree = Yes
recycle:versions = Yes
recycle:maxsixe = 0
```

Thanks!

**Comment by dperson** [comment]
This should be enabled on the new build. Thanks.

**Comment by xjflyttp** [comment]
Hi
recycle function need samba-vfs-modules apt package.
Thanks1

**Comment by dperson** [comment]
Yep, when I woke up and tested it, I found the same thing. Sigh. It's fixed now.

**Comment by passos** [comment]
@dperson could you please add some document about how to configure and use recycle bin feature in docker command line?

**Comment by xjflyttp** [comment]
document url:
---
https://www.samba.org/samba/docs/current/man-html/vfs_recycle.8.html
---

in samba.sh
---
    echo "   vfs objects = recycle" >>$file
    echo "   recycle:repository = .deleted/%U" >>$file
    echo "   recycle:keeptree = Yes" >>$file
    echo "   recycle:versions = Yes" >>$file
    echo "   recycle:maxsixe = 0" >>$file
---

Thanks.
