### ISSUE TITLE
Error on access (guest or user)

### ISSUE THREAD

**Issue by jtenniswood** [dperson/samba#57]
Somethings gone wrong, the container is throwing an error now...

Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/recycle.so': /usr/lib/x86_64-linux-gnu/samba/vfs/recycle.so: cannot open shared object file: No such file or directory
error probing vfs module 'recycle': NT_STATUS_UNSUCCESSFUL
smbd_vfs_init: vfs_init_custom failed for recycle
vfs_init failed for service IPC$

**Comment by dperson** [comment]
Sorry for the inconvienence, that was a derp on my part. It should be fixed now.

**Comment by jtenniswood** [comment]
No worries, thanks for the quick fix!
Appreciated
