### ISSUE TITLE
Samba server can't be found in the network

### ISSUE THREAD

**Issue by poolieh** [dperson/samba#59]
Hey! :)

This is my first time working with docker since I am using it for a school project.

I encountered a problem when I tried to connect to the samba server from another linux machine.

My ubuntu host uses the config 

sudo docker run -it --name samba -p 139:139 -p 445:445 \-d dperson/samba \-n \-s "public;/tmp;yes;no;yes" \-w "WORKGROUP". 

My host can find the server when I navigate to "Network - Windows-Network".

Whereas my ubuntu client cant find the server at "Network - Windows-Network".

My host has the IP 192.168.7.3 and my client has the IP 192.168.7.4, they can ping each other and my client can reach a docker-webserver my hostsystem is hosting.

Maybe you can help me find the mistake, I'm trying to get this working for 2 days now :D

**Comment by poolieh** [comment]
Nevermind, found my mistake. Sorry for the interruption.

**Comment by nachopro** [comment]
Hi @poolieh , I'm new here and I have the same issue. But I can't solve!

Can you share your mistake/solution? Thanks!
