### ISSUE TITLE
Add passwords as hashes

### ISSUE THREAD

**Issue by hugochinchilla** [dperson/samba#6]
I'm writting a startup script for a samba container, as the snippet will be posted on a wiki I don't like having all passwords in plaintext there, it would be nice to be able to set the user password as a hash so the script can be public without security being compromised.

**Comment by dperson** [comment]
Hugo,

Unfortunately, both a Unix account and a Samba account need to be created. The Unix account just needs to exist (no password need be set, even though it supports using a hash). The problem is really the Samba account, `smbpasswd` doesn't support using a hash for creating a user and/or setting a user password.

**Comment by hugochinchilla** [comment]
Yesterday I was invesitgating this a little, I found that using pdbedit I can export a samba users database in a format which smbpasswd accepts, using `sudo pdbedit -L -w`

The output is as follows:

```
user1:1003:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:28E0C29E023C2C686C0CA509E8A6B63C:[U          ]:LCT-53BA5618:
user2:1005:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:BE73623B2CBBF997DD129A725F2592E7:[U          ]:LCT-53E9E5FB:
user3:1002:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:14D4DB00CBE3C3551CB2CF890CD912C7:[U          ]:LCT-53DB779F:
```

I'm not sure, I haven't tested it, but I think the hashes are the passwords, I will test it when I have some time to investigate, but if this are the password hashes we should be able to add this feature, as I understand from the manpage that smbpasswd can import this data.

**Comment by dperson** [comment]
I've never used pbedit before, but if you get something working that I can
run in a script in the container, let me know. I'll be glad to add it. If I
come up with a way I'll add it in as well.

-- 
David P.

**Comment by dperson** [comment]
I did add an import option now, it's building now and should be available shortly. You'll have to share a smbpasswd file that's already created into the container and then use the `-i </full/path/to/file/in/container>` to import it. Hope this solves your problem.

**Comment by hugochinchilla** [comment]
Awesome, thank you very much!!
