### ISSUE TITLE
Making recycle optional

### ISSUE THREAD

**Issue by predakanga** [dperson/samba#60]
It would be very much appreciated if you could add an option to let people disable the recycle VFS module - I use your image without a persistent smb.conf, so there's currently no way to disable it other than rebuilding the image.

I'd also suggest that it may be a good idea to make it opt-in, rather than opt-out. Principle of least surprise and all that, a lot of people are going to be confused about why they're not reclaiming space when they delete their files.

**Comment by dperson** [comment]
There is now a `-r` option to disable the recycle bin feature.

**Comment by waspinator** [comment]
you can also use disable recycle in a `docker-compose.yml` file. Not sure what the value should be, but `-r` seems to work.

```
environment:
    RECYCLE: "-r" 
```
