### ISSUE TITLE
Permission denied on client even readonly is set to no

### ISSUE THREAD

**Issue by luomiao** [dperson/samba#63]
Hi, thanks for your great work of this samba container!
It's quite easy to use. However, it seems I cannot write into the shares on the client.
This is how I start it on the server:
`docker run -it -p 139:139 -p 445:445 -v /tmp:/exports dperson/samba -s "public;/exports;no;no;no;foo" -u "foo;bar"`

And on the client side I mounted the shares using:
`sudo mount -t cifs -o username=foo,password=bar //10.192.68.131/public /mnt`

Then on the client side, there is no permission to write to the mounted path.
Both server and client are ubuntu VMs.

Any suggestions? Thanks a lot!

**Comment by dperson** [comment]
Everything you're doing looks right... are there any logs from the docker container (`sudo docker logs <actual_containername>`)? Or on the system you're mounting it on (`dmesg` and `journalctl -xe`)?

**Comment by luomiao** [comment]
Thanks for your reply.
I have found my problem.
I created this share with a fake username foo. But after it's mounted on the client side, I am using another username to access it. I misunderstood the permission logic for smb shares.

**Comment by dperson** [comment]
I'm happy you got it working.
