### ISSUE TITLE
how to install on raspberry pi?

### ISSUE THREAD

**Issue by AnderssonPeter** [dperson/samba#65]
I tried running the following `sudo docker run -it --name samba -p 139:139 -p 445:445 -p 137:137/udp -p 138:138/udp -v /data:/mount -d dperson/samba -n`, but i get a format error, guessing its trying to run x86 or x64 code..

any chance you could add a tag for arm?

**Comment by dperson** [comment]
It already is. But I've never run docker on my RasPi, so it's up to you to figure out how to run the right platform version

```
dperson@tundro$ head -1 docker/samba/Dockerfile*
==> docker/samba/Dockerfile <==
FROM debian:stretch

==> docker/samba/Dockerfile.aarch64 <==
FROM aarch64/debian:stretch

==> docker/samba/Dockerfile.armhf <==
FROM armhf/debian:stretch
```

**Comment by AnderssonPeter** [comment]
i meant that if you add a tag like `arm` at dockerhub people could just run `sudo docker run -it --name samba -p 139:139 -p 445:445 -p 137:137/udp -p 138:138/udp -v /data:/mount -d dperson/samba:arm -n` As you already have the right dockerfile it should be easy?

**Comment by AnderssonPeter** [comment]
Or I guess two tags `aarch64` and `armhf` would be the best, but I'm 99% sure armhf would work on a pi.

**Comment by JessieSuffrage** [comment]
+1 on @AnderssonPeter's suggestion. Tags appear to be how official images for Node & Debian are managed. Allows for super easy selection from dockerhub, especially when using a UI like Portainer.

**Comment by dperson** [comment]
AFAIK (As Far As I Know) there's no way to add a tag via the Dockerfile and / or set it up on docker hub to tag them. I am just a guy that has a normal day job too, there's not even really an API to add a tag to an image on docker hub that I could find.

**Comment by htkoca** [comment]
https://docs.docker.com/docker-hub/builds/#create-an-automated-build seems to suggest tags are branch based?

**Comment by htkoca** [comment]
I appreciate the work you do @dperson - I use this image regularly. Just trying to help!

**Comment by dperson** [comment]
Ah, cool thanks. I'll try to get the new branches created and added to builds in the hub soon. I'd missed entirely that it would create tags for them.

**Comment by dperson** [comment]
Well they're added, let me know if it solves the problem for you.

**Comment by dperson** [comment]
Hmm, the builds are failing, it seems (based on the errors) that it's trying to do the build for the ARM systems on x86 systems... not going to work.

**Comment by htkoca** [comment]
Thanks anyway - I forked your repository to play around with, maybe I'll come up with something

**Comment by dperson** [comment]
I figured out a way to get docker hub to build them. There are now `rpi` and `armv7hf` tagged builds. Please let me know if they work for you. If they do, I'll add them to the `README.md` documentation.

**Comment by JessieSuffrage** [comment]
Great work mate! I got Samba installed and working through Docker Hub via the armv7hf tag on a Raspberry Pi 3 running Raspbian Stretch.

I didn't try the rpi image.

Cheers :)

**Comment by dperson** [comment]
Glad to hear it. I'll add it to the docs soon.

**Comment by dperson** [comment]
Made some changes, the tag names have simplified now there's just `armhf`. Hopefully no more changes in the naming. Thanks.
