### ISSUE TITLE
Using this image as AD DC

### ISSUE THREAD

**Issue by cweickhmann** [dperson/samba#67]
Hi!

This might sound like a stuipd idea, but I am trying to test this image to create an Active Directory (AD) Domain Controller (DC).
Two issues I came across:
 * samba-tool throws errors like "ldb: unable to stat module /usr/lib/x86_64-linux-gnu/samba/ldb : No such file or directory" and it wants 'xattr' to be present.
 * Once samba-tool was used to setup the AD DC, the container would not start anymore throwing the message: "server role = 'active directory domain controller' not compatible with running smbd standalone. You should start 'samba' instead, and it will control starting smbd if required."

The first issue is quickly fixed by adding two more packages in the Dockerfile (`samba-dsdb-modules` and `xattr`). Depending on your intentions, this might be worth adding either way. I have a fork with a modification to the Dockerfiles.

The second issue may be completely against the purpose of the image and samba.sh ;-)

What are your thoughts?

**Comment by dperson** [comment]
I made the container as a simple way to create a read-only share for a few files to a media player at my house. It's been far more popular than I ever thought it would be. If starting `samba` will also work for the stand alone file share, then it's no problem to me. I'll have to do some testing before I answer you for sure one way or another.

**Comment by dperson** [comment]
After looking at the issue a bit more, the two packages have a lot of other dependencies and the different startup method to me make this use case a separate container...
