### ISSUE TITLE
I can't add user

### ISSUE THREAD

**Issue by nachopro** [dperson/samba#68]
Hi! I created a container and now I want to add a new user.

```
$ sudo docker exec -it samba samba.sh -u "new_user:new_password"
/usr/bin/samba.sh: line 132: 2: unbound variable
```

I'm misunderstanding something?

Thanks!

**Comment by nachopro** [comment]
So sorry!! i'm using ":" between user and password. Change to ";" an it's working!

**Comment by dperson** [comment]
No problem, glad you spotted it and the container is working for you.
