### ISSUE TITLE
Force user

### ISSUE THREAD

**Issue by nosorozec** [dperson/samba#73]
Hi,

thanks for such a great samba packaged in docker!

Is there any change to change the "force user" in the startup parameters?

Rgds, Konrad

**Comment by dperson** [comment]
The user only exists inside the container, and the user that you'd change it to would have to exist inside the container as well. In samba the `force user` just changes the user that is reading / writing to the filesystem, samba still manages the logged in user separately.

There is support already for changing the smbuser user ID and group ID of the user by setting the `USERID` and `GROUPID` environment variables. With that you can get them to match a user that exists outside the container.

You'll have to explain your use case further to help me understand if this won't work for you. Thanks.
