### ISSUE TITLE
Permit arbitrary global options (for debugging, using insecure settings etc.)

### ISSUE THREAD

**Issue by m7a** [dperson/samba#74]
Hello,

I just came across this image and got a Samba share working in under a day -- nice :). To achieve what I wanted, I needed to go beyond the configuration options already provided by `samba.sh`'s parameters. To do that, I temporarily hacked the defaults in the `Dockerfile` until it worked and then thought about a cleaner solution.

What about an option `-g` to provide arbitrary configuration entries for `smb.conf`? This is sufficient for my use case (and provides a workaround/solution for https://github.com/dperson/samba/issues/41)?

The patch attached allows arbitrary options to be added in the `[global]`-section of the `smb.conf`. Would you mind applying the patch? (If yes, is there anything I can improve for arbitrary options to be possible with the dperson/samba image?)

TIA
Linux-Fan

Attachment [global_option_patch.txt](https://github.com/dperson/samba/files/1326776/global_option_patch.txt)

**Comment by Angelinsky7** [comment]
i would love that

**Comment by dperson** [comment]
Merged
