### ISSUE TITLE
response from daemon: linux spec user: unable to find user test;test: no matching entries in passwd file

### ISSUE THREAD

**Issue by didn0t** [dperson/samba#78]
Trying to set up, docker is running on VMWare Photon Linux virtual machine.

Following the examples given I get the following when trying to create new users:

root@photon [ /storage ]# docker run -it --name samba -p 139:139 -p 445:445 -u  "test;test"  -v /storage2/Samba:/shares -d dperson/samba
c7759f182e132502bdb5f37b9166237362848f0ff73db432e18d2750bed09a6a
docker: Error response from daemon: linux spec user: unable to find user test;test: no matching entries in passwd file.

**Comment by dperson** [comment]
Try running it without the `-d` option, so that output will be on the console. Initially I'd say that it looks like Photon is trying to parse the arguments to the docker command. Either `docker` is a script that calls the real docker command, or something similar.

**Comment by didn0t** [comment]
root@photon [ ~ ]# docker run -it --name samba -p 139:139 -p 445:445 -u  "test;test"  -v /storage2/Samba:/shares  dperson/samba
docker: Error response from daemon: linux spec user: unable to find user test;test: no matching entries in passwd file.

root@photon [ ~ ]# which docker
/usr/bin/docker

root@photon [ ~ ]# /usr/bin/docker -v
Docker version 17.06.0-ce, build 02c1d87

**Comment by dperson** [comment]
Oh, I need coffee. It's where the `-u "test;test"` argument is on the command line. It has to be after the `dperson/samba`, IE:
```
docker run -it --name samba -p 139:139 -p 445:445 -v /storage2/Samba:/shares -d dperson/samba -u "test;test"
```
