### ISSUE TITLE
NTLMV1 support

### ISSUE THREAD

**Issue by Archcry** [dperson/samba#81]
Some older devices with a crappy samba implementation (such as my xtreamer sidewinder 3) need NTLMV1 to be turned on. As of samba version 4.5 this is disabled by default for security reasons.
It would be nice if we could have a flag / environment variable that changes this behaviour.

Source: https://wiki.archlinux.org/index.php/samba#Password_Error_when_correct_credentials_are_given_.28error_1326.29

(Will make a pull-request when I have everything setup correctly here at home :P)

**Comment by Archcry** [comment]
Suggestions on what to call the flag are welcome ofcourse.

**Comment by dperson** [comment]
There is the `-g` command line option to set global configuration items in the `smb.conf` file for the server. Just call it twice with the options that you linked. IE:
```
-g "lanman auth=yes" -g "ntlm auth=yes"
```

**Comment by Archcry** [comment]
Oh oops, can't believe I overlooked that option!
This makes life a lot eaier, thanks!
