### ISSUE TITLE
Can't access shared folders 

### ISSUE THREAD

**Issue by bhavinp084** [dperson/samba#84]
I'm running following:
docker run -it -p 139:139 -p 445:445 \
--name code --rm \
-v gp_upload:/home/samba/upload/Marketplace \
-e "USERID=0" \
-e "GROUPID=0" \
-d dperson/samba \
-u "samba;password" \
-s "code;/home/samba/upload/Marketplace;yes;no;yes;all;;samba"

On Mac then I try to connect to following - none of them works

smb://code/code
smb://172.17.0.3/code
smb://localhost/code
any Ideas ? any help would be highly appreciated - Thanks in advance

I'm trying to upload/download files from the shared location - from spring boot application. 
Is there any domain that we need to use while excessing this folder ?

**Comment by dperson** [comment]
Are you running docker on your mac as well?

**Comment by bhavinp084** [comment]
yeah running docker locally in container & trying to connect to that container from my spring boot application.

**Comment by dperson** [comment]
Okay, as docker is actually run in a Linux VM run on the host, I'm not really sure how the port mapping (`-p`) works honestly. Can you provide the output of the following (run on your mac):

1. /sbin/ifconfig en0
1. /usr/sbin/netstat -rn
1. docker ps -a | grep dperson/samba
1. host code
1. /sbin/ping 172.17.0.3
1. /usr/sbin/traceroute 172.17.0.3

**Comment by dperson** [comment]
More importantly, can you send any error messages that the mount attempt gives you?

**Comment by bhavinp084** [comment]
I mainly get unknown host while trying to mount. I was trying to mount using Finder. 
For you above command pings returns timeout.

when I did ifconfig on docker container I got ip address of: 172.21.0.2

➜  sftp-docker git:(Smb_Changes) ✗ docker ps -a 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                             PORTS                                                                                      NAMES
1c0dbd970eb8        dperson/samba       "samba.sh -u samba..."   7 seconds ago       Up 17 seconds (health: starting)   0.0.0.0:139->139/tcp, 0.0.0.0:445->445/tcp, 0.0.0.0:2537->137/udp, 0.0.0.0:2538->138/udp   samba

➜  sftp-docker git:(Smb_Changes) ✗ ping 172.21.0.2
PING 172.21.0.2 (172.21.0.2): 56 data bytes
36 bytes from 10.251.66.6: Destination Net Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 82f9   0 0000  39  01 22e9 10.171.37.5  172.21.0.2 


➜  ~ traceroute 172.21.0.2
traceroute to 172.21.0.2 (172.21.0.2), 64 hops max, 52 byte packets
 1  10.171.37.254 (10.171.37.254)  4.317 ms  2.102 ms  2.972 ms
 2  10.171.32.134 (10.171.32.134)  5.967 ms  3.041 ms  6.321 ms
 3  10.171.3.17 (10.171.3.17)  3.789 ms  5.544 ms  3.882 ms
 4  10.171.3.21 (10.171.3.21)  8.347 ms  8.962 ms  8.558 ms
 5  10.252.122.6 (10.252.122.6)  10.376 ms  12.156 ms  8.758 ms
 6  10.252.111.2 (10.252.111.2)  83.984 ms  83.733 ms  80.938 ms
 7  10.252.122.165 (10.252.122.165)  81.965 ms  86.533 ms  80.988 ms
 8  10.251.66.6 (10.251.66.6)  80.829 ms !N  86.229 ms !N  86.423 ms !N

However, I tried 172.17.0.3 as you requested as well. For ping I got same timeout

➜  ~ traceroute 172.17.0.3
traceroute to 172.17.0.3 (172.17.0.3), 64 hops max, 52 byte packets
 1  10.171.37.254 (10.171.37.254)  4.410 ms  2.519 ms  2.729 ms
 2  10.171.32.134 (10.171.32.134)  2.845 ms  7.096 ms  2.060 ms
 3  10.171.3.17 (10.171.3.17)  2.658 ms  2.279 ms  1.886 ms
 4  10.171.3.21 (10.171.3.21)  7.502 ms !N  7.004 ms !N  19.961 ms !N

Thanks
Bhavin

**Comment by dperson** [comment]
Okay, it looks like you're running some or all of the commands on the Docker VM or one of it's containers... my intention was that they be run on the mac native system. Please replace `172.17.0.3` with the IP address of the samba container. Thanks.

**Comment by anuprajg** [comment]
Is there a solution for this?

**Comment by jatoko** [comment]
The problem is that MacOS does not allow smb connections to "local" shares, e.g. 127.0.0.1.
To solve the issue:

- setup loopback address different from 127.0.0.1 ([more info](https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x))
```
sudo ifconfig lo0 127.0.0.2 alias up
```

- expose ports when starting docker container to the new loopback dev:
```
--expose 137 -p 127.0.0.2:137:137  \
--expose 138 -p 127.0.0.2:138:138  \
--expose 139 -p 127.0.0.2:139:139  \
--expose 445 -p 127.0.0.2:445:445
```

- connect with "Finder" via "Go"->"Connect To Server..."->"smb://127.0.0.2"

**Comment by ivanghisleni** [comment]
Hi , 

I'm trying on my mac with this command: 
```
docker run -d -it --name samba --rm \
        --net=host \
        -e USERID=0 \
        -e GROUPID=0 \
        --expose 137 -p 127.0.0.2:137:137  \
        --expose 138 -p 127.0.0.2:138:138  \
        --expose 139 -p 127.0.0.2:139:139  \
        --expose 445 -p 127.0.0.2:445:445 \
        -v ivan:/Users/ivanghisleni/workspaces/samba/ivan \
        dperson/samba \
            -s "ivan;/Users/ivanghisleni/workspaces/samba/ivan;yes;no"
```

before I executed :
`sudo ifconfig lo0 127.0.0.2 alias up`

on docker run I have this message:
...
WARNING: Published ports are discarded when using host network mode
....

the docker logs are:
```
smbd version 4.8.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2018
daemon_ready: STATUS=daemon 'smbd' finished starting up and ready to serve connections
```

but when I'm trying to connect to smb://127.0.0.2 I can't access.

Where I'm wrong?

thanks
