### ISSUE TITLE
NT_STATUS_INVALID_NETWORK_RESPONSE when using armhf image on arm64v8 host

### ISSUE THREAD

**Issue by g000444555** [dperson/samba#85]
Note that `armhf` is compatible with `arm64v8` and I am successfully running other `armhf` images on my `arm64v8` host.

Following are the steps to reproduce the issue.

Start an instance

    sudo docker run -it -p 139:139 -p 445:445 -d dperson/samba:armhf \
                -u "example1;badpass" \
                -u "example2;badpass" \
                -s "public;/share" \
                -s "users;/srv;no;no;no;example1,example2" \
                -s "example1 private;/example1;no;no;no;example1" \
                -s "example2 private;/example2;no;no;no;example2" \
                -w "WORKGROUP" \
                -g "log level = 3"

When trying to connect to the remote samba server, I get the error

    smbclient //192.168.1.13/public -U example1
    WARNING: The "syslog" option is deprecated
    Enter example1's password: 
    protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE

The output of `docker logs` on the remote samba server is

    docker logs 2fc775951c34
    Added user example1.
    Added user example2.
    smbd version 4.6.8 started.
    Copyright Andrew Tridgell and the Samba Team 1992-2017
    Registered MSG_REQ_POOL_USAGE
    Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
    lp_load_ex: refreshing parameters
    Initialising global parameters
    Processing section "[global]"
    Processing section "[public]"
    Processing section "[users]"
    Processing section "[example1 private]"
    Processing section "[example2 private]"
    adding IPC service
    added interface eth0 ip=172.17.0.2 bcast=172.17.255.255 netmask=255.255.0.0
    loaded services
    INFO: Profiling support unavailable in this build.
    Standard input is not a socket, assuming -D option
    Becoming a daemon.
    No builtin backend found, trying to load plugin
    Module 'tdbsam' loaded
    pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
    tdb(/var/lib/samba/registry.tdb): tdb_open_ex: could not open file /var/lib/samba/registry.tdb: No such file or directory
    Could not open tdb: No such file or directory
    Failed to fetch domain sid for WORKGROUP
    Failed to fetch domain sid for WORKGROUP
    Initialise the svcctl registry keys if needed.
    Initialise the eventlog registry keys if needed.
    STATUS=daemon 'smbd' finished starting up and ready to serve connections
    waiting for connections
    Allowed connection from 127.0.0.1 (127.0.0.1)
    init_oplocks: initializing messages.
    Transaction 0 of length 216 (0 toread)
    switch message SMBnegprot (pid 54) conn 0x0
    Requested protocol [PC NETWORK PROGRAM 1.0]
    Requested protocol [MICROSOFT NETWORKS 1.03]
    Requested protocol [MICROSOFT NETWORKS 3.0]
    Requested protocol [LANMAN1.0]
    Requested protocol [LM1.2X002]
    Requested protocol [DOS LANMAN2.1]
    Requested protocol [LANMAN2.1]
    Requested protocol [Samba]
    Requested protocol [NT LANMAN 1.0]
    Requested protocol [NT LM 0.12]
    Requested protocol [SMB 2.002]
    Requested protocol [SMB 2.???]
    Selected protocol SMB2_FF
    GENSEC backend 'gssapi_spnego' registered
    GENSEC backend 'gssapi_krb5' registered
    GENSEC backend 'gssapi_krb5_sasl' registered
    GENSEC backend 'spnego' registered
    GENSEC backend 'schannel' registered
    GENSEC backend 'naclrpc_as_system' registered
    GENSEC backend 'sasl-EXTERNAL' registered
    GENSEC backend 'ntlmssp' registered
    GENSEC backend 'ntlmssp_resume_ccache' registered
    GENSEC backend 'http_basic' registered
    GENSEC backend 'http_ntlm' registered
    Selected protocol SMB 2.???
    Selected protocol SMB3_11
    Got NTLMSSP neg_flags=0x62088215
    Got user=[guest] domain=[WORKGROUP] workstation=[2FC775951C34] len1=24 len2=262
    lp_load_ex: refreshing parameters
    Initialising global parameters
    Processing section "[global]"
    Processing section "[public]"
    Processing section "[users]"
    Processing section "[example1 private]"
    Processing section "[example2 private]"
    adding IPC service
    check_ntlm_password:  Checking password for unmapped user [WORKGROUP]\[guest]@[2FC775951C34] with the new password interface
    check_ntlm_password:  mapped user is: [2FC775951C34]\[guest]@[2FC775951C34]
    check_sam_security: Couldn't find user 'guest' in passdb.
    check_ntlm_password:  Authentication for user [guest] -> [guest] FAILED with error NT_STATUS_NO_SUCH_USER
    No such user guest [WORKGROUP] - using guest account
    Allowed connection from 127.0.0.1 (127.0.0.1)
    idmap range not specified for domain '*'
    Failed to fetch domain sid for WORKGROUP
    Failed to fetch domain sid for WORKGROUP
    Forced user smbuser
    Forced group users
    Connect path is '/tmp' for service [IPC$]
    Initialising default vfs hooks
    Initialising custom vfs hooks from [/[Default VFS]/]
    Initialising custom vfs hooks from [recycle]
    Module 'recycle' loaded
    2fc775951c34 (ipv4:127.0.0.1:33059) connect to service IPC$ initially as user smbuser (uid=1000, gid=100) (pid 54)
    api_pipe_bind_req: srvsvc -> srvsvc rpc service
    check_bind_req for srvsvc context_id=0
    check_bind_req: srvsvc -> srvsvc rpc service
    api_rpcTNP: rpc command: SRVSVC_NETSHAREENUMALL
    Failed to fetch record!
    pcap cache not loaded
    2fc775951c34 (ipv4:127.0.0.1:33059) closed connection to service IPC$
    Server exit (NT_STATUS_END_OF_FILE)
    Allowed connection from 127.0.0.1 (127.0.0.1)
    init_oplocks: initializing messages.
    Transaction 0 of length 72 (0 toread)
    netbios connect: name1=LOCALHOST      0x20 name2=2FC775951C34   0x0
    netbios connect: local=localhost remote=2fc775951c34, name type = 0
    Transaction 0 of length 216 (0 toread)
    switch message SMBnegprot (pid 55) conn 0x0
    Requested protocol [PC NETWORK PROGRAM 1.0]
    Requested protocol [MICROSOFT NETWORKS 1.03]
    Requested protocol [MICROSOFT NETWORKS 3.0]
    Requested protocol [LANMAN1.0]
    Requested protocol [LM1.2X002]
    Requested protocol [DOS LANMAN2.1]
    Requested protocol [LANMAN2.1]
    Requested protocol [Samba]
    Requested protocol [NT LANMAN 1.0]
    Requested protocol [NT LM 0.12]
    Requested protocol [SMB 2.002]
    Requested protocol [SMB 2.???]
    Selected protocol SMB2_FF
    GENSEC backend 'gssapi_spnego' registered
    GENSEC backend 'gssapi_krb5' registered
    GENSEC backend 'gssapi_krb5_sasl' registered
    GENSEC backend 'spnego' registered
    GENSEC backend 'schannel' registered
    GENSEC backend 'naclrpc_as_system' registered
    GENSEC backend 'sasl-EXTERNAL' registered
    GENSEC backend 'ntlmssp' registered
    GENSEC backend 'ntlmssp_resume_ccache' registered
    GENSEC backend 'http_basic' registered
    GENSEC backend 'http_ntlm' registered
    Selected protocol SMB 2.???
    Selected protocol SMB3_11
    Got NTLMSSP neg_flags=0x62088215
    Got user=[guest] domain=[WORKGROUP] workstation=[2FC775951C34] len1=24 len2=262
    lp_load_ex: refreshing parameters
    Initialising global parameters
    Processing section "[global]"
    Processing section "[public]"
    Processing section "[users]"
    Processing section "[example1 private]"
    Processing section "[example2 private]"
    adding IPC service
    check_ntlm_password:  Checking password for unmapped user [WORKGROUP]\[guest]@[2FC775951C34] with the new password interface
    check_ntlm_password:  mapped user is: [2FC775951C34]\[guest]@[2FC775951C34]
    check_sam_security: Couldn't find user 'guest' in passdb.
    check_ntlm_password:  Authentication for user [guest] -> [guest] FAILED with error NT_STATUS_NO_SUCH_USER
    No such user guest [WORKGROUP] - using guest account
    Allowed connection from 2fc775951c34 (127.0.0.1)
    idmap range not specified for domain '*'
    Failed to fetch domain sid for WORKGROUP
    Failed to fetch domain sid for WORKGROUP
    pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
    Forced user smbuser
    Forced group users
    Connect path is '/tmp' for service [IPC$]
    Initialising default vfs hooks
    Initialising custom vfs hooks from [/[Default VFS]/]
    Initialising custom vfs hooks from [recycle]
    Module 'recycle' loaded
    2fc775951c34 (ipv4:127.0.0.1:42097) connect to service IPC$ initially as user smbuser (uid=1000, gid=100) (pid 55)
    2fc775951c34 (ipv4:127.0.0.1:42097) closed connection to service IPC$
    Server exit (NT_STATUS_END_OF_FILE)
    pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
    Allowed connection from 127.0.0.1 (127.0.0.1)
    init_oplocks: initializing messages.
    Transaction 0 of length 216 (0 toread)
    switch message SMBnegprot (pid 66) conn 0x0
    Requested protocol [PC NETWORK PROGRAM 1.0]
    Requested protocol [MICROSOFT NETWORKS 1.03]
    Requested protocol [MICROSOFT NETWORKS 3.0]
    Requested protocol [LANMAN1.0]
    Requested protocol [LM1.2X002]
    Requested protocol [DOS LANMAN2.1]
    Requested protocol [LANMAN2.1]
    Requested protocol [Samba]
    Requested protocol [NT LANMAN 1.0]
    Requested protocol [NT LM 0.12]
    Requested protocol [SMB 2.002]
    Requested protocol [SMB 2.???]
    Selected protocol SMB2_FF
    GENSEC backend 'gssapi_spnego' registered
    GENSEC backend 'gssapi_krb5' registered
    GENSEC backend 'gssapi_krb5_sasl' registered
    GENSEC backend 'spnego' registered
    GENSEC backend 'schannel' registered
    GENSEC backend 'naclrpc_as_system' registered
    GENSEC backend 'sasl-EXTERNAL' registered
    GENSEC backend 'ntlmssp' registered
    GENSEC backend 'ntlmssp_resume_ccache' registered
    GENSEC backend 'http_basic' registered
    GENSEC backend 'http_ntlm' registered
    Selected protocol SMB 2.???
    Selected protocol SMB3_11
    Got NTLMSSP neg_flags=0x62088215
    Got user=[guest] domain=[WORKGROUP] workstation=[2FC775951C34] len1=24 len2=262
    lp_load_ex: refreshing parameters
    Initialising global parameters
    Processing section "[global]"
    Processing section "[public]"
    Processing section "[users]"
    Processing section "[example1 private]"
    Processing section "[example2 private]"
    adding IPC service
    check_ntlm_password:  Checking password for unmapped user [WORKGROUP]\[guest]@[2FC775951C34] with the new password interface
    check_ntlm_password:  mapped user is: [2FC775951C34]\[guest]@[2FC775951C34]
    check_sam_security: Couldn't find user 'guest' in passdb.
    check_ntlm_password:  Authentication for user [guest] -> [guest] FAILED with error NT_STATUS_NO_SUCH_USER
    No such user guest [WORKGROUP] - using guest account
    Allowed connection from 127.0.0.1 (127.0.0.1)
    idmap range not specified for domain '*'
    Failed to fetch domain sid for WORKGROUP
    Failed to fetch domain sid for WORKGROUP
    Forced user smbuser
    Forced group users
    Connect path is '/tmp' for service [IPC$]
    Initialising default vfs hooks
    Initialising custom vfs hooks from [/[Default VFS]/]
    Initialising custom vfs hooks from [recycle]
    Module 'recycle' loaded
    2fc775951c34 (ipv4:127.0.0.1:33065) connect to service IPC$ initially as user smbuser (uid=1000, gid=100) (pid 66)
    api_pipe_bind_req: srvsvc -> srvsvc rpc service
    check_bind_req for srvsvc context_id=0
    check_bind_req: srvsvc -> srvsvc rpc service
    api_rpcTNP: rpc command: SRVSVC_NETSHAREENUMALL
    Failed to fetch record!
    pcap cache not loaded
    2fc775951c34 (ipv4:127.0.0.1:33065) closed connection to service IPC$
    Server exit (NT_STATUS_END_OF_FILE)
    Allowed connection from 127.0.0.1 (127.0.0.1)
    init_oplocks: initializing messages.
    Transaction 0 of length 72 (0 toread)
    netbios connect: name1=LOCALHOST      0x20 name2=2FC775951C34   0x0
    netbios connect: local=localhost remote=2fc775951c34, name type = 0
    Transaction 0 of length 216 (0 toread)
    switch message SMBnegprot (pid 67) conn 0x0
    Requested protocol [PC NETWORK PROGRAM 1.0]
    Requested protocol [MICROSOFT NETWORKS 1.03]
    Requested protocol [MICROSOFT NETWORKS 3.0]
    Requested protocol [LANMAN1.0]
    Requested protocol [LM1.2X002]
    Requested protocol [DOS LANMAN2.1]
    Requested protocol [LANMAN2.1]
    Requested protocol [Samba]
    Requested protocol [NT LANMAN 1.0]
    Requested protocol [NT LM 0.12]
    Requested protocol [SMB 2.002]
    Requested protocol [SMB 2.???]
    Selected protocol SMB2_FF
    GENSEC backend 'gssapi_spnego' registered
    GENSEC backend 'gssapi_krb5' registered
    GENSEC backend 'gssapi_krb5_sasl' registered
    GENSEC backend 'spnego' registered
    GENSEC backend 'schannel' registered
    GENSEC backend 'naclrpc_as_system' registered
    GENSEC backend 'sasl-EXTERNAL' registered
    GENSEC backend 'ntlmssp' registered
    GENSEC backend 'ntlmssp_resume_ccache' registered
    GENSEC backend 'http_basic' registered
    GENSEC backend 'http_ntlm' registered
    Selected protocol SMB 2.???
    Selected protocol SMB3_11
    Got NTLMSSP neg_flags=0x62088215
    Got user=[guest] domain=[WORKGROUP] workstation=[2FC775951C34] len1=24 len2=262
    lp_load_ex: refreshing parameters
    Initialising global parameters
    Processing section "[global]"
    pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
    Processing section "[public]"
    Processing section "[users]"
    Processing section "[example1 private]"
    Processing section "[example2 private]"
    adding IPC service
    check_ntlm_password:  Checking password for unmapped user [WORKGROUP]\[guest]@[2FC775951C34] with the new password interface
    check_ntlm_password:  mapped user is: [2FC775951C34]\[guest]@[2FC775951C34]
    check_sam_security: Couldn't find user 'guest' in passdb.
    check_ntlm_password:  Authentication for user [guest] -> [guest] FAILED with error NT_STATUS_NO_SUCH_USER
    No such user guest [WORKGROUP] - using guest account
    Allowed connection from 2fc775951c34 (127.0.0.1)
    idmap range not specified for domain '*'
    Failed to fetch domain sid for WORKGROUP
    Failed to fetch domain sid for WORKGROUP
    Forced user smbuser
    Forced group users
    Connect path is '/tmp' for service [IPC$]
    Initialising default vfs hooks
    Initialising custom vfs hooks from [/[Default VFS]/]
    Initialising custom vfs hooks from [recycle]
    Module 'recycle' loaded
    2fc775951c34 (ipv4:127.0.0.1:42103) connect to service IPC$ initially as user smbuser (uid=1000, gid=100) (pid 67)
    2fc775951c34 (ipv4:127.0.0.1:42103) closed connection to service IPC$
    Server exit (NT_STATUS_END_OF_FILE)
    pid_to_procid: messaging_dgm_get_unique failed: No such file or directory
    Allowed connection from 192.168.1.16 (192.168.1.16)
    init_oplocks: initializing messages.
    Transaction 0 of length 194 (0 toread)
    switch message SMBnegprot (pid 68) conn 0x0
    Requested protocol [PC NETWORK PROGRAM 1.0]
    Requested protocol [MICROSOFT NETWORKS 1.03]
    Requested protocol [MICROSOFT NETWORKS 3.0]
    Requested protocol [LANMAN1.0]
    Requested protocol [LM1.2X002]
    Requested protocol [DOS LANMAN2.1]
    Requested protocol [LANMAN2.1]
    Requested protocol [Samba]
    Requested protocol [NT LANMAN 1.0]
    Requested protocol [NT LM 0.12]
    reply_negprot: No protocol supported !
    Server exit (no protocol supported
    )
    pid_to_procid: messaging_dgm_get_unique failed: No such file or directory

Note that I get the same errors and logs when trying `armv7hf` and `rpi` images. I also tried to recompile the `Dockerfile.armhf` using `arm64v8/alpine:latest` as base image, and still getting the same errors.

My docker info is: https://gist.github.com/g000444555/b7b278278493b015c956e845c90fef50

**Comment by dperson** [comment]
Retry it as follows `smbclient //192.168.1.13/public -U example1 -m SMB3`

You can update the SMB version in your local `smb.conf` if it works or start the container with the `-S` option.

**Comment by g000444555** [comment]
Thank you for the hint.

I managed to connect.

I was getting a NT_STATUS_BAD_NETWORK_NAME

    $ smbclient //192.168.1.13/public -U example1 -m SMB3
    WARNING: The "syslog" option is deprecated
    Enter example1's password: 
    Domain=[D2D4E290206D] OS=[] Server=[]
    tree connect failed: NT_STATUS_BAD_NETWORK_NAME

Until I realised the directory `/share` did not exist and I had to manually create it

    $ docker ps | grep samba
    d2d4e290206d        dperson/samba:armhf   "samba.sh -u examp..."   4 minutes ago      Up 4 minutes (healthy)   0.0.0.0:139->139/tcp, 137-138/udp, 0.0.0.0:445->445/tcp   clever_lumiere
    docker exec -it d2d4e290206d bash
    bash-4.3# mkdir /share
    bash-4.3# chmod 755 /share

Then, I could connect normally.

Also, in order to connect from file manager, and as you recommended, I added the following line to the [global] section of my `smb.conf` in order to attempt use SMB3 by default:

    client max protocol = SMB3

The above configuration is documented here: https://www.samba.org/samba/history/samba-4.1.0.html

**Comment by dperson** [comment]
Glad you got it working.
