### ISSUE TITLE
Failed to retrieve share list from server: Connection timed out.

### ISSUE THREAD

**Issue by csriebel08** [dperson/samba#88]
I believe the problem is with my docker run but I am really unsure what I am doing wrong.  I would like to mount a local volume called /storage to a share in the container.  I can get the server browse able but when clicking on the server I get the error: "Failed to retrieve share list from server: Connection timed out."
could you please tell me what is wrong with my docker run?

 docker run -itd --restart=unless-stopped --name samba --hostname share --network=local-lan --ip=192.168.21.13 -v /storage:/mount -e TZ=America/chicago -e USERID=0 -e GROUPID=0    dperson/samba -n -u "chad;Passowrd" -s "Storage;/mount;no;no;no;chad" -w "WORKGROUP"

this is running on ubuntu 16.04 server with docker CE

Thanks in advance for any help you can provide.

**Comment by dperson** [comment]
First, sorry for the slow reply. On to the main issue:

I'm not familiar with, nor is the `docker run` man page the `--network=local-lan` option that you are using. You are using the `-n` option to start `nmbd` which provides the network browsing functions. My best guess is that the IP address that is being given out by browsing is different than what is in use in the container. Try using `--network=host` instead and see if that doesn't fix it.
