### ISSUE TITLE
UNKNOWN PAM ERROR

### ISSUE THREAD

**Issue by dehy** [dperson/samba#9]
Hi there,

with this setup, impossible to login as a user :
Command : -u "sam;sam" -s "share;/home/sam/share;yes;no;no;sam" -t Europe/Paris

Logs :
smb_pam_account: PAM: UNKNOWN PAM ERROR (4) during Account Management for User: sam
smb_pam_accountcheck: PAM: Account Validation Failed - Rejecting User sam!

Any idea why ?

Thank you :)

**Comment by dperson** [comment]
Hi dehy,

Sorry this got lost in my email bucket. I ran the exact options that you provided, but didn't get the error you describe...

    docker run --rm -Pit dperson/samba -u "sam;sam" -s "share;/home/sam/share;yes;no;no;
sam" -t Europe/Paris                                                                                
    Added user sam.
    smbd version 4.1.17-Debian started.
    Copyright Andrew Tridgell and the Samba Team 1992-2013
    standard input is not a socket, assuming -D option
    STATUS=daemon 'smbd' finished starting up and ready to serve connectionsUnable to connect to CUPS server localhost:631 - Bad file descriptor
    STATUS=daemon 'smbd' finished starting up and ready to serve connectionsfailed to retrieve printer list: NT_STATUS_UNSUCCESSFUL
    Unable to connect to CUPS server localhost:631 - Bad file descriptor
    failed to retrieve printer list: NT_STATUS_UNSUCCESSFUL
    STATUS=daemon 'smbd' finished starting up and ready to serve connections
    canonicalize_connect_path failed for service share, path /home/sam/share

The only error I got was that the directory `/home/sam/share` didn't exist. Once I created it, samba just worked.
