### ISSUE TITLE
Restart loop as docker service (no -i flag)

### ISSUE THREAD

**Issue by davelindquist-egistix** [dperson/samba#92]
This unfortunately does not work as a docker service -- it goes into a restart loop (seems like about every minute in my tests).

It appears that this is due to the fact that there is no "-i" flag when dealing with docker service create.  However, if I'm reading correctly, it seems like the "-it" is used ONLY to prevent it from shutting down?

Could we not modify the samba.sh script to have a "sleep infinity" at the end as an alternative?  Or is there something I'm missing here?

Thanks!

**Comment by davelindquist-egistix** [comment]
Hmm, I think I was premature here.  While it does work correctly as a 'docker run', and does go into a restart loop as a 'docker service', taking a look at things does not seem to indicate the problem as that simple.

More digging required first...

**Comment by htkoca** [comment]
Is there any details from the logs? Or alternatively, if there is no need to run more than one samba container, just use the regular docker run / docker compose.

**Comment by davelindquist-egistix** [comment]
No, unfortunately, the logs don't show anything (just a regular restart).  If I run samba with a much higher debug log, I can see that I get regular errors that look like "interpret_string_addr_internal: getaddrinfo failed for name" plus the name of my container.

It appears that what is happening is that the health check command is failing, and thus triggering a kill and restart of the container -- and I'm guessing the health check is failing because of the above error.

In the end, I just switched to a regular container instead of a service (I didn't REALLY have a need for the service, it was simply convenience).

Thanks!

**Comment by dperson** [comment]
Hmm, I haven't really used the `docker service` commands. The `healthcheck` is connecting to 'localhost' if that's not working, something is very weird in the service network stack... I'm glad that you found a work around though.

**Comment by davelindquist-egistix** [comment]
Yeah, I saw the connect to localhost -- but it seems like somewhere along the line it's using the container name as a hostname (which I think is normal with Docker), but somehow failing to resolve it (which is weird).

If I happen to dig any deeper into it and find a root cause, I'll post an issue.  Thanks!
