### ISSUE TITLE
More samba config support.

### ISSUE THREAD

**Issue by fiture** [dperson/samba#94]
Hi, how can I configuration more samba config options? 
for example: `writeable=true` and so on? Is any way to  specify the config file by docker volumes or other way like blow:

specify the config file like this: `docker run ... dperson/samba -config "[path];writeable=true;path=/data;browsable=yes;readonly=yes;.....and so on"` ?

**Comment by dperson** [comment]
Um, `writeable` is an inverted synonym for `read only` in the samba configuration.
```
    read only = no
    writeable = yes
```
Both mean exactly the same thing.
