### ISSUE TITLE
docker tags based on samba version

### ISSUE THREAD

**Issue by chesty** [dperson/samba#95]
Hi thanks for sharing your container.

Is there any possibility to have finer grained version tags?
It would be more work, I'm sure it could be automated though.

Like 3 tags

latest
samba-4
samba-4.7

So if samba 4.8.x comes out, you don't update samba-4.7 tag anymore, but you don't delete it either,
you do the usual latest tag update and then add the samba-4 and samba-4.8 tag too.

**Comment by dperson** [comment]
I'm not sure how it would be automated. I'm using the distro provided version of samba. So even if the last 4.7 version was tagged, it would never be updated again once they went to 4.8. In short order it would be insecure...

**Comment by chesty** [comment]
Oh ok, I didn't realise you were using the alpine version of samba, 
maybe mirror alpines tags then?

One day you're going to bump the alpine version which might
come with samba 5 for example (this is all a made up scenario) 
which might have incompatibilities with samba 4, and because everyone
is tracking dperson/samba:latest they will get samba 5 the next time
they pull whether they want it or not and break their existing containers.

If I could track dperson/samba:3.7 then my samba version wouldn't change,
and I could pull every night keep the container up to date with the latest alpine 3.7
bug and security fixes.

**Comment by dperson** [comment]
I don't plan on supporting multiple versions of alpine either, so the same issue of falling into being insecure comes back up...

**Comment by chesty** [comment]
OK thanks, David, there's no way to keep your container up to date automatically then, as when you bump the alpine version the samba version might change and could cause issues. 
So I either don't upgrade, and be insecure, or do it manually and check before updating the alpine version and hence samba version hasn't changed.
I'll find another container or roll my own.
Thanks for your work.
