### ISSUE TITLE
You do not have permission to access \\...

### ISSUE THREAD

**Issue by Philiphlop** [dperson/samba#96]
Have been struggling to get access to the file share once it's up. Any help is greatly appreciated. 

`sudo docker run -it --name samba -p 139:139 -p 445:445 
-v /run/mount/datastore001:/mount -d dperson/samba 
-u "root;root" -s "share;/mount;yes;no"`

I can mount this in Windows as a file share, but I cannot open the share. 

`You do not have permission to access \\192.168.0.201\share. Contact your network administrator to request access.`
[https://i.imgur.com/fmRHFpy.png](https://i.imgur.com/fmRHFpy.png)

Logs info

`$ sudo docker logs samba
[sudo] password for me:
adduser: user 'root' in use
Added user root.
smbd version 4.7.3 started.
Copyright Andrew Tridgell and the Samba Team 1992-2017
STATUS=daemon 'smbd' finished starting up and ready to serve connections`

Where do I need to look next?

**Comment by remche** [comment]
Same here. debug log here : https://gist.github.com/remche/4dc1142002f91359b353d803c0c1e631

**Comment by remche** [comment]
@Philiphlop if you tried to mount from Windows, you can try running container with
`-g "ntlm auth = yes"` option

**Comment by Philiphlop** [comment]
Thanks for your input @remche , unfortunately that didn't resolve it. 

I'm not sure what the correct fix is, but I hit some issues with dperson/emby regarding permissions to volumes. For that I have disabled SELinux (I did try with :z appended to the volume command, without any luck), which solved that and my issue here.

Disabling SELinux is not ideal. I would like to understand what I am doing wrong and how I can correct the issue properly.

**Comment by dperson** [comment]
@Philiphlop I have SELinux enabled on my system, and both the samba and emby containers are working for me. As you noted the `:z` is required at the end of the volume arguments. Can you run it again, and send me the logs after you've tried to connect from your windows host?
`sudo docker run -it --name samba -p 139:139 -p 445:445 -v /run/mount/datastore001:/mount:z -d dperson/samba -u "root;root" -s "share;/mount;yes;no"`
Also, I've never tried or thought of using `root` for connecting to samba. Could you test with some other user name as well.

**Comment by htkoca** [comment]
I've had problems with before with `You do not have permission to access` errors and it _could_ be file permissions...

Are the folders owned and accessible by the user defined in the command?
In this case it's `sudo chown -R root:root "/run/mount/datastore001"` and `sudo chmod -R 644"/run/mount/datastore001"`. These commands are recursive and will apply to child folders / files. Permissions I use that worked are 644, 755, and 775 (less secure). Remember to restart the container after any owner / permission changes.

**Comment by dperson** [comment]
If you pass in the `-p` argument, it will fix permissions to the shares for you.

**Comment by Philiphlop** [comment]
I'm still not able to get it working :-(

@htkoca I currently have it all on 777 to try remove layers to the issue. Once it's working I will play with restricting permissions till it's right.

```
$ ll /run/mount/
total 4
drwxrwxrwx. 1 root root 4096 Dec 20 08:52 datastore001
$
$ ll /run/mount/datastore001/
total 0
drwxrwxrwx. 1 root root 0 Dec 20 07:57 app_data
drwxrwxrwx. 1 root root 0 Dec 19 14:11 media
```

@dperson Still not working for me unfortunately. Here is what I've seen. 

```
$ sudo docker run -it \
> --name samba \
> -p 139:139 \
> -p 445:445 \
> -v /run/mount/datastore001:/mount:z \
> -d dperson/samba \
> -u "user;user" \
> -s "share;/mount;yes;no" \
> -p
697309e3cd0a7e322ec6ada814c3a105ec0a23244baeff0925b3aa9f3436272e
$
```
```
$ sudo docker ps --no-trunc
CONTAINER ID                                                       IMAGE               COMMAND                                             CREATED             STATUS                            PORTS                                                     NAMES
697309e3cd0a7e322ec6ada814c3a105ec0a23244baeff0925b3aa9f3436272e   dperson/samba       "samba.sh -u user;user -s share;/mount;yes;no -p"   4 seconds ago       Up 2 seconds (health: starting)   0.0.0.0:139->139/tcp, 137-138/udp, 0.0.0.0:445->445/tcp   samba
$
```
```
$ sudo docker inspect samba 
......
"HostConfig": {
            "Binds": [
                "/run/mount/datastore001:/mount:z"
            ],
......
 "Mounts": [
            {
                "Source": "/run/mount/datastore001",
                "Destination": "/mount",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
......
$
```
```
$ sudo docker logs samba
Added user user.
chown: /mount: Permission denied
chmod: /mount: Permission denied
find: /mount: Permission denied
find: /mount: Permission denied
smbd version 4.7.3 started.
Copyright Andrew Tridgell and the Samba Team 1992-2017
STATUS=daemon 'smbd' finished starting up and ready to serve connections
```

I'm not sure what's missing here :-( Adding in /bin/bash to look inside

```
$ sudo docker rm -f samba
samba
```
```
$ sudo docker run -it --name samba -p 139:139 -p 445:445 -v /run/mount/datastore001:/mount:z -d dperson/samba -u "user;user" -s "share;/mount;yes;no" -p /bin/bash
37069524b9a37244a6bf234e32d2c3031a4e7e1179905c511d1bf9c1fca47339
```
```
$ sudo docker attach samba
bash-4.4# ls -l
total 384
drwxr-xr-x    1 root     root           876 Dec  1 19:51 bin
-rw-------    1 root     root        393216 Dec  1 19:51 core
drwxr-xr-x    5 root     root           380 Dec 20 11:38 dev
drwxr-xr-x    1 root     root           706 Dec 20 11:38 etc
drwxr-xr-x    1 root     root             0 Dec  1 16:32 home
drwxr-xr-x    1 root     root           710 Dec  1 19:51 lib
drwxr-xr-x    1 root     root            28 Dec  1 16:32 media
drwxr-xr-x    1 root     root             0 Dec  1 16:32 mnt
drwx------    2 root     root           100 Dec 20 11:38 mount
dr-xr-xr-x  520 root     root             0 Dec 20 11:38 proc
drwx------    1 root     root             0 Dec  1 16:32 root
drwxr-xr-x    1 root     root            24 Dec 20 11:38 run
drwxr-xr-x    1 root     root           944 Dec  1 19:51 sbin
drwxr-xr-x    1 root     root             0 Dec  1 16:32 srv
dr-xr-xr-x   13 root     root             0 Dec 20 08:41 sys
drwxrwxrwt    1 root     root             0 Dec 20 11:38 tmp
drwxr-xr-x    1 root     root            54 Dec  1 19:51 usr
drwxr-xr-x    1 root     root            78 Dec  1 19:51 var
bash-4.4# 
bash-4.4# ls /mount/
ls: can't open '/mount/': Permission denied
bash-4.4# whoami
root
bash-4.4#
```

My system
```
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
$
$ sudo docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      ec8512b/1.12.6
 Built:           Mon Dec 11 16:08:42 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-68.gitec8512b.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      ec8512b/1.12.6
 Built:           Mon Dec 11 16:08:42 2017
 OS/Arch:         linux/amd64
```

**Comment by dperson** [comment]
I think you were mounting `/run/mount/datastore001` into the docker container. Is that RO on the host system? Just for grins run the following:
```
mkdir /tmp/dockertest
sudo docker run -it --name samba -p 139:139 -p 445:445 -v /tmp/dockertest:/mount:z -d dperson/samba -u "user;user" -s "share;/mount;yes;no" -p bash
ls /mount
touch /mount/test
```
See if that works, the issue lies with the storage you're trying to use.
