### ISSUE TITLE
Cant mount anymore

### ISSUE THREAD

**Issue by remche** [dperson/samba#97]
I use the container since long time (thanks for work !), but my devices (an android box and computers) cant mount the shares anymore. 
For example on my debian laptop :

```
# mount.cifs -vvv //192.168.1.42/goinfre /mnt/tmp -o user=*******
Password for ******@//192.168.1.42/goinfre:  ****************
mount.cifs kernel mount options: ip=192.168.1.42,unc=\\192.168.1.42\goinfre,user=******,pass=********

mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

The log of the container for a failed connection is here 
https://gist.github.com/remche/4dc1142002f91359b353d803c0c1e631

I do not use kerberos or such things. Tried to force ntlm auth with no success. Any idea ?

Note : I use docker-compose to spawn container, but it used to works...

**Comment by remche** [comment]
Got it, had to add min protocol since container is in samba 4.7.
Sorry for the noise, hope it will help others....

**Comment by dperson** [comment]
No problem at all, I'm glad you figured it out.
